### ISSUE TITLE
Failed to import FieldDef when the field is volatile

### ISSUE THREAD

**Issue by AlcatrazDev** [0xd4d/dnlib#100]
http://image.prntscr.com/image/5c7dcfcafc504a1fa3b8266f99240620.png

I've tried to find where the values of Fields where assigned but I'm tired of testing.. need to rest.

**Comment by 0xd4d** [comment]
The field signatures are different (one has a 'required C modifier'). Which method calls FindField()? There's a `IgnoreModifiers` option you can use.

**Comment by AlcatrazDev** [comment]
When reading a DynamicMethod, it needs to resolve the instructions and stuff.

http://image.prntscr.com/image/7f85e479a5ba47aa9a2e04fa0f22b82d.png


They both are the same type, I don't know why only one has a C modifier.

Also, as that task is performed into the DynamicMethodBodyReader.Read, how can I use the ```IgnoreModifiers``` option?

**Comment by 0xd4d** [comment]
`FieldInfo` has `GetOptionalCustomModifiers()` and `GetRequiredCustomModifiers()` methods, but whenever there's 2+ modifiers, it's not possible to know the order of them in the metadata. If there's 0 or 1 modifier, it's possible to restore the signature correctly without checking the metadata.

Try changing [this line](https://github.com/0xd4d/dnlib/blob/b8ca15ff341d7fcf9064f422388ecac65005947b/src/DotNet/Importer.cs#L597) to:

```C#
var fieldSig = new FieldSig(ImportAsTypeSig(fieldInfo.FieldType, fieldInfo.GetRequiredCustomModifiers(), fieldInfo.GetOptionalCustomModifiers()));
```

If it works for you, I'll push the changes to the master branch.

**Comment by AlcatrazDev** [comment]
Everything looks right now :smiley: 

http://image.prntscr.com/image/2f81ac1aecba4cbe8def0d81e03aa116.png

**Comment by 0xd4d** [comment]
:thumbsup:
