### ISSUE TITLE
call method from another module

### ISSUE THREAD

**Issue by RexProg** [0xd4d/dnlib#101]
i want to call special method from System.Windows.Forms.Form such as Dispose but i don't know how can i get this method

i wrote those codes:

```
//method is Dispose as MethodInfo
var methodDef = ModuleDefMD.Load(method.Module)
                                    .Find(method.ReflectedType?.FullName, true)
                                    .FindMethod(method.Name);
//when i want to call it Operand is null
```

and

```
//method is Dispose as MethodInfo
var methodDef =  moduleDef.CorLibTypes.GetTypeRef(method.ReflectedType.Namespace,
                    method.ReflectedType.Name)
                    .Resolve()
                    .FindMethod(method.Name);
//.Resolve() return null
```

how can i call "Dispose " or convert MethodInfo to MethodDef?

**Comment by 0xd4d** [comment]
I'll paste in an old reply that still applies:

This is something you can find out by looking at the IL instructions while debugging in Visual Studio. Compile such a method, load it in dnlib, find the method, get the instructions list, expand it in VS locals window, look at the created types.
