### ISSUE TITLE
Problems when adding more than 1 method to a class

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnlib#105]
I'm trying to clone a method-body to a new method, call that new method from the original and then call a method of my own that fires an event so the result can be editted. I dumbed down the code I made while still reproducing the problem:

```csharp
TypeDef myClass = module.Find("MyType", isReflectionName: true);
for (int i = 0; i < 2; i++)
{
	var signature = MethodSig.CreateInstance(module.CorLibTypes.Void, module.CorLibTypes.String);
	MethodDefUser method = new MethodDefUser("MyMethod" + i, signature);
	method.Body = new CilBody();
	method.Body.Instructions.Add(OpCodes.Ret.ToInstruction());
	method.DeclaringType = myClass;
	method.Attributes = MethodAttributes.Private | MethodAttributes.HideBySig;
}
```
In the code `MyType` is public, non-static, no interfaces, nothing.
After writing out the assembly using dnSpy, Unity (mono) gets TypeLoadException when starting the game. I'm assuming that all types being loaded get this exception. But dnSpy is still able to load the assembly.
Now the interresting thing is:
- The code works if i only run the loop once instead of twice.
- Using dnspy to add 2 methods that look the exact same, there is no problem.
- Adding 2 more methods using dnSpy after running my code still crashes unity
- Removing the 2 methods my code generated while keeping the dnSpy added methods resolves unity crash.

Both dnSpy and my own code write the assembly out with `MetaDataFlags.PreserveAll`.

What is the difference between my code and what dnSpy produces?
What could explain the difference between adding 1 or 2 methods to the type?

**Comment by maritaria** [comment]
Here is a zip with 3 different versions of the resulting assemblies in question: [Assembly-CSharp.zip](https://github.com/0xd4d/dnlib/files/819038/Assembly-CSharp.zip)

- Assembly-CSharp-original.dll - Working version of the dll without methods being added
- Assembly-CSharp-dnspy.dll - Working version of the dll with 2 methods added using dnspy
- Assembly-CSharp-mycode-1.dll - Working version of the dll with 1 method added using my code
- Assembly-CSharp-mycode-2.dll - Crashing version of the dll with 2 methods added using my code

Methods being added: `ModuleItemPickup.MyMethod#()`

Since dnspy is able to load all assemblies, I assume that my code must upset Unity/mono in a paticular way; maybe you could find a slight difference in MD-tokens/offsets etc. or other observations that makes the last assembly different from the rest

**Comment by 0xd4d** [comment]
Before I look at the files, have you actually compared the IL (code + structure) of the working class and non-working class?

**Comment by 0xd4d** [comment]
peverify is also recommended.

**Comment by maritaria** [comment]
@0xd4d Thanks for pointing peverify out to me:
![](http://image.prntscr.com/image/56440db8add341f5b21f7f5cea2d301a.png)

In conclusion: the method were **not static** but did **not specify hasthis** somewhere. Possibly catch this situation when serializing the assembly by throwing an exception.

**Comment by maritaria** [comment]
Im confident it is unrelated to the IL contained in the methods (as they are just a single ret)
I dont know exactly what you ment with structure, but I compared the properties of the `MethodDef` instances of the original and cloned methods that mycode produced and they were the same.



PEVerify results:

Assembly-CSharp-original.dll:
```
[MD]: Error: Invalid token specified as EntryPoint in CLR header.
[MD]: Error: Value class has neither fields nor size parameter. [token:0x0200049F]
[MD]: Error: TypeDef that is not an Interface and not the Object class extends Nil token. [token:0x020010F8]
```
Assembly-CSharp-dnspy.dll:
```
[MD]: Error: Invalid token specified as EntryPoint in CLR header.
[MD]: Error: Value class has neither fields nor size parameter. [token:0x0200049F]
[MD]: Error: TypeDef that is not an Interface and not the Object class extends Nil token. [token:0x020010F8]
```
Assembly-CSharp-mycode-1.dll
```
[MD]: Error: Invalid token specified as EntryPoint in CLR header.
[MD]: Error: Value class has neither fields nor size parameter. [token:0x0200049F]
[MD]: Error: TypeDef that is not an Interface and not the Object class extends Nil token. [token:0x020010F8]
```
Assembly-CSharp-mycode-2.dll
```
[MD]: Error: Invalid token specified as EntryPoint in CLR header.
[MD]: Error: Value class has neither fields nor size parameter. [token:0x0200049F]
[MD]: Error: TypeDef that is not an Interface and not the Object class extends Nil token. [token:0x020010F8]
```

The first error is not an issue; the assembly has been appearing as executable in dnspy for a while without issue.
The seccond error is for a struct class that only contains static methods.
The third error is for a static class that I generated to dump the clones on (this was a solution to the problem, but was kept in after reverting the code to test the different situations).

Specifically peverify did not point out any differences between the mycode-1 and mycode-2 versions; which is where the breaking change is introduced it seems

**Comment by 0xd4d** [comment]
You should compare the IL (the whole class with methods and everything). Compare working class (created by dnSpy) vs your created class.

**Comment by maritaria** [comment]
I thought IL was only for methods; besides the properties on `MethodDef` are there other things I should look at; or do you more specifically mean the IL like bytes of the assembly?

**Comment by 0xd4d** [comment]
Go to the type in dnSpy and change language from C# to IL, then compare old type vs new type. There appears to be no reason at the moment to check anything than the modified types, so diffing the whole assembly shouldn't be necessary.

**Comment by maritaria** [comment]
I have uploaded [ModuleItemPickup-IL.zip](https://github.com/0xd4d/dnlib/files/821119/ModuleItemPickup-IL.zip)
 containing the IL versions of the class:
IL-mycode-0: assembly created using my code, with no methods added (working)
IL-mycode-0-dnspy+2

: assembly created using my code, no methods added, 2 added using dnspy (working)
IL-mycode-1: assembly created using my code, 1 method added (working)
IL-mycode-2: assembly created using my code, 2 methods added (broken)
IL-mycode-2-dnspy-2: assembly created using my code, 2 methods added, and then removed using dnspy (working)

Using the difftool [mergely.com](http://www.mergely.com/editor) I have noticed the following:

The diffs showed minimal edits when mycode added methods (only the method was added, nothing else changed.
The diffs showed that dnSpy reorders some of the attributes (trivial).
The diffs showed that dnSpy changes something about the `RequiredComponent` attribute initialization after adding the 2 methods (comparing `il-mycode-2` with `il-mycode-0-dnspy+2`)

I wonder how I can trigger that optimization to be performed using dnlib

**Comment by maritaria** [comment]
Side note: the dnspy changes were made without having references loaded/available for loading.

**Comment by maritaria** [comment]
![](http://image.prntscr.com/image/2b981242f29840f0954b98ade8ee42a2.png)

**Comment by 0xd4d** [comment]
dnSpy uses code generated by Roslyn.

What you should do is have a look at the exception that is thrown to see if it contains important information about what is wrong with your assembly.

What happens when you edit a simple hello world .NET Framework assembly? Still crashes?

**Comment by 0xd4d** [comment]
What happens if you do NOT preserve the MD tokens?

**Comment by maritaria** [comment]
I didn't use "Edit Code(C#)...", only the menu commands for adding/removing a method from the class (i added ret using the IL editor).

@0xd4d I cant catch the exception, the dll is loaded by the unity player and crashes after trying to initialize some class instances. Also it complains it cant find certain types in the dll.

I will try:
Attaching debugger to unity
Similar edits with a helloworld assembly (though mono wont load that but windows .net, so maybe something different will happen?)

**Comment by 0xd4d** [comment]
Also try what I wrote above about not preserving MD tokens. If you do that the assembly will most likely be an uncompressed assembly (using `#-` heap instead of the normal `#~` heap). It's possible that Mono has some problems with such table heaps.

**Comment by maritaria** [comment]
@0xd4d Im indeed starting to look into what mono does. Though I do need to preserve MD tokens because (as far as I know) those determine field-order and that is what needs to preserved for unity to correctly deserialize instances.

**Comment by maritaria** [comment]
Side note: consider adding a `MetaDataFlags.None = 0` to the enum so you can type-safely specify to not preserve anything.

**Comment by maritaria** [comment]
Fixed by using `MetaDataFlags.PreserveFieldRids` 💃 🕺 😃 😄 
I will check what preservation killed it.
Please log this problem as part of the documentation somewhere
Im so happy this is solved :D

**Comment by maritaria** [comment]
It seems to have fixed the problem, I can get to the unity launcher and click the button to launch the game. However before the game manages to reach the main menu I get another crash; Will have to figure out why that is happening before I can call this issue closed.

Thanks for all your help 👍

**Comment by maritaria** [comment]
Problem unrelated to this issue or dnlib, closing.
PM me your paypal so I can donate to you :)

**Comment by 0xd4d** [comment]
I don't accept donations. :)

So what was the problem then if it wasn't the `#-` heap?

**Comment by maritaria** [comment]
I dont know exactly, I changed the preservation to `PreserveFieldRids` only and the issue disappeared.

**Comment by 0xd4d** [comment]
Well it seems Mono doesn't fully support the `#-` table heap.

You don't even need `PreserveFieldRids` since the only important thing is the order of the fields in the type. And this order is always preserved since the assembly writer uses the order of the fields in the `Fields` property.

**Comment by maritaria** [comment]
@0xd4d alright good to know :)
