### ISSUE TITLE
Custom Blob Sig

### ISSUE THREAD

**Issue by yq8** [0xd4d/dnlib#107]
Hi,
How can I add a _StandAloneSig_ which points to a chunk of data (byte array)?
I would create it like this:

```
RawStandAloneSigRow watermarkBlobSig = new RawStandAloneSigRow();
watermarkBlobSig.Signature = 0x1337;   // ??     
writer.MetaData.TablesHeap.StandAloneSigTable.Add(watermarkBlobSig);
```

But:
1) I don't know where I can define the bytearray I like to add.
2) How should I know the signature (index in blob heap) ?

**Comment by 0xd4d** [comment]
Call `MetaData.GetToken(IList<TypeSig> locals, uint origToken)`

**Comment by yq8** [comment]
Alright, solved. Thanks !
