### ISSUE TITLE
All fields have ElementType = End

### ISSUE THREAD

**Issue by nulldev01** [0xd4d/dnlib#108]
Hello!
All fields in assembly have ElementType = End.
Screen:
![image](https://cloud.githubusercontent.com/assets/17256467/24464419/71b72eda-14b2-11e7-8f83-b3c94f34f6ec.png)
This is error?

**Comment by 0xd4d** [comment]
It means that there's no constant, see the [source code](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/FieldDef.cs#L499)

**Comment by nulldev01** [comment]
Ohh, really, thanks!
