### ISSUE TITLE
ModuleDef.Import vesion

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#109]
MethodInfo mi..
var module=ModuleDefMD.Load("C:\\target.exe");
Instruction ins..
ins.Operand = module.Import(mi)
module.Save("C:\\target2.exe");

If my program is .net 4.0, and "target.exe" is .net 2.0, when I save it, "target2.exe" will ref both .net 4.0 and .net 2.0, so it will run fail because it's runtime is .net 2.0 and can not find .net 4.0 dlls.

**Comment by 0xd4d** [comment]
It uses only the references you give it and nothing more, and don't forget about the asm ref in `ICorLibTypes`.

**Comment by CreateAndInject** [comment]
I think dnlib should do someting when Import(System.Type,System.Reflection....), because If our program is .net 4.0, we can not create a System.Reflection.MethodInfo .net 2.0.

when Import reflection object, dnlib should decide version from module's runtime or module.GetAssemblyRefs()

**Comment by 0xd4d** [comment]
No you should instead open the correct assembly and import that type. Auto changing version numbers and other info like this is not safe at all. What if the type isn't present in the target runtime?

**Comment by CreateAndInject** [comment]
"No you should instead open the correct assembly and import that type."
>>But I can't do it:
`string assemblyName = "System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089";
string assemblyName2 = Assembly.Load(assemblyName).FullName;
//string assemblyName2 = Assembly.LoadFrom(@"C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll").FullName;`

If this code is compiled as .net 4.0, assemblyNmae2 = System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

I can't import .net 2.0 assemblies.

"Auto changing version numbers and other info like this is not safe at all. What if the type isn't present in the target runtime?"

If the version of the imported type is higher, change  it, otherwise keep it.
When importing a higher version assembly type, if don't change the version, the program allways can not run(.net 2.0 can not load 4.0 dlls), if change it, only the type isn't present in the target runtime, it can not run. I mean, don't change it ,100% can not run, change it ,10% can not run.

**Comment by 0xd4d** [comment]
You have to load the assembly using dnlib.

**Comment by CreateAndInject** [comment]
But sometime I don't know the type in advance, it's dynamic, I just get a reflection object.
I think dnlib should support it automaticly, at least support a way like System.Resources.ResourceWriter.**TypeNameConverter**, so I can write any version resources even if my program is .net 4.0 and the reflection object is .net 4.0.

**Comment by 0xd4d** [comment]
Importer is open source, you can just inline the whole thing in your program and patch it to use another version number when it creates a new assembly ref.

**Comment by CreateAndInject** [comment]
I fint it!
Importer.cs line 329:
return module.UpdateRowId(new AssemblyRefUser(asmName.Name, asmName.Version, PublicKeyBase.CreatePublicKeyToken(pkt), asmName.CultureInfo.Name));

=>
return module.UpdateRowId(new AssemblyRefUser(asmName.Name, **module.GetAssemblyRef(asmName.Name)?.Version ??** asmName.Version, PublicKeyBase.CreatePublicKeyToken(pkt), asmName.CultureInfo.Name));
