### ISSUE TITLE
dnlib resolves operand type incorrect

### ISSUE THREAD

**Issue by yq8** [0xd4d/dnlib#113]
Hello.

I have a test application with an instruction like this:
![efamnn2](https://cloud.githubusercontent.com/assets/20257630/24833595/81297aca-1cce-11e7-81b4-d01c540650ad.png)

I try to resolve the _FieldDef_ from the operand, but dnlib fails and tells me the _FieldDef_ is a _MemberRef_.

I am resolving like this:
`var field = (FieldDef)instruction.Operand;`

An exception is thrown:

![5vxkxdi](https://cloud.githubusercontent.com/assets/20257630/24833619/df908a4a-1cce-11e7-9151-d626e3da4d1e.png)

Why can't dnlib resolve the _FieldDef_ ?
TestApp : https://www.sendspace.com/file/zube86

Check the 'DoStuff' method for the instruction.
And yes I am aware that the file is not runnable because it has some token issues, - but this shouldn't be the reason
why dnlib can't resolve the operand correctly.
At the moment the field is not really referenced correctly and I am trying to fix that.
To do so I need to resolve the operand to update it.
Any ideas?

**Comment by CreateAndInject** [comment]
ldsfld string [RuntimeCode]RuntimeCode.Code::field

this "field" is defined in the assembly named "RuntimeCode", so it's a reference in the assembly named "App".

**Comment by yq8** [comment]
nvm - I am stupid.
Fixed it.
