### ISSUE TITLE
TypeLoadException when adding a property while preserving RIDs

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnlib#115]
I was adding (private) field wrapping properties to some classes in a dll. Code:
```csharp
private static void WrapField(TypeDef type, string fieldName, string propertyName)
{
	FieldDef field = type.Fields.First(f => f.Name == fieldName);
	var propertySignature = PropertySig.CreateInstance(field.FieldType);
	var property = new PropertyDefUser(propertyName, propertySignature);
	type.Properties.Add(property);
	
	var getterSignature = MethodSig.CreateInstance(field.FieldType);
	MethodDefUser getter = new MethodDefUser("nuterra_get_" + propertyName, getterSignature, MethodAttributes.Public | MethodAttributes.HideBySig);
	getter.DeclaringType = type;
	getter.Body = new CilBody();
	getter.Body.Instructions.Add(OpCodes.Ldarg_0.ToInstruction());
	getter.Body.Instructions.Add(OpCodes.Ldfld.ToInstruction(field));
	getter.Body.Instructions.Add(OpCodes.Ret.ToInstruction());
	property.GetMethod = getter;
}
```

Preservation settings:
```csharp
writerOptions.MetaDataOptions.Flags = MetaDataFlags.PreserveFieldRids | MetaDataFlags.PreservePropertyRids;
```
The type and field already exist in a loaded module, the property and method are being added (there are no name collisions).

This code created a TypeLoadException (no info given in logs) with preserving RIDs is enabled. The issue does not occur when not preserving RIDs. This shouldn't be an issue for the method since I have been adding methods before while preserving RIDs, Though I think it may have something to do with adding the property. If it turns out you know some other reason why this could cause some kind of malfunction in mono let me know.

Also weird is that the tokens, RIDs, RVAs and file offsets are the same between the fixed and broken versions. However, the size of the working dll is slightly smaller (~10kb). 

Finally the broken dll can be fixed by loading it in dnSpy and (without modifications) writing it out again with preserving RIDs disabled.

I can send you a copy of both dll's if you are interrested.

**Comment by 0xd4d** [comment]
Mono/unity doesn't seem to support the `#-` table, https://github.com/0xd4d/dnlib/issues/105#issuecomment-284538507 so don't preserve rids. It's not needed as explained in that post, all that's needed is the field order.
