### ISSUE TITLE
Problem on the OnWriteEvent

### ISSUE THREAD

**Issue by xXxRevolutionxXx** [0xd4d/dnlib#117]
I found out that the OnWriteEvent is raised only when you write the module(ModuleDefMD) to a file in the disk... but it doesn't raised if you write it to a Stream.

**Comment by 0xd4d** [comment]
Do you have a repro? `Write(string)` calls `Write(Stream)` so there should be no differences.

**Comment by xXxRevolutionxXx** [comment]
What do you mean repro ? I tried to write it on a memory stream but the event didn't fired. Anyway, now i write in the disk using the Write(string) "version" and then i take it's stream... there is a solution for someone to play around.

**Comment by SlowLogicBoy** [comment]
repro = code that would show how to reproduce your problem. How we could get an error just like you do.

**Comment by xXxRevolutionxXx** [comment]
This is the repro:  https://pastebin.com/CLEav8pd

Thanks @SlowLogicBoy

**Comment by 0xd4d** [comment]
It's not a repro since I can't compile that code. A whole lot of code is missing. Most likely you haven't added your listener and that's the reason your code isn't called.

**Comment by 0xd4d** [comment]
See the other `Write()` overload that takes writer options.

**Comment by xXxRevolutionxXx** [comment]
I have the listener properly configured. Anyway i used the Write() with the options and now it seems to work. Maybe it has something to do with the options ? I don't know. Anyway... i am closing the issue :)
