### ISSUE TITLE
Why sometimes <Module>.cctor can not run in .net 1.1, but sometimes can?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#118]
I use dnlib to add some code to `<Module>.cctor`, but `<Module>.cctor` can run in some programs, but don't run in another programs, these will run Main method directly.

.Net 2.0+ don't like this.

**Comment by 0xd4d** [comment]
Use a .NET 1.x debugger (dnSpy won't work, it hasn't been tested with the .NET 1.x debugging API) or WinDbg and have a look at the exception. Also run peverify (the one built for .NET 1.x) and see what it says.

**Comment by CreateAndInject** [comment]
I get it.
Peverify is unusefull for this.

.Net 1.1 always don't run <Module>.cctor.

"but <Module>.cctor can run in some programs"

That's because these is an indirect call in Main method, such as:

Main()->Program.SomeMethod()-><Module>.SomeMethod()

I mean, <Module>.cctor don't run auto in .net 1.1, but if its member is called, <Module>.cctor will run.
