### ISSUE TITLE
Why there are GetAssemblyRefs and GetMemberRefs in ModuleDefMD but no GetTypeRefs?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#119]
Why there are GetAssemblyRefs and GetMemberRefs in ModuleDefMD but no GetTypeRefs?

**Comment by 0xd4d** [comment]
These methods are in the base class, and also the base class has a `GetTypeRefs()` method.

**Comment by CreateAndInject** [comment]
I'm sorry, I used the old version.
dnlib move GetAssemblyRefs/GetMemberRefs from ModuleDefMD to ModuleDef, and add GetTypeRefs in 2015.10.22
