### ISSUE TITLE
Changing namespace does not update when passed as generic argument as part of attribute

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnlib#121]
I am trying to move classes from the nameless namespace (not all, specific groups) to a new namespaces. But after executing my code i got a argument null exception on a type passed to an attribute.

Assembly before edit:
```csharp
public class ManThing
{
    [My(typeof(GenericClass<NestedThing>))]
    private object _field;

    public class NestedThing {}
}
public class GenericClass<T> {}
```
Code doing the modification:
```csharp
var module = ModuleDefMD.Load("some.dll");
var unnamedNamespace = module.Types.Where(t => t.Namespace == "");
foreach (var type in unnamedNamespace.Where(t => t.Name.StartsWith("Nested")))
{
	type.Namespace = "TerraTech.Managers";
}
module.Write("some.other.dll");
```
After the edit the generic parameter of `_field` is not updated correctly, it still points to a type in the nameless namespace.

This is not the case when editing the type with dnSpy.

**Comment by 0xd4d** [comment]
Types in custom attributes are stored as strings in the `#Blob` heap. If you edit it in dnSpy, you have decompiled the class including `_field` so its custom attribute has been read and the type has been found.

A workaround is to read all custom attributes of all types and their members before renaming.

**Comment by 0xd4d** [comment]
Something like this could work:

```C#
ModuleDef mod = /*...*/;
foreach (var t in mod.GetTypes()) {
	foreach (var f in t.Fields) {
		var dummy = f.CustomAttributes;
	}
	foreach (var m in t.Methods) {
		var dummy = m.CustomAttributes;
		foreach (var p in m.ParamDefs) {
			dummy = p.CustomAttributes;
		}
	}
	foreach (var p in t.Properties) {
		var dummy = p.CustomAttributes;
	}
	foreach (var e in t.Events) {
		var dummy = e.CustomAttributes;
	}
}
```

**Comment by xoofx** [comment]
Hey @0xd4d, I was going other a similar problem but I'm curious about your workaround. How does accessing `xxx.CustomAttributes;`  changes things in the types in dnspy? Is `mod.GetTypes()` going to return more types after visiting the custom attributes?

**Comment by 0xd4d** [comment]
`mod.GetTypes()` returns the same value as before. The example above just loads all types and any attribute that could be referencing a type before renaming it since attributes have string refs to types instead of TypeRefs.

If you're renaming a type/member, you can use `MemberFinder` to find all of them. (see the issues, there are a few issues about that class). Generic MemberRefs aren't shared since they have a gp context. So if you rename one MemberRef, the other ones that reference the same type also need to be renamed.

**Comment by xoofx** [comment]
So I have been using the MemberFinder and trying to rename juts namespaces with the following code:

```csharp
            var finder = new MemberFinder();
            finder.FindAll(module);

            var assembly = module.Assembly;
            assembly.Name = UpdateName(assembly.Name);
            foreach (var moduleDef in module.Assembly.Modules)
            {
                moduleDef.Name = UpdateName(moduleDef.Name);
            }
            foreach (var assemblyReference in module.GetAssemblyRefs())
            {
                assemblyReference.Name = UpdateName(assemblyReference.Name);
            }
            foreach (var type in finder.TypeDefs.Keys)
            {
                type.Namespace = UpdateName(type.Namespace);
            }
            foreach (var typeReference in finder.TypeRefs.Keys)
            {
                typeReference.Namespace = UpdateName(typeReference.Namespace);
            }
            foreach(var method in finder.MethodDefs.Keys)
            {
                method.Name = UpdateName(method.Name);
            }
            foreach(var prop in finder.PropertyDefs.Keys)
            {
                prop.Name = UpdateName(prop.Name);
            }

            var newFile = UpdateName(Path.GetFileName(filePath));
            assembly.Write(Path.Combine(destFolder, newFile));
```

but I can still see that some types are missing from the renaming when I look with an hex editor. For instance, generic type arguments.
Is it the right approach to perform a namespace renaming?

**Comment by 0xd4d** [comment]
Use `type.GenericParameters` to get all type generic params and rename their `Name` prop. And `method.GenericParameters` to get method generic parameters.

Note that the code you showed renames the metadata, not eg. any names in resource files or in baml files etc.

**Comment by xoofx** [comment]
Actually, that was not generic parameters (because I was looking more at generic arguments), but it seemed that some methods had their names like `System.Collections.Generic.IEnumerable<NamespaceAToReplace.TypeToKeep>.GetEnumerator` so that's where these names were coming from the IL.

**Comment by 0xd4d** [comment]
Well if you rename every method those names should be renamed too. The Roslyn C# compiler gives them names similar to that if you implement an interface method explicitly `void IFace.Method() { ... }`

If you use dnSpy's hex editor you should be able to hover over the string and it should hopefully show you the token that references it in the tooltip.

**Comment by 0xd4d** [comment]
Or if there's no token, search for the method name in eg. dnSpy.
