### ISSUE TITLE
How to completly delete instructions from a given method?

### ISSUE THREAD

**Issue by Mefist0** [0xd4d/dnlib#127]
Hello all!

So my question is in the name of the issue: how to completly delete instructions from a given method?
I have an obfuscated assembly, I wrote a little program using dnLib to deobfuscate it.
I just replace unnecessary instructions with Nop OpCode. But after this manipulation I have IL-code with many nops. I tryied to use method.Body.Instructions.RemoveAt(index), but this doesn't work properly.

Please, help me!

P.S.: why there is no any documentation for this great project!?

**Comment by XenocodeRCE** [comment]
Docu is in the main readme file :-)

`I tryied to use method.Body.Instructions.RemoveAt(index), but this doesn't work properly.` it does, what is is happening ? Describe your issue :-)

**Comment by Mefist0** [comment]
> It's a list implementing IList<Instruction> so you can use the normal Add/Remove/etc methods to modify it.
Yes, but as I said already, when I do `method.Body.Instructions.RemoveAt(index)` some methods are becoming corrupted and dnSpy cannot display theirs bodies(in C#).
Everuthing looks logically, but doesn't work properly. Perhaps, I made a mistake.

**Comment by 0xd4d** [comment]
Some instructions reference other instructions (branch and switch) and then there are exception handlers that also reference the instructions. If you remove an instruction you have to update everything else that references the instruction. If you just want to nop an instruction, don't remove it, just change it to NOP.

**Comment by Mefist0** [comment]
> Some instructions reference other instructions (branch and switch) and then there are exception handlers that also reference the instructions. If you remove an instruction you have to update everything else that references the instruction. If you just want to nop an instruction, don't remove it, just change it to NOP.

Thank you! But I don't understand why linear code (without brances, switches and exception handlers) is being damaged.
Anyway, the damaged code seems unused. Looks like it's just for obfuscating manual analysis of a assembly.
