### ISSUE TITLE
Remove methods from type

### ISSUE THREAD

**Issue by Mefist0** [0xd4d/dnlib#130]
Hello all!

I need a help again :)
How to remove methods from a type?
I'm trying to delete them like this (just example):

`if (type.HasMethods)
{
  for (int i = 0; i < type.Methods.Count; i++)
  {
       MethodDef method = type.Methods[i];                    
       type.Methods.Remove(method);
  }
}`
I see in debugger that method is removed from type.Methods list, but after saving assembly all methods are in the type.

Any ideas?
Thanks in advance!

**Comment by bprg** [comment]
Try the following code.

```
            foreach (TypeDef type in module.Types)
            {
                foreach (MethodDef method in type.Methods)
                {
                    type.Remove(method);
                }
            }
```

**Comment by Mefist0** [comment]
@bprg > Try the following code.
Unfortunately, you cannot edit a collection while you iterate it through by foreach :)

**Comment by Mefist0** [comment]
Fu***ing .NET! I had to iterate my collection backwards. Oh, God!

**Comment by 0xd4d** [comment]
You don't even need a loop if you're removing every method, just call `type.Methods.Clear()`.

**Comment by 0xd4d** [comment]
Regarding your question, make sure you open the saved assembly and not the original assembly. Closing since I can't repro.
