### ISSUE TITLE
edit TabelStream 

### ISSUE THREAD

**Issue by BeginnerBoy** [0xd4d/dnlib#131]
how can access to edit TableStream ?

            ModuleDefMD mod = ModuleDefMD.Load("App.exe");
            MDTable mdTable = mod.MetaData.TablesStream.MemberRefTable;
            mdTable.(...)

**Comment by 0xd4d** [comment]
It's read only. If you want to edit something, you have to figure out the offset of the data in the file and write to the file. All tables implement `IFileSection` which contains the start/end offsets.
