### ISSUE TITLE
ModuleWriterException: Instruction has been removed but it's referenced by PDB info

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#134]
In the latest version, there is a random exception shlwing up:
`dnlib.DotNet.Writer.ModuleWriterException: Instruction has been removed but it's referenced by PDB info`
I can not reproduce it myself (it would be too easy :smile: ), but some of Mr Advice users are experiencing it.
Does it ring a bell to you? This is very likely to be related to the latest changes.

Thanks.

**Comment by 0xd4d** [comment]
Some instruction was removed but it's still referenced by the data needed to write the PDB. It's similar to when you remove an instruction but it's still being referenced by some exception handler instance. If you don't want to scan all possible references to an instruction, the safest way is to just keep it but change it to a NOP.

**Comment by 0xd4d** [comment]
I updated the error message to include more context, BP method and current method: https://github.com/0xd4d/dnlib/commit/8546dcf0bd812b84cb7669e6b370fa02d0e2dab9

It's related to async methods.

**Comment by picrap** [comment]
Thank, I've updated and a new Mr Advice package is currently being built. However the odd thing is that I don't remove anything from the original assembly. We'll see :smile:

**Comment by hhblaze** [comment]
Such construction fails
var res = Task.Run(async () => await test()).Result;

Error log:
https://github.com/ArxOne/MrAdvice/issues/106#issuecomment-321459918

**Comment by 0xd4d** [comment]
Original issue was fixed in other repo.
