### ISSUE TITLE
Custom BlobSignature

### ISSUE THREAD

**Issue by yq8** [0xd4d/dnlib#139]
Hello.

Is there a way to create a custom blob signature with a chunk of bytes and add it to the assembly using dnlib?
If yes, what dnlib class can I inherit from to create my own BlobSignature?

**Comment by 0xd4d** [comment]
The blob writer is here: https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/MetaData.cs#L385

To get an instance of the MetaData class with that property you have to add your own listener to https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/ModuleWriterBase.cs#L32

**Comment by yq8** [comment]
So, I was able to create the writer and listener.
I added a new  entry to the Standalonesig table.
But how can I link it to a byte[] chunk?

```
case ModuleWriterEvent.MDEndCreateTables:
{
    var tableHeap = writer.MetaData.TablesHeap;
    tableHeap.StandAloneSigTable.Add(new RawStandAloneSigRow(123));
    break;
}
```
