### ISSUE TITLE
Create temporary assembly

### ISSUE THREAD

**Issue by yq8** [0xd4d/dnlib#140]
Hello,

Is there a way to create a new .NET application from scratch, with a main() method without loading an external file?
That would be useful for unit testing, so I don't need to add many different files as resources but can create them on the runtime instead to perform certain tests on them?
If it is possible is there already an example code posted somwhere?

Regards,
yq8dev

**Comment by UlyssesWu** [comment]
Have you seen the [Example3](https://github.com/0xd4d/dnlib/blob/master/Examples/Example3.cs)?
