### ISSUE TITLE
[Feature Request] Find Type by Namespace+Name

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#141]
Please add feature that can be searched Type by Namespace+Name.
```
if (ModuleDef.Find(typeDef.Namespace, "<CLR>" + typeDef.Name) != null)
{
 return false;
}
```
https://github.com/jbevain/cecil/blob/fc5cb9f07720ca7b4ce8c26ba34c3723e81d00ac/Mono.Cecil/ModuleDefinition.cs#L680

**Comment by 0xd4d** [comment]
There is a Find method that takes a full name as input and returns a type, just concatenate namespace and name or add an extension method that does it.
