### ISSUE TITLE
rename type (dll with exe) / ValueTypeSig

### ISSUE THREAD

**Issue by BeginnerBoy** [0xd4d/dnlib#142]
hello 

I have two problems

the first how can the use of  (ValueTypeSig)

`TypeRef stream = new TypeRefUser(modDLL, "System.IO","Stream",nativeEmbDLL.CorLibTypes.AssemblyRef);
                            ValueTypeSig sig = new ValueTypeSig(stream);
                            getField.FieldSig.Type = stream .TryGetValueTypeSig();`

or 

`TypeRef stream = new TypeRefUser(modDLL, "System.IO","Stream",nativeEmbDLL.CorLibTypes.AssemblyRef);
                            ValueTypeSig sig = new ValueTypeSig(stream);
                            getField.FieldSig.Type = sig;`

all do not work

the second how can rename the TypeDef (dll)
without crash main file (exe use call import some types from dll).

:)

**Comment by 0xd4d** [comment]
1st. System.IO.Stream is not a value type so you're using the wrong class.

2nd. You can't change the type of a public member without breaking code that reference it from another assembly. You have to update all the places.

**Comment by BeginnerBoy** [comment]
i trying call struct with ValueTypeSig but it always set ClassSig

that is what I want ( example dnspy ):
https://imgur.com/a/vGeOp

🤕

**Comment by 0xd4d** [comment]
Seems like you haven't initialized a module context, https://github.com/0xd4d/dnlib#resolving-references

**Comment by BeginnerBoy** [comment]
i have dll and exe 
will have modulecontext for exe ? or dll?
