### ISSUE TITLE
CustomSig with byte[]

### ISSUE THREAD

**Issue by yq8** [0xd4d/dnlib#143]
Hey,
So as you mentioned in #139 I implemented the listener and the writer.
The goal is to create a byte[] and reference the blob in the _StandaloneTableSig_ entry.
How am I supposed to do that.
For now I just figured out how to create a table-entry and pass in some blob index.
But how can I create the actual blob data and reference it properly in the table entry?
I came up wit this so far:

```
case ModuleWriterEvent.MDEndCreateTables:
{
    var tableHeap = writer.MetaData.TablesHeap;
    // How to create the blob data and reference it properly?
    tableHeap.StandAloneSigTable.Add(new RawStandAloneSigRow(1234)); // Some blob Index
    break;
}
```

**Comment by 0xd4d** [comment]
Call `BlobHeap.Add(xxx)`, it returns an index you can add to the standalone sig table.

**Comment by yq8** [comment]
That causes a readonly exception.

```
case ModuleWriterEvent.BeginWriteChunks:
{
    string data = "AAAAAAAAAAAABBBBBBBBBBBBCCCCCCCCCCCCC";
    var bytes = Encoding.UTF8.GetBytes(data);
    var offset = writer.MetaData.BlobHeap.Add(bytes);
    Console.WriteLine(offset);
    break;
}
```

**dnlib.DotNet.Writer.ModuleWriterException: 'Trying to modify #Blob when it's read-only'**

**Comment by yq8** [comment]
Solved - was suing the wrong writing event.
Need to do it during `MDBeginCreateTables`
