### ISSUE TITLE
Question about StepInfos

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#144]
Hi,

I upgraded to the latest version, and the following does not build anymore:
```csharp
                var stepInfos = innerMethod.Body?.PdbMethod?.AsyncMethod?.StepInfos;
```
because there is no `AsyncMethod` property anymore.
So where are the `StepInfos` related to an async method?

Thanks.

**Comment by picrap** [comment]
Is the following OK?
```csharp
var stepInfos = innerMethod.CustomDebugInfos.OfType<PdbAsyncMethodCustomDebugInfo>().SelectMany(d => d.StepInfos).ToArray();

```

**Comment by 0xd4d** [comment]
It's the correct custom debug info yes. I think the compiler only adds at most one though (doesn't seem to make sense to add more than one).

**Comment by picrap** [comment]
Yes, it makes sense. Thanks.
