### ISSUE TITLE
Double backslash in strings

### ISSUE THREAD

**Issue by Rottweiler** [0xd4d/dnlib#145]
Strings set with Instruction[i].Operand = "\x20"; seem to get double backslashes

**Comment by 0xd4d** [comment]
I can't repro this. Could you show what string you get and a simple program to repro this?

**Comment by Rottweiler** [comment]
Var sb = New stringbuilder();
Sb.append(”\x90”);
Var line = sb.tostring(); and then set operand

**Comment by 0xd4d** [comment]
The `StringBuilder` seems useless since it doesn't change anything. You're also using a different string in both examples "\x20" vs "\x90".

Anyway I still can't repro it.

What is the string you write and what is the string that you see in the saved image?

**Comment by Rottweiler** [comment]
I use a string builder because I iterate through a lot of bytes, and write them as such “\x90” the number doesn’t matter

**Comment by Rottweiler** [comment]
If I write \x90 with the stringbuilder then it turns out as \\x90

**Comment by Rottweiler** [comment]
Sorry autocorrect is on my phone I mean \\x90 of course

**Comment by Rottweiler** [comment]
Double backslash is what I’m trying to write

**Comment by 0xd4d** [comment]
Show your code. Double backslash usually means that you're looking at a string the variables window because the debugger shows \ as \\.

**Comment by Rottweiler** [comment]
https://i.imgur.com/exWQdw2.png

**Comment by Rottweiler** [comment]
All I do is basically set .Operand = "\x90" and it becomes double-backslashed

**Comment by 0xd4d** [comment]
Where's the code?

Show the string, byte by byte. `Encoding.UTF8.GetBytes(xxxxxxx)`
