### ISSUE TITLE
Reading resources after writing

### ISSUE THREAD

**Issue by Rottweiler** [0xd4d/dnlib#146]
How do you read resources written using this method:

                var res = new EmbeddedResource(new UTF8String("data"), memorystream.ToArray(), ManifestResourceAttributes.Public);
                stub.Resources.Clear();
                stub.Resources.Add(res);

When it writes it without a namespace

**Comment by 0xd4d** [comment]
The resources are just blobs of data. There's a .NET reader and writer available (`dnlib.DotNet.Resources.ResourceReader`) that can read the files in a .NET multi resource blob. .NET Framework should have a similar reader but it requires loading the assembly at runtime and deserialization.

**Comment by Rottweiler** [comment]
Ah okay I understand. Thanks for answering my question.
