### ISSUE TITLE
Support MDB files

### ISSUE THREAD

**Issue by mazegen** [0xd4d/dnlib#147]
Are there any plans to support (loading/writing) MDB files?

I know that dnlib is kind of similar to Cecil. I've been looking into `Mono.Cecil.Mdb` but it doesn't seem to be easily portable to dnlib but I don't know the dnlib internals good enough.

**Comment by 0xd4d** [comment]
There are no plans to do it. It's used by mono / unity, but AFAIK they're switching to portable PDBs + roslyn.

**Comment by mazegen** [comment]
You're right, Mono moved to csc.exe and PDB recently. The only reason is Unity that adopts new mono features slowly. I understand that this is not a strong motivation to do it. Thanks for your reply anyway.
