### ISSUE TITLE
It's confused between new AssemblyRefUser(IAssembly) and IAssembly.ToAssemblyRef()

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#149]
I think IAssembly.ToAssemblyRef should take a bool  parameter to decide whether to keep the same behavior with new AssemblyRefUser(IAssembly) or not.

**Comment by 0xd4d** [comment]
It creates a new AssemblyRef, what is it exactly that you want it to do different?

**Comment by CreateAndInject** [comment]
I want to modify the scope of a TypeRef, my first thought is:
```
TypeRef tr..;
tr.ResolutionScope = someAssemblyDef.ToAssemblyRef();
or
tr.ResolutionScope = new AssemblyNameInfo(fullname).ToAssemblyRef()
```
but it doesn't work
The following can work:
```
tr.ResolutionScope = new AssemblyRefUser(someAssemblyDef)
or
tr.ResolutionScope = new AssemblyRefUser(new AssemblyNameInfo(fullname))
```

So, I think it's confused.

**Comment by 0xd4d** [comment]
You can create an extension method that does what you want.
