### ISSUE TITLE
Question about MemberFinder

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#151]
After MemberFinder.FindAll, there are elements in mf.CustomAttributes, but there's none element in mf.TypeRefs,
for example:
```
MemberFinder mf = new MemberFinder();
mf.FindAll(mdUser);
foreach (var ca in mf.CustomAttributes.Keys)
    foreach (var caa in ca.ConstructorArguments)
        foreach (var obj in new[] { caa.Type, caa.Value })
            if (obj is TypeSig)
            {
                var tr = (obj as TypeSig).TryGetTypeRef();
                if (tr != null)
                   //=== the program can run to here, but why don't mf.TypeRefs contains "tr"?
            }
                                    
```

I debug it ,and find:
```
		void Add(TypeSig ts) {
			if (ts == null || TypeSigs.ContainsKey(ts))
				return;
			if (ts.Module != validModule)
				return; //=== here
```

**Comment by 0xd4d** [comment]
It finds the references to definitions in the current module only. Those typerefs are most likely references to mscorlib.

**Comment by CreateAndInject** [comment]
I have added breakpoints for all checking validModule.
Generally speaking, it seems xxx.Module != validModule always is false except xxx.Module == null for normal module. When using ModuleDefUser and adds some types from another module, it may be true.
Should it add a bool parameter to decide whether to check the module rather than allways check?

**Comment by 0xd4d** [comment]
It was designed to only find refs in the same module to defs in the same module.
