### ISSUE TITLE
Resolve Method with mdtoken

### ISSUE THREAD

**Issue by RexProg** [0xd4d/dnlib#152]
How can i resolve method with mdtoken? 
like ResolveMethod in System.Reflection
https://msdn.microsoft.com/en-us/library/k16h33dz(v=vs.110).aspx

**Comment by bprg** [comment]
https://github.com/0xd4d/dnlib#resolving-types-methods-etc-from-metadata-tokens

**Comment by 0xd4d** [comment]
And also eg. `module.ResolveToken(mdToken.Raw)`.
