### ISSUE TITLE
dnlib and Reflection returning different values

### ISSUE THREAD

**Issue by Pirajew** [0xd4d/dnlib#161]
```
Assembly assembly = Assembly.LoadFrom(@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll");
Console.WriteLine(assembly.GetModules()[0].GetTypes()[0].GetMethods()[0]);

AssemblyDef assemblyDef = AssemblyDef.Load(@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll");
Console.WriteLine(assemblyDef.Modules[0].Types[0].Methods[0]);
```

Both of these statements are returning completely different values on the same assembly. The top one is Reflection, the bottom is dnlib. Why is this happening? Shouldn't they return the same method?

**Comment by 0xd4d** [comment]
Reflection doesn't return the global type, dnlib does. Reflection GetTypes() returns all types, including nested types. dnlib's Types returns non-nested types. Use GetTypes() if you want all types.

**Comment by Pirajew** [comment]
Thank you for your reply, that explains it.

The reason I was asking is because I am looping through all function in a DLL and attempted to execute them with MethodInfo.Invoke(). The ones that execute without error will have the index of the type and method outputted to a txt file. Then, using Dnlib, I was going to read through each line (each line contains the index of the type and method) and add that method into an executable. Since the index won't be the same for GetTypes()/GetMethods() and Types/Methods, is there any way I could convert the Type/MethodInfo to TypeDef/MethodDef? I'm trying to get the same index values reflection so it grabs the right type/method.

**Comment by Pirajew** [comment]
UPDATE: I got the Types sync'd up(it's off by one, but that can be fixed obviously). However there doesn't appear to be a "GetMethods" function in dnlib.

```
Assembly assembly = Assembly.LoadFrom(@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll");
Console.WriteLine(assembly.GetModules()[0].GetTypes().Length);

AssemblyDef assemblyDef = AssemblyDef.Load(@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll");
Console.WriteLine(assemblyDef.Modules[0].GetTypes().ToList().Count);
```

**Comment by 0xd4d** [comment]
Seems like you deleted your reply. What you're looking for is the metadata token (MDToken in dnlib, MetadataToken in reflection) and then use ResolveToken() to get the method.

**Comment by Pirajew** [comment]
Thanks, I did delete my replies because I wasn't sure how to phrase them properly. Is there an example how to use the ResolveToken/ITokenResolver to parse an MDToken?
