### ISSUE TITLE
generic struct ref parameters

### ISSUE THREAD

**Issue by tgrindinger** [0xd4d/dnlib#162]
Suppose you have a generic `struct` and want to do something neat with `this` inside some method, like pass it to `Console.WriteLine`. Maybe you just want to print `this` out every time the constructor for a generic `struct` is called. This is just an example, of course.

I can call `param.Type.ToByRefSig().Next` to get a `TypeSig` for `this`, but I can't convert that into something that I can box up. It seems fairly insistent that it's NOT a generic sig, and it omits the `<T, U>` stuff whenever I convert it to a `TypeDef` with `ToTypeDefOrRef()`. This kind of makes sense in the context of the tree structure of sigs, and I'm not surprised it doesn't work.

For return values, which are `GenericInstSig` for generic `struct`s, I can just call `OpCodes.Box.ToInstruction(method.ReturnValue.ToTypeDefOrRef())`, and it works great, but I can't figure out a way to do the same for `ref` parameters. My first thought was to manually create a `GenericInstSig` from the `TypeSig`, but I'm having trouble wrapping my head around that process.

Am I heading along the right track? If so, could you give me some pointers on how to do that? If not, what's the proper method for getting this done?

Thanks for any help you can provide! I can show some code if anything isn't clear.

Edit: removed misleading summary

**Comment by 0xd4d** [comment]
Short answer: Write the code in C#, then have a look at the code in a disassembler or check the method's instructions in the Locals window.

**Comment by tgrindinger** [comment]
Already done that. My problem isn't knowing what IL to write. It's knowing how to tell dnlib to write what I want. How do I get dnlib to write `box SomeType``2<T,U>` instead of `box SomeType``2`, which is what I want.

**Comment by bprg** [comment]
@tgrindinger Try this example https://github.com/saneki/dnlib-examples

**Comment by 0xd4d** [comment]
Have you tried the locals window? Load the method, have a look in the locals/watch window. Expand body, and check the interesting instruction. You'll see exactly what classes where used (is it a MemberRef or a MethodDef, the locals/watch windows will tell you exactly what's needed)

**Comment by tgrindinger** [comment]
@bprg Thanks very much! That's very helpful.
