### ISSUE TITLE
I want to only import a typeref or methoref , no il call methodref 

### ISSUE THREAD

**Issue by littlewisp** [0xd4d/dnlib#164]
Importer importer = new Importer(mod);
    ITypeDefOrRef consoleRef = importer.Import(typeof(System.Console));
    IMethod writeLine = importer.Import(typeof(System.Console).GetMethod("WriteLine"));

if  il calls writeline, consoleref and writeline exisites in meta data.
if no il calls writeline, consoleref and writeline does not appear  in meta data.
is there a soulution

**Comment by 0xd4d** [comment]
The solution is to add it to the metadata. You can do that when writing the file. Your listener gets called at various stages, and you have a chance to modify the metadata, eg. add those references even if no-one uses them.

**Comment by littlewisp** [comment]
Thank you very much
