### ISSUE TITLE
Type.GUID equivalent

### ISSUE THREAD

**Issue by enemyofthedawn** [0xd4d/dnlib#168]
Is there some equivalent to Type.GUID?

https://msdn.microsoft.com/en-us/library/system.type.guid(v=vs.110).aspx

Or it's randomly generated?

**Comment by enemyofthedawn** [comment]
Nevermind, it's generated internally by the CLR: https://github.com/dotnet/coreclr/blob/7f7d8276e65059a37001aaa5ce9af7e82249f4a0/src/vm/methodtable.cpp#L7377

**Comment by 0xd4d** [comment]
Yes, but I think it uses the GUID attribute if one exists.
