### ISSUE TITLE
Conflicted files when I want merge commits into Yck from 0xd4d

### ISSUE THREAD

**Issue by ElenaMilito** [0xd4d/dnlib#176]
Can you please help me to merge?
https://github.com/ElenaMilito/dnlib/pull/1

**Comment by 0xd4d** [comment]
> Can you please help me to merge?

Good one. April 1st was 5 days ago. :)

**Comment by ElenaMilito** [comment]
Still says can't automatically merge.

![screenshot](https://user-images.githubusercontent.com/9071462/38434719-3ddb4dce-3984-11e8-912e-274829b4c705.png)
