### ISSUE TITLE
Target multiple frameworks in dnlib.netstandard.csproj

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnlib#177]
Changing `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFrameworks>net35;netstandard2.0</TargetFrameworks>` (note the plural framework**s**) will generate assemblies targeting both frameworks on build. When adding dnlib as a project reference, it will allow the compiler to pick whichever framework type is most appropriate (for example net35 for a .NET Fx 3.5+ app, .NET Standard 2.0 for a .NET Core app) and potentially avoid adding 96 extra DLLs.

Personally, I can't use the old csproj file due to a VS bug, so I'm forced to use the .NET Standard one.

**Comment by HoLLy-HaCKeR** [comment]
You can also make package references optional, based on what configuration is being built. I noticed you have references to `System.Reflection.Emit` and `System.Reflection.Emit.Lightweight`, so you can make that ItemGroup only apply on .NET Standard builds.

**Comment by SlowLogicBoy** [comment]
Adding `net35` to `netstandard.csproj` would break builds on platforms that do not support net framework/mono, and would destroy sole purpose of why we made `netstandard.csproj`.

>Personally, I can't use the old csproj file due to a VS bug, so I'm forced to use the .NET Standard one.

Why this project has to fix the bug you are refering to :) ?

**Comment by HoLLy-HaCKeR** [comment]
I'm not so sure about that, it sounds pretty illogical that the compiler would stop completely if it encountered one configuration it doesn't support :P I'll try it real quick and report back if it does indeed break it.

**Comment by SlowLogicBoy** [comment]
Is mono installed?

**Comment by 0xd4d** [comment]
Closed by the PR
