### ISSUE TITLE
exception loading module

### ISSUE THREAD

**Issue by RexProg** [0xd4d/dnlib#179]
`var module= ModuleDefMD.Load(typeof(Type).Module); ` => Exception Message : "It is not possible to get address of module"

what's wrong?

**Comment by SlowLogicBoy** [comment]
As it says, it can't find the address where Module is stored in memory.
If you are using netstandard version try using framework one.

**Comment by RexProg** [comment]
i use cs-script in vscode

**Comment by 0xd4d** [comment]
And it's probably using .NET Core. Use typeof(int).Assembly.Location instead
