### ISSUE TITLE
MethodBodyChunks.Remove has been removed

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#180]
How to remove a body from MethodBodyChunks?

**Comment by 0xd4d** [comment]
This method doesn't seem to have ever existed.

**Comment by li0nsar3c00l** [comment]
Aparently it's part of yck1509's mod of dnlib, see https://github.com/yck1509/dnlib/blob/master/src/DotNet/Writer/MethodBodyChunks.cs#L86
