### ISSUE TITLE
StringsHeap.GetAllRawData return empty

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#181]
In latest version StringsHeap.GetAllRawData return empty.

```
void OnWriterEvent(object sender, ModuleWriterEventArgs e) {
   if (e.Event == ModuleWriterEvent.MDEndAddResources) {
   IEnumerable<KeyValuePair<uint, byte[]>> data = e.Writer.Metadata.StringsHeap.GetAllRawData();
   }
}
```

**Comment by 0xd4d** [comment]
Try event `EndCalculateRvasAndFileOffsets` instead. The #Strings heap is now optimized and the offsets aren't known until later.

**Comment by 0xd4d** [comment]
I think the `#Strings` stream can be initialize this earlier, eg. before `MDEndCreateTables`

**Comment by 0xd4d** [comment]
Use event `BeginCalculateRvasAndFileOffsets`
