### ISSUE TITLE
TablesHeap.ManifestResourceTable the 'Name' return invalid value

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#182]
```
if (e.Event == ModuleWriterEvent.BeginCalculateRvasAndFileOffsets) {
  var nameVal = e.Writer.Metadata.TablesHeap.ManifestResourceTable[1].Name;
}
```

**Comment by 0xd4d** [comment]
It's a `#Strings` index, use `StringsHeap.GetOffset(uint)` to get the `#Strings` offset. This method can only be called starting from event `BeginCalculateRvasAndFileOffsets`.
