### ISSUE TITLE
Inserting before Ldc opcode is freezing my Application

### ISSUE THREAD

**Issue by netlool** [0xd4d/dnlib#184]
Hey, im trying to insert a Nop Instruction before a Ldc opcode, but everytime im doin this my Application freezes:

```C#
 if (body.Instructions[i].IsLdcI4())
                            {
    body.Instructions.Insert(i , Instruction.Create(OpCodes.Nop));
}
```

---
I don't know what the issue is, but i think it adds more than one instruction

**Comment by 0xd4d** [comment]
> I don't know what the issue is, but i think it adds more than one instruction

How could it possibly add more than one instruction if you just added it once?

I need a repro since your example isn't enough. Try to run peverify.exe on it after just that change.
