### ISSUE TITLE
Moving StartupStub to new section

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#187]
I want remove StartupStub from TextSection then add StartupStub to new section but return exception in save process **(Can't add a relocation when the relocs section is read-only)**, Older versions (Ver 2.0) do not have this problem, How to resolve this problem?
```
        	void OnWriterEvent(object sender, ModuleWriterEventArgs e) {
			if (e.Event == ModuleWriterEvent.MDEndCreateTables) {
				var section = new PESection("New", 0x60000020);
				var moduleWriter = e.Writer as ModuleWriter;
				uint alignment = e.Writer.TextSection.Remove(moduleWriter.StartupStub).Value;
				section.Add(moduleWriter.StartupStub, alignment);
				e.Writer.Sections.Add(section);
			}
		}
```

**Comment by 0xd4d** [comment]
I don't see a good reason to move it. It's nothing special at all, no secrets etc.

Try moving it in some other event, eg. `ChunksCreated`

**Comment by 0xd4d** [comment]
When you add a new section, add it before the .relocs section if it exists. That will probably solve your problem.

**Comment by 0xd4d** [comment]
Also note that StartupStub can be null, so you have to add extra checks for that.

**Comment by bprg** [comment]
StartupStub contain Entry Point I want move Entry Point to new section, I tried all Events the problem was not resolved.

**Comment by 0xd4d** [comment]
See my two previous replies that you probably haven't read yet.

**Comment by bprg** [comment]
I added new section before .relocs the problem solved, Thanks.
