### ISSUE TITLE
Native PDB writer fail in debug time

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#189]
How to prevent fail in debug time?

https://github.com/0xd4d/dnlib/blob/28a07e9648f5d0e7efbe61889e75a4de0f3d8e04/src/DotNet/Pdb/WindowsPdb/WindowsPdbWriter.cs#L246

**Comment by 0xd4d** [comment]
Add some repro steps

**Comment by bprg** [comment]
I created new project **CLR Console App** FW 4 IDE : VS 2017 ver 15.6.6.

```
var mod = ModuleDefMD.Load(@"D:\ConsoleApplication6.exe");
var opts = new NativeModuleWriterOptions(mod, true);
opts.WritePdb = true;
opts.PdbFileName = @"D:\ConsoleApplication60.pdb";
mod.NativeWrite(@"D:\ConsoleApplication60.exe", opts);
```

**Comment by 0xd4d** [comment]
The source code to `ConsoleApplication6` needs to be shown too. I can't repro this.

**Comment by bprg** [comment]
I created empty project, I attached binary and source.
[ConsoleApplication6.zip](https://github.com/0xd4d/dnlib/files/1930781/ConsoleApplication6.zip)

**Comment by 0xd4d** [comment]
It's a C++/.NET project, that's why I couldn't repro it.

**Comment by bprg** [comment]
The behavior is strange, I attached a screencast.
[Screencast.zip](https://github.com/0xd4d/dnlib/files/1930909/Screencast.zip)
