### ISSUE TITLE
Getting error : Identifier expected; 'in' is a keyword

### ISSUE THREAD

**Issue by B-Esmaili** [0xd4d/dnlib#193]
When i wanna build the project i get preceding error in `DotNet\MD\RidList.cs` in following block :

```
internal Enumerator(in RidList list) {
				startRid = list.startRid;
				length = list.length;
				rids = list.rids;
				index = 0;
				current = 0;
			} 
```

**Comment by 0xd4d** [comment]
You need C# 7.2 to compile it, i.e., the latest VS.

**Comment by B-Esmaili** [comment]
could i just install the language but not the IDE?
