### ISSUE TITLE
Why do you write "ResourceReader" yourself instead of System.Resources.ResourceReader?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#195]
System.Resources.ResourceReader can read any version of .resources file, but your dnlib.DotNet.Resources.ResourceReader can't read .net 1.1 .resources file, so why do you write this class? Does this class surpass System.Resources.ResourceReader in some way?

**Comment by 0xd4d** [comment]
The answer is similar to: why use dnlib and not reflection?

dnlib's class doesn't load the assembly and doesn't deserialize random data stored in resources (could execute any random code). It was needed by de4dot and now also by dnSpy.

If you don't care about any of that, and if you can load the assembly and don't care that a random assembly got loaded into your process, then go ahead and use the framework's resource reader. It can deserialize anything stored in resource files as long as it can load the assembly.
