### ISSUE TITLE
Set MethodBodyBytes as 0x00

### ISSUE THREAD

**Issue by Radck** [0xd4d/dnlib#196]
how can i set method body bytes to 0x00 on module writer listener ??
like i show method body in hex editor dnSpy and fill selection bytes with 0x00 byte and save file.

**Comment by 0xd4d** [comment]
There's a `writer.Metadata.GetMethodBody(MethodDef)` method that returns the `MethodBody`. You can then write to its `Code` and `ExtraSections` arrays.
