### ISSUE TITLE
Why GenericArgument Scope is null?

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#197]
![sc](https://user-images.githubusercontent.com/706507/40904081-8452968a-678e-11e8-9f1a-57bd85a28492.png)

**Comment by 0xd4d** [comment]
Because someone wrote null to it? It's impossible to tell from this picture.

**Comment by bprg** [comment]
Please try with PaintDotNet project.

```
var moduleDefMd = ModuleDefMD.Load(@"C:\paint.net4.19\PaintDotNet.exe");
foreach (var typeDef in moduleDefMd.GetTypes())
{
   var field = typeDef.FindField("<filePath>i__Field");
   if (field != null)
   {
      var scope = field.FieldSig.Type.Scope;
   }
}
```

**Comment by 0xd4d** [comment]
I assume it's a generic parameter. They don't have scopes.
