### ISSUE TITLE
Why when the TypeDef call to ToTypeSig the MdToken changed to TypeSpec but IsTypeSpec return false?

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#198]
```
foreach (var typeDef in moduleDefMd.GetTypes())
{
   var typeSig = typeDef.ToTypeSig();
}
```
https://prnt.sc/jrn14c

**Comment by 0xd4d** [comment]
IsTypeSpec returns true if it's a TypeSpec which TypeSigs aren't. TypeSpecs have a ref to a TypeSig, it's stored in the #Blob. TypeSigs implement IType and implement MDToken and have to return a value so it returns a TypeSpec token.
