### ISSUE TITLE
Example Code for Reading PDB files 

### ISSUE THREAD

**Issue by tgiphil** [0xd4d/dnlib#201]
Is there any example code for reading PDB files, specifically the SequencePoints?

Thanks in advance.

**Comment by 0xd4d** [comment]
The sequence points are stored in the method bodies so just iterate over all types and all methods and get the method body. Then iterate over all instructions and check if it has a sequence point.

**Comment by tgiphil** [comment]
Thanks for pointing me in the right direction.
