### ISSUE TITLE
get method of resolved typesiq

### ISSUE THREAD

**Issue by Radck** [0xd4d/dnlib#202]
i wanna find a resolved methoddef from a resolved typedef , out of the current module (mscorelib) then replace it.
there is two options here :
with import: module will have two mscorlib in refrences( v2.0 and v4.0 )
without import: after saving module call operand will be null

**Comment by 0xd4d** [comment]
It will help a lot if you add code to reproduce this.

**Comment by Radck** [comment]
`FieldDef field = Module.GlobalType.Fields[*];`
`TypeDef type = field.FieldType.ToTypeDefOrRef().ResolveTypeDef();` https://ibb.co/fmOazy
`MethodDef method = type.Methods[*];`
Now i need to create a memberRef of method to use in a call instruction
I tested: 
`MemberRefUser memberRef = new MemberRefUser(Module, methodInfo.Name, methodInfo.MethodSig);` but didn't work.

**Comment by 0xd4d** [comment]
What I meant is can you show the minimum code that reproduces this? The code above are just snippts that won't compile.

**Comment by Radck** [comment]
hmmm,
i can't put it here
can i send you an email?

**Comment by 0xd4d** [comment]
I prefer a short repro example, but if it's not possible send an email with repro steps and I'll have a look when I have time.

**Comment by 0xd4d** [comment]
Nothing received, closing.

**Comment by Radck** [comment]
bro i sent it via email De4dot@gmail.com
what's your gmail?

**Comment by 0xd4d** [comment]
Email again

**Comment by Radck** [comment]
i sent it again

**Comment by 0xd4d** [comment]
Post the link to the file here or attach it. There's no email, and nothing in the spam folder.
