### ISSUE TITLE
System.TypeLoad Exception

### ISSUE THREAD

**Issue by Mighty00** [0xd4d/dnlib#204]
Hey, why am I getting an Exception in this file? The Instructions should be fine, so i think its an issue with this: 
 Local lcl = new Local(ppctx.Importer.Import(typeof(System.TimeSpan)).ToTypeSig());
 body.Variables.Add(lcl);

[File.zip](https://github.com/0xd4d/dnlib/files/2207302/File.zip)

**Comment by 0xd4d** [comment]
You don't have an assembly resolver. See the README.
