### ISSUE TITLE
ModuleWriter Error when using X86CpuArch EntryPoint

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#205]
Hello,

I encountered an problem when trying to write a module that contains a `dnlib.DotNet.Writer.StartupStub` with an `dnlib.DotNet.X86CpuArch`. The problem that happens during the execution of `dnlib.DotNet.Writer.ModuleWriterBase.CalculateRvasAndFileOffsets` where the offsets of the element chucks are set.  
First the offsets of the `dnlib.DotNet.Writer.PESection` is set. This function calls the `SetOffset` function of an instance of `dnlib.DotNet.Writer.RelocDirectory`. This directory is set as read-only once this happens. The `StartupStub`, more specifically the x86 implementation tries to add the `StartupStub` into the assembly the was set ealier set at read-only. And at this point the writer fails.

The issue can be reproduced by the "AntiTamper" UnitTests in this feature branch of the ConfuserEx project:
https://github.com/mkaring/ConfuserEx/tree/feature/antitamper_unittest

You'll find the backtrace of the error here:
https://ci.appveyor.com/project/mkaring/confuserex/build/8#L281

If dnlib works as expected I am grateful for any hints regarding what I am doing wrong when using it.

**Comment by 0xd4d** [comment]
I haven't checked the ConfuserEx code, but if you're adding new sections, make sure that the reloc section (if it exists, it can be null) is always the last section.

**Comment by 0xd4d** [comment]
Check for refs to `ModuleWriter.Sections`, if there's code adding new sections, make sure you add it before the relocs section.

I should document this.

**Comment by mkaring** [comment]
Thank you! That helped a lot. I was able to track the problem down.

**Comment by 0xd4d** [comment]
I added a new helper method that will do this automatically, `ModuleWriterBase.AddSection()`. The writer now verifies that the reloc section is last.
