### ISSUE TITLE
dnlib doesn't show any methods in GlobalType ("<Module>" type)

### ISSUE THREAD

**Issue by NBNGaming** [0xd4d/dnlib#206]
Hello! There are two methods in GlobalType in my assembly: .cctor and external umanaged method. But dnlib doesn't show them in GlobalType.Methods (Count = 0). dnSpy and Mono.Cecil (I used a similar code) show them. What am I doing wrong?

**Comment by 0xd4d** [comment]
dnSpy uses dnlib so if dnSpy shows you those methods then there's most likely a bug in your code. Verify that you're opening the same file that dnSpy opened.

**Comment by NBNGaming** [comment]
Oh, I'm sorry. You are right. It was the wrong file. Understand me, I killed two days for debugging this. Thank you!
