### ISSUE TITLE
Replace a string to a method in if-else block statement bug

### ISSUE THREAD

**Issue by 0x7d9** [0xd4d/dnlib#207]
**ForTest.exe**

using System;
namespace ForTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string result;
            bool b = true;
            if (b)
                result = "A";
            else
                result = "B";

            Console.WriteLine(result);
            Console.ReadLine();
        }
        static string B()
        {
            return "B";
        }
    }
}

**Replace string ‘B’ to method ‘B()’**

        static void Main()
        {
            ModuleDefMD module = ModuleDefMD.Load("ForTest.exe");
            foreach (TypeDef type in module.Types)
            {
                for (int j = 0; j < type.Methods.Count; j++)
                {
                    MethodDef method = type.Methods[j];
                    Console.WriteLine(method.Name);
                    for (int k = 0; k < method.Body.Instructions.Count; k++)
                    {
                        Instruction ins = method.Body.Instructions[k];

                        if (ins.OpCode == OpCodes.Ldstr && (string)ins.Operand == "B")
                        {
                            method.Body.Instructions[k] = OpCodes.Call.ToInstruction(type.Methods[1]);
                        }
                    }
                }
            }
            module.Write("ForTest_1.exe");
        }
**Error:**
dnlib.DotNet.Writer.ModuleWriterException:“Error calculating max stack value. If the method's obfuscated, set CilBody.KeepOldMaxStack or MetadataOptions.Flags (KeepOldMaxStack, global option) to ignore this error. Otherwise fix your generated CIL code so it conforms to the ECMA standard.”
![1](https://user-images.githubusercontent.com/37729896/43518181-d165e6f4-95bd-11e8-81bc-cb6e197ba64d.png)

**And I use cecil do the something have no problem.**

        static void Main(string[] args)
        {
            var assembly = AssemblyDefinition.ReadAssembly("ForTest.exe");
            var module = assembly.MainModule;

            foreach (var type in module.Types)
            {
                for (int j = 0; j < type.Methods.Count; j++)
                {
                    var method = type.Methods[j];

                    ILProcessor il = method.Body.GetILProcessor();

                    Console.WriteLine(method.Name);
                    for (int k = 0; k < method.Body.Instructions.Count; k++)
                    {
                        Instruction ins = method.Body.Instructions[k];

                        if (ins.OpCode == OpCodes.Ldstr && (string)ins.Operand == "B")
                        {
                            method.Body.Instructions[k] = il.Create(OpCodes.Call, (type.Methods[1]));
                        }
                    }
                }
            }
            module.Write("ForTest_1.exe");
        }

**Comment by 0xd4d** [comment]
I don't get that exception. I get an error saying that you've removed an instruction that is referenced by another instruction. Eg. there's a branch instruction that references the instruction you overwrite.

The easiest way to fix this is to not remove the instruction, but instead overwrite its OpCode and Operand values.

**Comment by 0x7d9** [comment]
Sometimes I get the same exception as you. I solved problem with your method, thank you! @0xd4d
