### ISSUE TITLE
Infinite Loop when loading assembly 

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#210]
I encountered an error when trying to load an assembly. In the attachment you find a project to create an assembly that causes the error.

[DnlibInfiniteLoop.zip](https://github.com/0xd4d/dnlib/files/2286805/DnlibInfiniteLoop.zip)

If you try to load `Assembly1` you will find that dnlib enters a loop to leads to a `StackOverflowException` when trying to resolve the assembly attribute.

I hope you can reproduce the problem. I encountered the problem when trying to obfuscate an assembly with the same structure using ConfuserEx. The assemblies provided will cause the error when loaded in ConfuserEx as well.

If you have problems reproducing the error let me know.

**Comment by 0xd4d** [comment]
I can't repro it, could you write a simple console program that repros this? I suspect that my example doesn't resolve the same assemblies as your code does.

**Comment by 0xd4d** [comment]
I was able to reproduce it. Can you confirm that my fix fixes this.

**Comment by mkaring** [comment]
The error shows up for me when I set up the assembly resolver in a specific way.
Loading the assembly like this leads to the error:

```C#
static void Main(string[] args) {
	var asmResolver = new AssemblyResolver() {
		EnableTypeDefCache = true
	};
	asmResolver.DefaultModuleContext = new ModuleContext(asmResolver);
	ModuleDefMD.Load("Assembly1.dll", asmResolver.DefaultModuleContext);
}
```

**Comment by mkaring** [comment]
Your fix solves the issue.

**Comment by 0xd4d** [comment]
OK, thanks for reporting the issue and verifying the fix!
