### ISSUE TITLE
Adding generic parameters to method does not update MethodSig

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#212]
Hello,

I noticed that the method signature is not updated when adding new generic parameters to a method. I added some generic parameters to the lazy list `dnlib.DotNet.MethodDef.GenericParameters`, expecting that the listener on this list will update the generic parameter count in the signature of the method. How ever it is not doing just that.

Is adding generic parameters expected to be done another way or is this actually an error?
I can easily update the generic parameter count in the signature by hand.

**Comment by mkaring** [comment]
Also I just noticed that the `Generic` flag is not set or unset for the method if the first generic parameter is added or the last is removed. I guess that should happen automatically as well?

**Comment by 0xd4d** [comment]
It's supposed to match the metadata and since metadata allows the method generic params count to not match the method sigs param count, dnlib allows that too. So in other words you have to update both.

**Comment by mkaring** [comment]
It seems strange that the signatures of the method parameters are updated automatically and the generics are not.

What is the reason to have the generics and the signature mismatch? `peverify` is all over the methods with mismatched signature generics count and method generics.

**Comment by 0xd4d** [comment]
Like I said, if the metadata allows it dnlib should also allow it, even if the CLR throws or peverify shows an error message.

> It seems strange that the signatures of the method parameters are updated automatically and the generics are not.

When are the method parameter types updated automatically, it should be done by calling UpdateParameterTypes().

**Comment by mkaring** [comment]
It does so automatically.

I am talking about the Parameter list accessed in [`dnlib.DotNet.MethodDef.Parameters`](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/MethodDef.cs#L450). You can get a parameter with the [indexer](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/ParameterList.cs#L68). If you alter the [`TypeSig`](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/ParameterList.cs#L403) of this parameter [`dnlib.DotNet.ParameterList.TypeUpdated`](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/ParameterList.cs#L210) is invoked and there the signature of the method is changed.

**Comment by mkaring** [comment]
It just seemed inconsistent.
But you are right. It is easy to fix if you know it. :wink:

I'll leave it at that.
