### ISSUE TITLE
Question: OptimizeMacros - Ldc_I8

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#215]
Hello,

The `dnlib.DotNet.Emit.MethodInfo.OptimizeMacros` function currently only optimises single instructions to  the fitting short form.

According to [this][1] it is recommended to optimise the `Ldc_I8` instruction to a `Ldc_I4` instruction and a `Conv_I8` instruction in case the value can be expressed with no more than 32 bit.

Since this operation adds (or removes in case of simplify) an instruction from the method, this is a new case for the `OptimizeMacros` function. For this reason I'll ask before submitting an pull request.  
Is this optimisation something you would consider adding to the `OptimizeMacros`? Or do you consider this out of scope for the function?

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldc_i4?redirectedfrom=MSDN&view=netframework-4.7.2#remarks

**Comment by 0xd4d** [comment]
> Or do you consider this out of scope for the function?

Yes, it's supposed to keep the instructions not add/remove instructions. It should only change it from long to short form.

**Comment by mkaring** [comment]
Okay. 👍  Works for me too.
