### ISSUE TITLE
Assembly not loading after writing with dnlib

### ISSUE THREAD

**Issue by trevisscott** [0xd4d/dnlib#216]
I have an assembly that when I modify it with dnSpy it runs but when writing with dnlib the assembly doesn't run.

- Assembly is obfuscated.
```
var opts = new ModuleWriterOptions(Module);

opts.MetadataOptions.Flags |= MetadataFlags.PreserveAll |
					MetadataFlags.KeepOldMaxStack |
					MetadataFlags.AlwaysCreateBlobHeap |
					MetadataFlags.AlwaysCreateGuidHeap |
					MetadataFlags.AlwaysCreateStringsHeap |
					MetadataFlags.AlwaysCreateUSHeap;

opts.Logger = DummyLogger.NoThrowInstance;
Module.Write(ModulePath);
```

I noticed when I save the assembly/module using dnSpy the file offset of the function I modify is different than when I save the assembly using dnlib. Also the assembly isn't mixed-mode or doesn't contain any native methods.

**Comment by 0xd4d** [comment]
Do you use the same settings that dnSpy uses? And you can debug it with dnSpy to see where it crashes.

**Comment by trevisscott** [comment]
Yes, I use the same settings that dnSpy uses. When I debug to see where it crashes
![image](https://user-images.githubusercontent.com/43643125/47041509-f6095700-d156-11e8-8457-8308e4792602.png)

I also check the PE Headers, I also tried adding the MetadataFlags.RoslynSortInterfaceImpl that dnSpy adds but dnlib doesn't, and it doesn't work.

**Comment by trevisscott** [comment]
I tried and verified the options are the same except the Flags that dnSpy add `MetadataFlags.RoslynSortInterfaceImpl`, I tried without and with and it still doesn't work.

Do you think it is because the way I use the importer to modify a method?

**Comment by 0xd4d** [comment]
The pic above shows it throws because the memberref token is invalid. dnlib can preserve the memberdef tokens only, see the PreserveRids documentation.

**Comment by 0xd4d** [comment]
Wrong.

You can use dnSpy to compare the memberref tables. Check the metadata nodes, select all rows and copy it. Then use your favorite diff program.

**Comment by trevisscott** [comment]
I tried that and it looks fine

**Comment by 0xd4d** [comment]
You should compare every single row (copy, and use a diff tool), so either you know they're identical or not. Were they identical?
