### ISSUE TITLE
OK Button is Disabled when editting IL Instruction from obfuscated file

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnlib#220]
I was trying to remove the antitamper and antidump of this application and when i try to edit it. i noticed that the ok button is disabled.

Attachment:
https://cdn.discordapp.com/attachments/507400704621543435/507544769254129674/nou.exe

**Comment by 0xd4d** [comment]
You have to figure out why it's disabled, this is most likely not a dnlib issue. My guess is that the protector has checks and if the checks fail, the OK button is disabled.
