### ISSUE TITLE
Question: How to inject "if else"

### ISSUE THREAD

**Issue by YoungBased** [0xd4d/dnlib#221]
Hello,
Long interested in this question, decided to ask, looking for mono.cecil, too, is not found.
Can please you create a small example?

**Comment by 0xd4d** [comment]
Write the code in C#, look at the IL code, use the same code.

**Comment by UlyssesWu** [comment]
You can also use Reshaper's IL Viewer to check the IL code of the method you're writing, or you can use http://sharplab.io/ . For `br` instructions, the operand is another instruction.
