### ISSUE TITLE
how to change RID

### ISSUE THREAD

**Issue by Asmge5** [0xd4d/dnlib#222]
Please tell me how to change the RID method or type without damaging the application.

**Comment by 0xd4d** [comment]
Explain some more what you're trying to do.

**Comment by Asmge5** [comment]
I'm trying to shuffle the RID methods and classes, but all attempts fail. I would like to ask if it is possible to do this, and perhaps, if it is not difficult for you, to give a small example.
Thx.

Dnspy -. PE -> Storage Stream -> Tables Stream -> Method -> RID, Token, Offset etc ..

**Comment by 0xd4d** [comment]
You can shuffle the `Fields`/`Methods`/`Types`/etc properties before saving the module.

**Comment by Asmge5** [comment]
I did it. Thanks for your reply.
