### ISSUE TITLE
Decompile to source code

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnlib#223]
Is there a simple way to decompile a type / method to source code (just plain text view, nothing else needed)? I would like to switch from Mono.Cecil to dnlib but I'm currently using ICSharpCode.Decompiler which doesn't understand dnlib.

**Comment by SlowLogicBoy** [comment]
You can use [Modified ICSharpCode.Decompiler](https://github.com/0xd4d/ILSpy/tree/6c5d01bad289002b02854b954e61e8fe1300eb96) that understands dnlib

**Comment by Symbai** [comment]
Thank you SlowLogicBoy for the links, I'll check out the modified decompiler.
