### ISSUE TITLE
Create a nuget package

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnlib#225]

**Comment by 0xd4d** [comment]
This is not an official build: https://www.nuget.org/packages/dnlib/

I've contacted the owner to see if I can get ownership of it.

**Comment by mylemans** [comment]
Maybe you found it already: https://docs.microsoft.com/en-us/nuget/policies/dispute-resolution

**Comment by MeikTranel** [comment]
@0xd4d is there anything you need help with while the dnlib ownership issue is resolved?

**Comment by vatsan-madhavan** [comment]
Is [https://www.nuget.org/packages/dnlib-new](https://www.nuget.org/packages/dnlib-new) an official package?

**Comment by 0xd4d** [comment]
> is there anything you need help with while the dnlib ownership issue is resolved?

No I'm just waiting a couple of more days before I'll contact nuget again.

> Is https://www.nuget.org/packages/dnlib-new an official package?

No, that's not mine, my nuget account name is the same as my github account name.

**Comment by 0xd4d** [comment]
I've notified nuget again, but it's december so it could possibly take a while before something happens.

**Comment by 0xd4d** [comment]
I'm now the owner of https://www.nuget.org/packages/dnlib/ and have uploaded 3.1.0.
