### ISSUE TITLE
Optimize writing method bodies

### ISSUE THREAD

**Issue by dyarkovoy** [0xd4d/dnlib#228]
@0xd4d, I've been experimenting with multithreading to speed up writing, got 3x performance boost with some simple locking and 10 threads on a 6 core CPU. I modified only `Metadata.WriteMethodBodies()` as the most expensive part (3x refers only to `WriteMethodBodies`, not the whole process). I believe the result can be further improved by optimizing locks and splitting other parts into parallel jobs.

Would you be interested in merging this improvement?

Not ready for PR yet because I need to understand the extent of changes you are willing to tolerate, if your answer to the question above is "yes". For example, would you consider dropping net35 target completely? This would give a benefit of ConcurrentDictionary vs. plain lock()'s and Parallel.ForEach() vs. manual thread management.
Maybe create a "4.0-beta" branch for this?
Let me know your thoughts.

**Comment by 0xd4d** [comment]
There's a problem with generating a DLL with multiple threads. Each run will very likely generate a different binary because the first time method body A is before method body B but the 2nd time it's the reverse order. This is sometimes important and sometimes not important (depends on the user).

How long does it take to save the assembly? Shouldn't take more than a few seconds even if it's a big one. We trade saving a few seconds (maybe 2-4?) for extra complexity. This will probably require changes in all writer classes.

**Comment by dyarkovoy** [comment]
If you mean ordering of methods inside the global method table stream in the file - it should be easy to sort the table right before it is written, if you mean ordering of members inside types - order will not change, I was going to process only types in parallel, there is no sense to parallelize processing of type members. In any case, it is possible to have a switch whether to use multithreading or not.
I have >50mb assemblies here that take around 30-40 sec. It's not a big deal if you do it once, but if you run continuous tests after some minor changes, multithreading could save some time. But I see where you're coming from and I must agree that the majority of the users aren't going to need this. No problem, I'll see if I can do it in my fork. Thanks for the response.

**Comment by 0xd4d** [comment]
I think there could be an easy fix that doesn't require adding locks all over the place. The method body writer requries a ITokenProvider, so if you pass in a new class that implements that interface that locks each time the methods are called, do you still get 3x speedup?

**Comment by dyarkovoy** [comment]
No, it actually slows down almost 2x when locking inside ITokenProvider proxy. These GetToken() methods are used so frequently that the threads end up waiting for each other most of the time, rather than doing something useful. I believe the best way is to replace Dictionaries with ConcurrentDictionaries in row and heap caches.

**Comment by 0xd4d** [comment]
Writing method bodies is just one part of writing the .NET file. What's the total time writing that DLL without any optimization and total time after the optimization?

**Comment by dyarkovoy** [comment]
Working with smaller assemblies now (about 20Mb), and I had to add more locks. My current results are not that exciting (total write time / method bodies write time): 

- before optimization: 11.6s / 6.4s
- after optimization: 9.5s / 4.5s

I guess we can suspend this issue for now, it's not worth the effort with these results.
