### ISSUE TITLE
Add more code examples

### ISSUE THREAD

**Issue by CaptainPRICE** [0xd4d/dnlib#229]
I do find myself stuck with this library.
I would really appreciate if you would add more examples.

How to create a new delegate definition?
How to add a new custom attribute to some member definition?
How to create native/import definitions (platform invoke)?

Here's my attempt to create a new delegate definition with some attribute metadata:
(I managed to set an attribute, everything else is a fail. I am assuming latest C# version.)
```csharp
TypeDefUser typeDef = new TypeDefUser("dnlib_Test", "UserCreatedDelegate", mod.CorLibTypes.GetTypeRef(typeof(MulticastDelegate).Namespace, nameof(MulticastDelegate)));
typeDef.Attributes = TypeAttributes.NotPublic | TypeAttributes.AutoLayout | TypeAttributes.Class | TypeAttributes.AnsiClass | TypeAttributes.Sealed;
mod.Types.Add(typeDef);
ICustomAttributeType attributeType = mod.Import(typeof(UnmanagedFunctionPointerAttribute).GetConstructor(new[] { typeof(CallingConvention) })) as ICustomAttributeType;
TypeRef customAttributeRef = mod.CorLibTypes.GetTypeRef(typeof(CallingConvention).Namespace, nameof(CallingConvention));
TypeSig customAttributeArgType = customAttributeRef.ToTypeSig();
CustomAttribute delegateCustomAttribute = new CustomAttribute(attributeType, new[]
{
    new CAArgument(customAttributeArgType, CallingConvention.ThisCall)
});
typeDef.CustomAttributes.Add(delegateCustomAttribute);
```

Using above code the following is rendered on the output:
```csharp
namespace dnlib_Test
{
	[UnmanagedFunctionPointer(CallingConvention.ThisCall)]
	internal delegate UserCreatedDelegate();
}
```

No idea how to set return type, add parameters... Some casting?

Is there a way to automatically create inner members (`.ctor`, `BeginInvoke`, etc.)?
Some helper extension to add a delegate based on the existing signature would be nice to have, for example:
```csharp
public static TypeDefUser CreateDelegateTypeDef<TDelegate>(this TypeDef @this) where TDelegate : System.Delegate
{
// ...
}

// And then to add a new delegate definition:
TypeDef typeDef = ModuleDef.GlobalType;
TypeDefUser delegateTypeDefUser = typeDef.CreateDelegateTypeDef<Func<string, bool>>();
delegateTypeDefUser.Name = "awesomeDelegate";
typeDef.Module.Types.Add(delegateTypeDefUser);
```

And have that output respectively:
```csharp
internal class <Module>
{
    [__DynamicallyInvokable]
    public delegate bool awesomeDelegate(string);
}
```

**Comment by 0xd4d** [comment]
Write a simple C# dll with that delegate and use eg. ILDASM to look at what the compiler created.

You'll see that your delegate is missing several required members, eg. Invoke, BeginInvoke etc.

For more info, you can read the ECMA 335 spec partition II, "14.6 Delegates"
