### ISSUE TITLE
Consider making the library less restrictive

### ISSUE THREAD

**Issue by twsI** [0xd4d/dnlib#230]
I just noticed, that migrating to v3 made the library more restrictive in terms of access to classes. A couple classes went from public to private, e.g. dnlib.DotNet.GenericArguments (de9bb51cefe07534f1219034c1f46ea3dc86bad4). I know that it is bad practice to make everything public, but many advanced options are hidden within those private classes.
I'd prefer not to always try to find a way around that with reflection, so how do you recommend I procede with that? Make pull requests for classes I would like to access? Fork it and try to keep my own version up to date? Or just continue with dirty reflection workarounds? Would love to hear from you.

**Comment by 0xd4d** [comment]
I don't plan on making that type public ever again. If you need to use it, you can just copy the source code to your project, it's not a lot of code.

**Comment by CreateAndInject** [comment]
But now, de4dot and dnSpy ref dnlib by nuget not source, so If we want to use these types, it's not easy.

**Comment by twsI** [comment]
Alright, fair enough.
