### ISSUE TITLE
dnlib shifts embedded resource offsets

### ISSUE THREAD

**Issue by RasheR666** [0xd4d/dnlib#231]
Hi, i'm using dnlib to make strong name sign for assemblies.
I started from dnlib 1.6.1. and embedded resource offsets was okey.
Now i tried to use version 3.1.0 and look at difference in IL code.
Diff shows me that now offsets are changed.
Then i tried only read and write assembly by dnlib without any changes and result the same.
I attaching IL code of original and modified files and code using for writing with dnlib.

Can you tell me, it's normal behavior of dnlib (to not preserve resources offsets)?
Creates it the broken assembly? Can i trust that modified assembly is not corrupted and resources will found correctly in runtime?
Is it important to have the same offsets in modified assembly like in original?

I think it's behavior changes because of this commit https://github.com/0xd4d/dnlib/commit/69de265922c888f636c482649d2940181583cbdc#diff-a8acd8e02a19236bcc08fdf30aa9ec19R415

At version 1.6.1DEFAULT_NETRESOURCES_ALIGNMENT has value 8
[Work.zip](https://github.com/0xd4d/dnlib/files/2717179/Work.zip)

**Comment by 0xd4d** [comment]
Some alignments were updated in some version between this version and an older version. Your DLL is OK.

**Comment by RasheR666** [comment]
Do you planning to make some configurable parameter for this offsets? Preserve Flags for writer for example?

**Comment by 0xd4d** [comment]
No, preserving tokens is useful, but adding an option to override resource alignment is something almost noone needs.

**Comment by RasheR666** [comment]
Okey. Thank you for so fast answers.
I think that i doesn't meet any problem with resources when test modified assemblies.
