### ISSUE TITLE
Fail to Compile

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#232]
What is the reason for this error?

![annotation](https://user-images.githubusercontent.com/706507/50576448-cfa69f80-0dc6-11e9-9cac-e7576ff71550.png)

**Comment by bprg** [comment]
I added the following code to _csproj_ solved problem.

```
  <PropertyGroup>
    <EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
  </PropertyGroup>
```

**Comment by 0xd4d** [comment]
You can just use the nuget package and you don't have to worry about that.

**Comment by 0xd4d** [comment]
The error looks related to sourcelink in the csproj file.

**Comment by bprg** [comment]
I need to change the source code, What is the final solution?

**Comment by 0xd4d** [comment]
Test removing SourceLink PackageReference from dnlib.csproj

**Comment by bprg** [comment]
Solved problem, Thanks.

**Comment by 0xd4d** [comment]
It also looks like you didn't use git to clone the repo, that's probably why SourceLink failed. Did you download the zip file with the source code?

**Comment by bprg** [comment]
> Did you download the zip file with the source code?
Yes I've download zip source code.
