### ISSUE TITLE
Push Nightly builds

### ISSUE THREAD

**Issue by twsI** [0xd4d/dnlib#233]
I'd like to suggest, that you push nightly builds to eigher nuget or maybe myget. Having the latest version available via nuget instead of a submodule would be more convenient for many projects.

**Comment by 0xd4d** [comment]
myget doesn't seem to be free, so that won't work, and I don't want to push every build to nuget.

**Comment by twsI** [comment]
My bad, didn't checked the pricing on myget..org Just saw quite a lot of open source projects using it and assumed, it would be free for FOSS. nuget.org does support pre-releases, so most people wouldn't even notice, but I understand, that you prefer not to pollute the main feed.

**Comment by UlyssesWu** [comment]
I think myget is free for public feeds since I'm still using it. The storage (500MB) and build time (10h per month) are limited though.

**Comment by Tianjiao** [comment]
myget no longer free for new users? Don't see free plan on their [pricing](https://myget.org/pricing) site.
@UlyssesWu myget doesn't charge you because you're the old user.
