### ISSUE TITLE
How to save a module and give up native code.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#236]
Some module with native code (ILOnly=false) is runnable, but Assembly.LoadfFrom failed with:
`. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)'
`

Maybe there's only a little native code, so is there any way to give up the native code, and save it as ILOnly, so Assembly.LoadFrom can work.

**Comment by CreateAndInject** [comment]
```
var module=ModuleDefMD.Load("test.exe");
module.Write("a.exe");
module.IsILOnly = true;
module.Write("b.exe");
```
test.exe and a.exe are runnable, when Assembly.LoadFrom it, occur the exception as above

b.exe is not runnable, when Assembly.LoadFrom it:
```
Could not load file or assembly ... or one of its dependencies. The module was expected to contain an assembly manifest.
```

There's no any confused code in test.exe, all code is:
```
    static class Program
    {
        static void Main(string[]args)
        {
            Console.WriteLine("OK");
            Console.ReadKey();
        }
    }
```

[test.zip](https://github.com/0xd4d/dnlib/files/2768573/test.zip)

**Comment by 0xd4d** [comment]
This usually means something related to native code is still set in some header, eg. some flag or vtable fixups. You should compare the PE and .NET headers in the saved file with a normal ILonly assembly created by eg. the C# compiler.

**Comment by CreateAndInject** [comment]
test.exe is about 800KB, after de4dot, it's still 800KB, but If clean it with some old de4dot(such as de4dot1.9), it's only 10KB
Does it mean old de4dot clean more complete?

How can I clean that redundant data use dnlib like old de4dot?

**Comment by 0xd4d** [comment]
Seems like you got it working.

Open a new issue about the size issue if it's still a problem. You can easily check what's in the 10KB exe and the 800KB exe with eg. dnSpy so you should know if it's needed or not.
