### ISSUE TITLE
How to remove a generic method if IsILOnly is false.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#237]
dnlib will preserve tokens if IsILOnly is false, that means even if I remove a generic method and all refs to it, dnlib will still write its MethodSpec, this will occur an error: A type was removed that is still referenced by this module.

Of course, I can disable PreserveMethodSpecRids, but I'm not sure whether it's safe? Becuase it won't preserve any MethodSpecs rather than only one MethodSpec.

**Comment by 0xd4d** [comment]
It's safe to disable it if you know the application doesn't have any hard coded method spec tokens in its code.

**Comment by CreateAndInject** [comment]
My tool is like de4dot, it will handle various applications, not a specific application.
For example, if I mod de4dot to support a new protector, but it's string obfuscator is a generic method, and is not ILOnly, so how can I do it? This time I can't disable PreserveMethodSpecRids, or else some of applistions may can not run.

**Comment by 0xd4d** [comment]
Is this still needed?

**Comment by CreateAndInject** [comment]
I forgot the example, maybe it's not important
