### ISSUE TITLE
Show more information.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#238]
The most frequent error of dnlib is:
Error calculating max stack value....

Now, dnSpy & de4dot ref dnlib by nuget, not source, everytime I must debug de4dot.exe in dnSpy and breaking in WriteMethodBodies to view the method name. It's so troublesome.

1. Can you restore dnlib source instead of nuget? Not everyone is so skilled as you, we must debug with dnlib source to resolve our problem.

2.Can you show method name when occurs: Error calculating max stack value....

**Comment by 0xd4d** [comment]
1: no

2: can do that.

**Comment by riQQ** [comment]
Shouldn't https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg solve 1?

**Comment by 0xd4d** [comment]
The nuget package already has sourcelink support so it should work today, yes. The pdb file is included with the nupkg. Next release will use snupkg files.

**Comment by MeikTranel** [comment]
Check @shanselman blog for both producing and consuming these symbols:

https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

@CreateAndInject, try enabling the Visual Studio options (the changes to the CSProj are only if you want to produce packages with sourcelink enabled)

**Comment by CreateAndInject** [comment]
@MeikTranel How?

**Comment by MeikTranel** [comment]
It is explained in the article i liked. I also made a Video showing how to do it with DNLib (Ignore the error frame... that wouldnt happen to you):

https://gfycat.com/marriedimpressionablecaecilian

**Comment by CreateAndInject** [comment]
@MeikTranel Thanks

**Comment by CreateAndInject** [comment]
Any news about `Can you show method name when occurs: Error calculating max stack value....` ?

By the way:
1. Please update sourcelink, or else dnlib can't build:
https://github.com/dotnet/sourcelink/issues/337#issue-466979138
https://github.com/aspnet/EntityFrameworkCore/issues/16656#issue-469885486
https://github.com/dotnet/sourcelink/issues/350#issue-470675436

2. I notice you make a large changes in dnlib & dnSpy about `Pattern Matching(use is null instead of ==)` & `Nullable reference type`, etc.
Please don't do it in de4dot, or else there will be large conflicts when modded version pull it.

**Comment by 0xd4d** [comment]
Don't hijack old issues with new issues. Create new issues instead.

**Comment by CreateAndInject** [comment]
> The nuget package already has sourcelink support so it should work today, yes. The pdb file is included with the nupkg. Next release will use snupkg files.

Do you use snupkg now in 3.3.1? How to debug into dnlib source?

**Comment by 0xd4d** [comment]
Open a VS issue about that.

**Comment by 0xd4d** [comment]
Or read the link above posted by @MeikTranel

**Comment by CreateAndInject** [comment]
> Or read the link above posted by @MeikTranel

I tested. It works in dnlib 3.1, but when I use F11, I can't go to source in dnlib 3.2/3.3/3.31

**Comment by MeikTranel** [comment]
@CreateAndInject you need to enable the NuGet Symbol Server. snupkg relies on symbol server based symbol delivery wherein before we stored the pdb directly in nuget package.

![image](https://user-images.githubusercontent.com/6466560/71549128-96444800-29b8-11ea-9a82-f04b60b49886.png)
If you put your tick on the symbol server it'll just like before.

**Comment by MeikTranel** [comment]
btw. enable microsoft symbol server if you want to step through stuff like console.writeline ;)

**Comment by CreateAndInject** [comment]
@MeikTranel I can't find any different when enable this option.
I tested so many times, dnlib 3.1 can, but 3.2/3/3/3.3.1 can't display this dialog:

![image](https://user-images.githubusercontent.com/2529999/71549251-86972480-29f5-11ea-96f4-b8d07cc55e66.png)

**Comment by 0xd4d** [comment]
@CreateAndInject Like I said above, contact MS if you can't get it working. All your recent posts here have been off topic.
