### ISSUE TITLE
Question: How to inject a class with dnlib (excluding InjectHelper from ConfuserEx)

### ISSUE THREAD

**Issue by Hulkstance** [0xd4d/dnlib#239]
The title is pretty self explanatory. I want to inject a class with one method inside it. I don't want to use ConfuserEx's way because I will have to edit dnlib.

**Comment by 0xd4d** [comment]
There's no such method built in so you have to write it yourself. You have to clone the types, and replace TypeDef/member def refs to the old location with TypeRef/member refs.

If you know that the type you want to move is only referencing type/member defs that are also moved, then you can just remove the type from the original module (module.Types) and add it to the new module.
