### ISSUE TITLE
Removing entries from MethodBodyChunks

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#240]
Hello,

I am currently trying to move the dnlib special Implementation for ConfuserEx that was done by @yck1509 closer to the original implementation. Thanks to the new mapper in the `Importer` I am pretty close.

What remains is the way how entries are removed from the `MethodBodyChunks` during the write process and moved to the method chunk of an additional `PESection`. To do this @yck1509 added the `Remove` method to the `MethodBodyChunks` class as you find [here][1].

The method works fine like this. So the question is why it's not present in the original version of dnlib. Are there any problems I fail to see with removing the method bodies again from the chunk?

I tried to work around this by removing the method bodies before they are written and placing them back in once the work is done. How ever that has all sorts of negative effects on the remaining parts of the writer that try to query the original `MethodBodyChunks` (that doesn't know anything about the method bodies) for the references to the bodies.

[1]: https://github.com/mkaring/dnlib/blob/master/src/DotNet/Writer/MethodBodyChunks.cs#L109

**Comment by 0xd4d** [comment]
I guess I never thought anyone would need it. You can send a PR to add it.

It should also throw unsupported exception if CanReuseOldBodyLocation is true (it's only true when writing native images and optimizing the exe size by reusing old md/body locations)
