### ISSUE TITLE
TypeLoadException after sorting types

### ISSUE THREAD

**Issue by gihojitoy** [0xd4d/dnlib#243]
Hello, please tell me why I get a TypeLoadException after starting the application in which the type list was sorted. Tell me how it is better to implement this sorting without damaging the application and whether it is possible. thx

```
var options = new ModuleCreationOptions();
options.TryToLoadPdbFromDisk = false;
 var module = ModuleDefMD.Load(File.ReadAllBytes(@"application.exe"), options);
 var typeArray = module.Types.ToArray();
random.Shuffle(typeArray);
foreach (var type in typeArray)
{
  if (module.Types.Remove(type))
  {
    module.Types.Add(type);
  }
 }
module.Write(@"application.exe");
```

**Comment by 0xd4d** [comment]
The ECMA spec says a nested type must be after its enclosing type, so you need to update your randomizer.

```
A
  B
     C
  D
```

Valid sort orders are: `A B C D`, `A B D C`, `A D B C`

Although dnlib could do this for you, dnlib should also be able to produce assemblies that don't follow the ECMA spec.

**Comment by 0xd4d** [comment]
I misread your code, you only sort non-nested types. You can use peverify to see what errors it spits out. My guess is that you moved the global `<Module>` type (it must be the first type).
