### ISSUE TITLE
DynamicMethodBodyReader: Add constructor with Importer

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#249]
Hello,

would you accept a PR adding a new constructor overload to the `DynamicMethodBodyReader` that allows setting the `Importer` instance from the outside? I got a use case were I need to map some of the types inside a `DynamicMethod` to some other types. That would work very well if I could set the `ImportMapper` of the `Importer`.

Best regards,
Martin

**Comment by 0xd4d** [comment]
Yes, that could be useful!

**Comment by mkaring** [comment]
Very good. I'll implement and test it to see if it works as I expect it to. Once I am done I send the changes your way.
