### ISSUE TITLE
Is it possible to write to a string?

### ISSUE THREAD

**Issue by ChrisDevinePimss** [0xd4d/dnlib#252]
Currently i am having to write to a file, then read the file back into a string. I was wondering if there was a way to write straight to a string. My example code of what i currently have to do is below.

`
 private static void ReplaceDllString()
    {
      byte[] data = File.ReadAllBytes("DllWithStringToEdit.dll");

      ModuleDefMD module = ModuleDefMD.Load(data);

      foreach (TypeDef t in module.Types)
      {
        foreach (MethodDef m in t.Methods)
        {
          if (!m.HasBody) continue;
          foreach (var instr in m.Body.Instructions)
          {
            if (instr.OpCode == OpCodes.Ldstr && (string)instr.Operand == "%FISH%")
            {
              instr.Operand = "Fishandchips";
              //module.Write(@"I:\DllWithStringToEdit.dll");
              //return;
            }
          }
        }
      }
      string stubSource;
      module.Write(@"I:\DllWithStringToEdit.dll");
      stubSource = File.ReadAllText(@"I:\DllWithStringToEdit.dll");
      // pass stub source to codedom (be better if i didnt have to write the dll and could just write to a string instead)
    }
`

**Comment by 0xd4d** [comment]
Write to a Stream instead of a file. Then use eg. base64 encoding to turn that binary data to a string.
