### ISSUE TITLE
One more problem about PrivateScope.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#253]
1. What happens  with PrivateScope?
2. Why does TypeDef.FindMethod check PrivateScope even if the name and sig matches?

**Comment by 0xd4d** [comment]
Describe the problem and show how I can repro it.

**Comment by CreateAndInject** [comment]
```
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(My<int>.Get());
        Console.ReadKey();
    }
}
class My<T>
{
    public static string Get()
    {
        return Environment.CurrentDirectory;
    }
}
```
Build it, and modify 'Get' method as PriviateScope, make sure there're only `call memberref` and `ret` 2 instructions. Compiler may generate as: `call memberref` `stloc` `br` `ldloc` `ret`, please delete other instructions except these 2.

This is my test, it's runnable:
[test.zip](https://github.com/0xd4d/dnlib/files/2883777/test.zip)

de4dot test.exe -p dr4 (use dr4 to enable remove inline method)

de4dot will think `Get` is an inline method and remove it. But because it's private scope, dnlib can't find MethodDef in `My<int>.Get()`
de4dot will remove 'Get` definition but keep call `Get`, so the output can't run.

As I say, if dnlib doesn't check private scope, or DotNetUtils.GetMethod use the arg:SigComparerOptions.PrivateScopeMethodIsComparable can resolve it.

**Comment by 0xd4d** [comment]
So you're saying this is a de4dot bug?

**Comment by CreateAndInject** [comment]
I'm not sure, but why does TypeDef.FindMethod check PrivateScope? What's special thing with it?

**Comment by 0xd4d** [comment]
FindMethod has been updated to check if sourceModule == type.Module if it is PrivateScope.
