### ISSUE TITLE
Maliciously crafted array type signature can trigger DoS via memory exhaustion

### ISSUE THREAD

**Issue by gonzalezjo** [0xd4d/dnlib#255]
Or at least, that *seems* to be the issue. I've already reset the VM that I did the analysis on, so I don't have much left besides what I remember and what I've noted. This issue is present in both dnlib *and* in Cecil.

I made a [*very* brief write-up on this](https://jordig.me/posts/beating-dotnet-anti-analysis/) and would be more than happy to email the pathological assembly to a developer to debug. 

I apologize for not being able to provide more information right now. I'm not the most familiar with the .NET ecosystem so I'm learning as I go.

**Comment by cawk** [comment]
Hi,
nice writeup i was looking at this and wondering if you could share the file with me so i can have a look at it myself as something i found quite interesting,
i did try email you from the email on your site but i got a failed email as it is misconfigured

if you could share it with me that would be great my email is cawkre@gmail.com

Regards

**Comment by 0xd4d** [comment]
You can attach the file here or email me, see https://github.com/0xd4d/dnlib/blob/master/LICENSE.txt

**Comment by gonzalezjo** [comment]
> Hi,
> nice writeup i was looking at this and wondering if you could share the file with me so i can have a look at it myself as something i found quite interesting,
> i did try email you from the email on your site but i got a failed email as it is misconfigured
> 
> if you could share it with me that would be great my email is [cawkre@gmail.com](mailto:cawkre@gmail.com)
> 
> Regards

Fixed. Will email you and @0xd4d now. I'm concerned about sharing obfuscated binaries on GitHub and potentially being flagged for it, especially if it contains copyrighted (I'm not sure?) content. Not sure how GitHub's rules work in that regard.

**Comment by kronikc** [comment]
> > Hi,
> > nice writeup i was looking at this and wondering if you could share the file with me so i can have a look at it myself as something i found quite interesting,
> > i did try email you from the email on your site but i got a failed email as it is misconfigured
> > if you could share it with me that would be great my email is [cawkre@gmail.com](mailto:cawkre@gmail.com)
> > Regards
> 
> Fixed. Thanks for catching that. Will email you and @0xd4d now. I'm concerned about sharing obfuscated binaries on GitHub and potentially being flagged for it, especially if it contains copyrighted (I'm not sure?) content. Not sure how GitHub's rules work in that regard.
> 
> Edit: Emails sent.

Tried emailing you through ur blog email and it's not setup

**Comment by gonzalezjo** [comment]
> > > Hi,
> > > nice writeup i was looking at this and wondering if you could share the file with me so i can have a look at it myself as something i found quite interesting,
> > > i did try email you from the email on your site but i got a failed email as it is misconfigured
> > > if you could share it with me that would be great my email is [cawkre@gmail.com](mailto:cawkre@gmail.com)
> > > Regards
> > 
> > 
> > Fixed. Thanks for catching that. Will email you and @0xd4d now. I'm concerned about sharing obfuscated binaries on GitHub and potentially being flagged for it, especially if it contains copyrighted (I'm not sure?) content. Not sure how GitHub's rules work in that regard.
> > Edit: Emails sent.
> 
> Tried emailing you through ur blog email and it's not setup

The issue is on your end, then.

**Comment by kronikc** [comment]
The response from the remote server was:
550 5.7.1 <public@jordig.me>: Relay access denied

**Comment by 0xd4d** [comment]
The commit is right here, it shows exactly what changed. It's an array sig with an array rank set to max value.
