### ISSUE TITLE
Please upload the wiki.

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#256]
Please upload the wiki.

**Comment by Ambraham1544** [comment]
I don't know how to use it exactly

**Comment by 0xd4d** [comment]
There's no wiki, see the README instead.

**Comment by 0xd4d** [comment]
And the examples

**Comment by Ambraham1544** [comment]
It does not explain you how to read and modify and add resources.

**Comment by 0xd4d** [comment]
`module.Resources` has the raw .NET resources. If it's a resx (multi) resource, you can use ResourceReader (part of .NET Framework) to get all reosurces.

```new ResourceReader(embeddedResource.CreateReader().AsStream())```

where `embeddedResource` is an `EmbeddedResource` in `module.Resources`.

Note that that ResourceReader deserializes the resources which can load arbitrary dlls, do only do it with trusted assemblies.

dnlib has `dnlib.DotNet.Resources.ResourceReader` and `dnlib.DotNet.Resources.ResourceWriter` too. They don't deserialize/serialize the data, so any unsupported serialized data is returned as raw bytes.

**Comment by Ambraham1544** [comment]
Is it right? add
        Dim FS As String = "TEST.exe"
        Dim md As ModuleDefMD = ModuleDefMD.Load(File.ReadAllBytes(FS))
        Dim res As EmbeddedResource = New EmbeddedResource(New UTF8String("RESNAME"), IO.File.ReadAllBytes(FS), ManifestResourceAttributes.Public)
        md.Resources.Clear()
        md.Resources.Add(res)
        md.Write("Out.exe")

        Me.Close()

how to create multiple resource i don't know really

**Comment by 0xd4d** [comment]
Looks like it will work. Did you try it?

For multiple resources, see see the ResourceWriter class I mentioned above or use .NET Framework's ResXResourceWriter class.

**Comment by Ambraham1544** [comment]
Yes it works. 
I actually added it, but I do not know how to read it.
I'd like to know how to read from the TEST.exe file itself.
And
How to add a string to a resource?
I can't understand about multi resource still does :(

**Comment by 0xd4d** [comment]
As I've explained already, the ResourceWriter classes mentioned above should be used to generate the data. If you use the .NET Framework class, use the Stream constructor so you write to a MemoryStream and not to a file.

https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcewriter

**Comment by Ambraham1544** [comment]
Thank you. understood
thx for help

**Comment by Ambraham1544** [comment]
System.Resources.MissingManifestResourceException 
how to fix it ?
            Dim ASS As Assembly = Assembly.GetExecutingAssembly()
            Dim RM As New ResourceManager("RESNAME", ASS)
            MsgBox(RM.GetObject("MARCHS"))

**Comment by Ambraham1544** [comment]
Read : 
        Dim rm As ResourceManager
        rm = New ResourceManager("RESNAME", Assembly.GetExecutingAssembly())
        rm.GetString("MARCHS")

error : System.Resources.MissingManifestResourceException
Is't this?
I'm sorry that I have many questions.

**Comment by 0xd4d** [comment]
That's not a class in dnlib, so better ask here: https://github.com/dotnet/corefx/

**Comment by Ambraham1544** [comment]
Does that code work normally?

**Comment by Ambraham1544** [comment]
write: 
        Dim writer As ResourceWriter = New ResourceWriter("myResources.resources")


        writer.AddResource("GG", "First String")
        writer.Close()

        Dim FS As String = "TEST.exe"

        Dim md As ModuleDefMD = ModuleDefMD.Load(File.ReadAllBytes(FS))
        Dim res As EmbeddedResource = New EmbeddedResource(New UTF8String("GG.resources"), File.ReadAllBytes("myResources.resources"))

        'md.Resources.Clear()
        md.Resources.Add(res)
        md.Write("Out.exe")

        Me.Close()
read : 
            Dim rdm As ResourceManager
            rdm = New ResourceManager("GG.resources", Assembly.GetExecutingAssembly())

            MsgBox(rdm.GetString("GG"))
error..

**Comment by Ambraham1544** [comment]
I'm idiot thjx 0xd4d
