### ISSUE TITLE
Problem about ImportMapper

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#259]
Does commit `Customize importing of System.Type's` (#245) resolve my issue `ModuleDef.Import vesion` #109?

If that, could you update dnlib nuget to the lastest to support `TypeRef ImportMapper.Map(Type source)`?
And update dnSpy & de4dot to ref lastest dnlib.

**Comment by 0xd4d** [comment]
You can test the latest code yourself and see if it works for you

**Comment by CreateAndInject** [comment]
Yes, it works fine, could update dnlib nuget to the lastest?

**Comment by 0xd4d** [comment]
When it's ready I'll do that.
