### ISSUE TITLE
dnlib System.NullReferenceException

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#260]
System.NullReferenceException

CODE ;  
 Dim asm As ModuleDefMD = ModuleDefMD.Load("Blur.exe") 
                For Each tdf As TypeDef In asm.GetTypes() 
                    For Each mdf As MethodDef In tdf.Methods
                        For Each instruction As Instruction In mdf.Body.Instructions
                            If instruction.Operand.ToString() = "[@]" Then
                                instruction.Operand = ramdomresourcename
                            End If
                        Next
                    Next
                Next
                asm.Write("Output")

**Comment by 0xd4d** [comment]
Show the stack trace or some more info because that code shouldn't throw a NRE

**Comment by CreateAndInject** [comment]
@0xd4d Why do you say so?
There're at least 2 problems may occur NRE
1. He doesn't check whether a method has body, so mdf.Body.Instructions may occur NRE.
2. He doesn't check whether an instruction is ldstr, so instruction.Operand.ToString() may occur NRE.

**Comment by Ambraham1544** [comment]
> @0xd4d Why do you say so?
> There're at least 2 problems may occur NRE
> 
> 1. He doesn't check whether a method has body, so mdf.Body.Instructions may occur NRE.
> 2. He doesn't check whether an instruction is ldstr, so instruction.Operand.ToString() may occur NRE.

**Comment by Ambraham1544** [comment]
@CreateAndInject  i'd like to fix..

**Comment by 0xd4d** [comment]
@CreateAndInject I quickly read the unformatted VB code, I thought he meant it was a NRE in dnlib.

@Ambraham1544 Fix your code to check for null. The operand can be null, a string, a target instruction, or a boxed primitive value, etc.

**Comment by Ambraham1544** [comment]
@0xd4d Any example??..

**Comment by Ambraham1544** [comment]
@0xd4d And what is NRE?

**Comment by 0xd4d** [comment]
NRE is NullReferenceException.

You check if the operand is a string and if it is you cast it to a string which you can then compare to your magic string value. How you do this depends on the language, so google a VB tutorial.

**Comment by Ambraham1544** [comment]
@0xd4d  
code :
                Dim asm As ModuleDefMD = ModuleDefMD.Load("Blur.exe")
                For Each tdf As TypeDef In asm.GetTypes()
                    For Each mdf As MethodDef In tdf.Methods
                        For Each instruction As Instruction In mdf.Body.Instructions
                            Dim strings As String = instruction.Operand.ToString
                            If strings = "[@]" Then instruction.Operand = "CHANGGED"

                        Next
                    Next
                Next
