### ISSUE TITLE
How to change assembly name & root namespace with dnlib?

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#263]
How to change assembly name & root namespace with dnlib?

**Comment by 0xd4d** [comment]
Every type has a Namespace property that you can update. module.Types returns all non-nested types.

**Comment by Ambraham1544** [comment]
![githubaa](https://user-images.githubusercontent.com/48386042/55271639-6fef6000-52f3-11e9-942b-5f8b2cf6208b.PNG)
Could you give me an example?
Also, is it impossible to change the framework version if possible?

**Comment by 0xd4d** [comment]
An example isn't needed, just write the new namespace to the `Namespace` property.

Changing the framework is possible but is too much work. You have to update all assembly references.

**Comment by Ambraham1544** [comment]
Does it mean root namespace?
And how do I change the assembly name?

**Comment by 0xd4d** [comment]
`module.Assembly.Name`

**Comment by Ambraham1544** [comment]
@0xd4d Thanks! 
how to change framework version??

this ?
Creating mscorlib type references
Every module has a CorLibTypes property. It has references to a few of the simplest types such as all integer types, floating point types, Object, String, etc. If you need a type that's not there, you must create it yourself, eg.:

    TypeRef consoleRef = new TypeRefUser(mod, "System", "Console", mod.CorLibTypes.AssemblyRef);

**Comment by Ambraham1544** [comment]
module.RuntimeVersion
