### ISSUE TITLE
Is there a way to get the SequencePoint of an Async method instruction?

### ISSUE THREAD

**Issue by tonyredondo** [0xd4d/dnlib#264]
I can get the SequencePoint of the instructions of a method unless the method is marked as Async.  I know the compiler changes the original code by a state machine, but my question is if there is a way to get the actual SequencePoint for this instructions? Maybe is a dumb question but, the info should be in the PDB isn't? when an exception is thrown from an async method I have this file and line info on the stack trace, so I guess it should be somewhere.

Thanks.

**Comment by 0xd4d** [comment]
The exception should be thrown in the `MoveNext` method. Find that method (you should have the type + method name == `MoveNext` or the method token so use `module.Find()` or `module.ResolveToken()`), and `MethodDef.Body` has the method body. Find the correct Instruction (you should know the IL offset), and check its `SequencePoint` field.

Related: https://github.com/0xd4d/dnlib/issues/248

**Comment by 0xd4d** [comment]
Most of the time, the compiler adds this attribute to the kickoff method (original async method) `System.Runtime.CompilerServices.AsyncStateMachineAttribute`

You can find the async state machine by getting the type from that attribute and then finding the MoveNext method.

**Comment by tonyredondo** [comment]
@0xd4d Thanks for the guidance, it's working perfectly, now I'm extracting the SequencePoint from async methods too.
