### ISSUE TITLE
mono.cecil ModuleDef.Mainmodule to dnlib ModuleDef?

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#265]
mono.cecil
Dim asm As AssemblyDefinition = AssemblyDefinition.ReadAssembly(Path)

Dim MainModule As ModuleDefinition  = asm.MainModule

dnlib
Dim asm As AssemblyDef = AssemblyDef.Load(Path)
        Dim MainModule As ModuleDef = ??
what is it

**Comment by bprg** [comment]
```
AssemblyDef assembly = AssemblyDef.Load("file");
ModuleDef module = assembly.Modules[0];
```

**Comment by Ambraham1544** [comment]
I just decided to use mono.cecil.

**Comment by Ambraham1544** [comment]
NRE Help?
Private Sub Obfuscate(ByVal Path As String)
        Dim asm As AssemblyDef = AssemblyDef.Load(Path)
        Dim MainModule As ModuleDef = asm.ManifestModule

        For Each t As TypeDef In MainModule.Types
            t.Name = RandomString(30, False)

            For Each p As PropertyDef In t.Properties
                p.Name = RandomString(30, False)
            Next

            For Each f As FieldDef In t.Fields
                f.Name = RandomString(30, False)
            Next

            For Each ed As EventDef In t.Events
                ed.Name = RandomString(30, False)
            Next

            If Not t.[Namespace].Contains(".My") Then

                For Each m As MethodDef In t.Methods

                    If m.IsConstructor = False Then

                        If m.IsPinvokeImpl = False Then
                            m.Name = " "
                        End If
                    End If

                    For Each param As Parameter In m.Parameters
                        param.Name = RandomString(30, False)
                    Next
                Next

                t.[Namespace] = RandomString(30, False)
            End If
        Next

        asm.Write(Path)
    End Sub

**Comment by 0xd4d** [comment]
Debug it and you'll know which line throws.

**Comment by Ambraham1544** [comment]
Here
  For Each t As TypeDef In MainModule.Types
        t.Name = RandomString(30, False)

        For Each p As PropertyDef In t.Properties
            p.Name = RandomString(30, False)
        Next

        For Each f As FieldDef In t.Fields
            f.Name = RandomString(30, False)
        Next

        For Each ed As EventDef In t.Events
            ed.Name = RandomString(30, False)
        Next

        If Not t.[Namespace].Contains(".My") Then

            For Each m As MethodDef In t.Methods

                If m.IsConstructor = False Then

                    If m.IsPinvokeImpl = False Then
                        m.Name = " "
                    End If
                End If

                For Each param As Parameter In m.Parameters
                    param.Name = RandomString(30, False)
                Next
            Next

            t.[Namespace] = RandomString(30, False)
        End If
    Next


{For Each t As TypeDef In MainModule.Types next}
