### ISSUE TITLE
There're some problems if the module doesn't contain any type except global type.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#266]
```
        static void Main(string[] args)
        {
            var module = new ModuleDefUser();
            new AssemblyDefUser("a").Modules.Add(module);
            //module.Types.Add(new TypeDefUser("x", module.CorLibTypes.Object.TypeDefOrRef));
            string file = "a.dll";
            module.Write(file);
            var asm = Assembly.LoadFrom(file); //BadImageFormatException
            Console.WriteLine(asm);
            Console.ReadKey();
        }
```

This code will occur a BadImageFormatException, but it's runnable if I uncomment the third line.

**Comment by 0xd4d** [comment]
Could you explain why you think this is a dnlib issue and not a coreclr issue?

**Comment by CreateAndInject** [comment]
Create a Class Liabray, delete Class1.cs, build it. The output doesn't contain any type exept global type, but Assebmly.LoadFrom works.

**Comment by 0xd4d** [comment]
You need a module name, you don't add any name to the ctor.

**Comment by CreateAndInject** [comment]
Thanks, it works!
I know why did I fail ago:
ctor() doesn't create a guid, and ctor(string) will create a guid

So, this code works:
```
var module = new ModuleDefUser("a");
```

This code doesn't work:
```
var module = new ModuleDefUser();
module.Name = "a";
```

**Comment by 0xd4d** [comment]
You can pass in a Guid to the ctor too. A null mvid is possible, even if the runtime perhaps won't like it.

**Comment by CreateAndInject** [comment]
Thanks!
