### ISSUE TITLE
Size issue about #236.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#267]
3 months ago, I opened an issue : How to save a module and give up native code. #236

I'm sorry, I don't resolve the size issue.
This is my target:
[files.zip](https://github.com/0xd4d/dnlib/files/3089434/files.zip)

All code is:
```
    static class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("OK");
            Console.ReadKey();
        }
    }
```

These 2 files are both about 800KB
 SizeTest1.exe is runnable, but Assembly.LoadfFrom failed with:
. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)'

SizeTest2.exe can't run.

de4dot1.9 can clean both 2, and the output file is only 5KB, and runnable, and Assembly.LoadFrom can work. But the lastest de4dot can't.

It seems de4dot1.9 can fix header error, but the lastest can't.

Could you help me find out what's problem with these 2 files?

**Comment by 0xd4d** [comment]
My guess is that's some flag or field in the cor20 headers are set that need to be cleared. Dnlib doesn't try to guess what values you want, so if you need to clear some field / etc you should do that before saving it.

**Comment by CreateAndInject** [comment]
Is there any way to generate a runnable exe from .text section. It means give up PE header and rebuild it from .text section.

**Comment by CreateAndInject** [comment]
> Set ILOnly = true and call module.Write() instead of NativeWrite() should do it. If it has a module cctor that calls native code, you have to patch it.

Do you mean I can determine whether a module contains native code from GlobalType.cctor？

ILOnly flag isn't exact, because I can clean it even if the module doesn't contain any native code in fact.

So, I want to know whether there's a way to determin a module whether contains native code.

**Comment by 0xd4d** [comment]
> 
> 
> Is there any way to generate a runnable exe from .text section. It means give up PE header and rebuild it from .text section.

Doesn't seem to be related to dnlib.

> > Set ILOnly = true and call module.Write() instead of NativeWrite() should do it. If it has a module cctor that calls native code, you have to patch it.
> 
> Do you mean I can determine whether a module contains native code from GlobalType.cctor？
> 
> ILOnly flag isn't exact, because I can clean it even if the module doesn't contain any native code in fact.
> 
> So, I want to know whether there's a way to determine whether a module contains native code.

Check all methods to see if it has a native method body.
