### ISSUE TITLE
Change TypeDef.FullName

### ISSUE THREAD

**Issue by binarysnake** [0xd4d/dnlib#268]
I'm trying to change the FullName of a type.
Is this possible?; If so, how?
Example: 
`            foreach(TypeDef type in module.Types)
            {
                type.FullName = randomString();
            }`

**Comment by binarysnake** [comment]
Sorry for the confusion;
The FullName of a type can be changed, but not directly
FullName of a type is: `namespace name`.`class name`

**Comment by 0xd4d** [comment]
Each type has a `Name` and `Namespace` property that you can initialize.
