### ISSUE TITLE
Validate strong name signature

### ISSUE THREAD

**Issue by RasheR666** [0xd4d/dnlib#269]
Hello, can you help me?
I signed assembly using strong name key. (using this method InitializeStrongNameSigning)
After this i want to verify signature. But i can't understand how i can make this using dnlib.
I can check that assembly has public key and each reference has public key token.
But it not enought, I must check the hash of the assembly, but i don't know how.
Can you help me and tell, how i can do this?

**Comment by 0xd4d** [comment]
There's no such API at the moment. Use `sn.exe` or native APIs (.NET Framework probably needed): https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/strong-naming/
