### ISSUE TITLE
Decrypted USStream

### ISSUE THREAD

**Issue by cawk** [0xd4d/dnlib#274]
Hello, i am currently working on a file that has an encrypted USStream 
i have now decrypted this and want to replace it with the decrypted byte[]
is this possible?
will i have to save the file to do it as i want to replace the stream then continue with deobfuscation as it reads data from here
Kind Regards

**Comment by cawk** [comment]
I solved this by getting the fileoffset to the stream and writing the byte[] back into the byte[] of the file
then reloaded the file

would be interested if theres a better way of doing this within dnlib

**Comment by 0xd4d** [comment]
The solution you used is probably the one I'd use too (updating the byte[] with the new data).

**Comment by 0xd4d** [comment]
Actually, it's the #US stream (and not any of the other streams), so you could just do what de4dot does and add a string decrypter. Have a look at its code.
