### ISSUE TITLE
CallingConventionSig is null

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#276]
If I use "MetadataFlags.PreserveAll" and some methods were removed, dnlib will throw "CallingConventionSig is null". Is there any other way except ignoring it?

![Snipaste_2019-06-01_00-13-19](https://user-images.githubusercontent.com/27536652/58719395-1940f800-8402-11e9-9d62-4d7dee3b7e52.png)
![Snipaste_2019-06-01_00-17-09](https://user-images.githubusercontent.com/27536652/58719575-9f5d3e80-8402-11e9-88fb-7f2cd77ea7b2.png)

**Comment by 0xd4d** [comment]
Have you tried writing a valid (non-null) signature?

**Comment by wwh1004** [comment]
The reason does not seem to be that some methods were removed. Writing a non-null signature will not cause an error. The original assembly contains invalid signature (non-null but it is encrypted). So when I use "MetadataFlags.PreserveAll" to save the module, dnlib will throw error. I know how to fix it. Thanks for your reminding.
