### ISSUE TITLE
Copy type to another module - System.InvalidOperationException

### ISSUE THREAD

**Issue by cobbr** [0xd4d/dnlib#277]
Hi @0xd4d, thanks a bunch for the dnlib project!

I am hoping to write a dotnet "injector" that copies a dotnet assembly into a pre-existing dotnet assembly.

To do so, I thought I would copy all the types from the first assembly into the second, however I get an error that the type is already owned by another module. Here's my current implementation:

```
static void Main(string[] args)
{
    if (args.Length != 3)
    {
        Console.Error.WriteLine("Usage: </path/to/tobeinjected.exe> </path/to/injectee.exe> </path/to/output.exe>");
        return;
    }

    var tobeinjectedMod = ModuleDefMD.Load(args[0]);
    var injecteeMod = ModuleDefMD.Load(args[1]);
    foreach (var type in injecteeMod.GetTypes())
    {
        if (type.FullName != "<Module>")
        {
            injecteeMod.Types.Add(type);
        }
    }
}
```

And the error I'm receiving:
```
Unhandled Exception: System.InvalidOperationException: Type is already owned by another module. Remove it from that module's type list.
   at dnlib.DotNet.ModuleDef.dnlib.Utils.IListListener<dnlib.DotNet.TypeDef>.OnAdd(Int32 index, TypeDef value)
   at dnlib.Utils.LazyList`1.Add_NoLock(TValue item)
   at dnlib.Utils.LazyList`1.Add(TValue item)
```

Let me know if there is a better way to do this, or if there is a way I could avoid this error. Thanks in advance!

**Comment by 0xd4d** [comment]
You have to remove the type from the original module before you add it to the new module. Something like this:

```C#
    foreach (var type in sourceModule.Types.ToArray())
    {
        if (!type.IsGlobalModuleType)
        {
            sourceModule.Types.Remove(type);
            destModule.Types.Add(type);
        }
    }
```

Note that I used `Types` and not `GetTypes()` since `GetTypes()` also returns nested types.

**Comment by cobbr** [comment]
Thanks for the info @0xd4d, I'll give this a shot. Does copying over a Type like this create a "deep copy" (i.e. including all the nested types)?

**Comment by 0xd4d** [comment]
It's a move, not a copy. Deep copy requires a lot more code.

**Comment by cobbr** [comment]
@0xd4d  No problem, I figured that was the case.

Do you have any plans to implement a deep-copy method or is this something you would consider?

**Comment by 0xd4d** [comment]
No there are no such plans.
