### ISSUE TITLE
Branching Examples

### ISSUE THREAD

**Issue by cobbr** [0xd4d/dnlib#278]
Hi @0xd4d , I was struggling to programmatically create an assembly that includes branching.

Are there any examples of dnlib being used to create branching instructions? (i.e. using OpCodes.Bgt_S, OpCodes.Br_S, etc.)

If not, would it be possible to add an example that uses these instructions?

Thanks in advance!

**Comment by 0xd4d** [comment]
`var newBranch = Instruction.Create(targetInstruction)` creates the instruction. The operand is the target instruction.
