### ISSUE TITLE
Get compile timestamp?

### ISSUE THREAD

**Issue by Bluscream** [0xd4d/dnlib#279]
https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/ModuleWriterBase.cs#L399

Is it this?

![image](https://user-images.githubusercontent.com/3318223/59810375-3e3fd100-9305-11e9-95b7-0c71fa088c7d.png)

**Comment by 0xd4d** [comment]
Yes the compiler should normally write the timestamp there. If bit 31 is set, it's not a timestamp though.
