### ISSUE TITLE
Run some method from loaded assembly

### ISSUE THREAD

**Issue by Bluscream** [0xd4d/dnlib#280]
I want to run `VRCApplicationSetup.GetBuildStoreID()` which looks like this
```csharp
	public static string GetBuildStoreID()
	{
		return "Steam";
	}
```

I found https://stackoverflow.com/a/38538451/5494061 but it's not for dnlib

**Comment by 0xd4d** [comment]
dnlib doesn't load the assembly for execution. You have to save it to disk and load it using Assembly.Load() etc or save it to a byte[] and call Assembly.Load().
