### ISSUE TITLE
Couldn't resolve the correct module

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#284]
src/DotNet/Importer.cs, line 609:
`var mod = asm.FindModule(origDeclType.Module.Name) as ModuleDefMD;`

Seems there's a bug, for example:
When the assembly is mscorlib, ModuleDef.Name is `CommonLanguageRuntimeLibrary`, but System.Reflection.Module.Name is `mscorlib.dll`, so asm.FindModule failed.

**Comment by 0xd4d** [comment]
Should be fixed in master.
