### ISSUE TITLE
Import(Type) will lose the namespace of a NestedType.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#285]
Generally speaking, NestedType doesn't have its own namespace, but it still work if it has.
If there's a NestedType `xxx.C1+yyy.C2`, after Import(Type), dnlib will create a TypeRef `xxx.C1+C2`, so it can't resolve and call. TypeLoadException will occur when running.

```
TypeRef CreateTypeRef2(Type type) {
	if (!type.IsNested)
		return module.UpdateRowId(new TypeRefUser(module, type.Namespace ?? string.Empty, type.Name ?? string.Empty, CreateScopeReference(type)));
	return module.UpdateRowId(new TypeRefUser(module, string.Empty, type.Name ?? string.Empty, CreateTypeRef2(type.DeclaringType)));
}
```

**Comment by 0xd4d** [comment]
Should be fixed in master.
