### ISSUE TITLE
NestedType.Namespace is the DeclaringType.Namespace

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#286]
Commit a86fca3f83c67f55f71fc1bc8ccda57f68897ffa can't fix #285
System.Reflection.Type.Namespace will always return DeclaringType.Namespace if it's NestedType, so Type.Namespce are both `xxx` in these 2 types:
`xxx.C1+C2`
`xxx.C1+yyy.C2`
It seems we can only get the real namespace form Type.FullName

**Comment by 0xd4d** [comment]
> It seems we can only get the real namespace form Type.FullName

It's unreliable. I suggest you open the assembly (mscorlib) and get the token of the type and resolve it. Maybe `ImportMapper` can be useful.

**Comment by CreateAndInject** [comment]
Your commit has serious bug:
`xxx.C1+C2`
This type deosn't have namespace, but Type.Namespace is `xxx`, so your commit will create TypeRef as : `xxx.C1+xxx.C2`

**Comment by CreateAndInject** [comment]
This code get the real namespace:
```
TypeRef CreateTypeRef2(Type type) {
	if (!type.IsNested)
		return module.UpdateRowId(new TypeRefUser(module, type.Namespace ?? string.Empty, type.Name ?? string.Empty, CreateScopeReference(type)));
	string ns = type.FullName.Substring(type.DeclaringType.FullName.Length + 1, type.FullName.Length - type.DeclaringType.FullName.Length - 1 - type.Name.Length);
	if (ns.Length > 0)
		ns = ns.Remove(ns.Length - 1);
	return module.UpdateRowId(new TypeRefUser(module, ns, type.Name ?? string.Empty, CreateTypeRef2(type.DeclaringType)));
```

**Comment by 0xd4d** [comment]
I removed that commit. That substring is a hack, and probably not something I'll add to the code. Have you verified that it works 100% of the time? It's better to do what I said above, open it with dnlib, resolve it, now you know with 100% certainty the nested namespace

**Comment by CreateAndInject** [comment]
[ConsoleApplication51.zip](https://github.com/0xd4d/dnlib/files/3390201/ConsoleApplication51.zip)

![image](https://user-images.githubusercontent.com/2529999/61186618-0c1e5680-a69a-11e9-87d6-227a12709d8d.png)

The real Namespace for `xxx.C1+yyy.C2` is `yyy`.

**Comment by CreateAndInject** [comment]
Create the target like this:
1. Build this code
```
namespace ConsoleApplication51
{
    class Program
    {
        static void Main(string[] args)
        {
            xxx.C1.C2.Test();
            Console.ReadKey();
        }
    }
}

namespace xxx
{
    public class C1
    {
        public class C2
        {
            public static void Test()
            {
                Console.WriteLine(typeof(C2).Namespace+"."+typeof(C2).Name);
            }
        }
    }
}
```

2.Load the assembly in dnSpy, and go to EntryPoint
3.Edit IL instructions, convert `call MethodDef` to `call MemberRef`.
4.Right Click `xxx.C1+C2`, Edit Type , set its namespace as yyy.
5.Save it. The output is runnable.

**Comment by CreateAndInject** [comment]
I find one more way:
```
static string GetRealNamesapce(Type type)
{
    var GetMetadataImport = typeof(ModuleHandle).GetMethod("GetMetadataImport", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance);
    object mdImport;
    if (GetMetadataImport.IsStatic) //.Net 4
        mdImport = GetMetadataImport.Invoke(null, new[] { type.Module });
    else //.Net 2
        mdImport = GetMetadataImport.Invoke(type.TypeHandle.GetModuleHandle(), null);
    return mdImport.GetType().GetMethod("GetNamespace").Invoke(mdImport, new object[] { type.MetadataToken }).ToString();
}
```

**Comment by 0xd4d** [comment]
The 2nd one is worse since it relies on implementation details, and who knows if it works on .NET Core or Mono.

I might add the substring hack unless there's a better way of doing it without having to add your own `ImportMapper`, open the assembly in dnlib and resolve it.

**Comment by CreateAndInject** [comment]
> I suggest you open the assembly (mscorlib) and get the token of the type and resolve it. Maybe `ImportMapper` can be useful.


> It's better to do what I said above, open it with dnlib, resolve it, now you know with 100% certainty the nested namespace


I write an unpacker based on dnlib, someone protector encrypts IL by DynamicMethod, it generates namespace for nestedtype, so when I restore IL by DynamicMethodBodyReader, the output will occur TypeLoadException becuase of this issue.
My tool should unpack all protected files, that's why I don't get tokens from dnSpy.

**Comment by 0xd4d** [comment]
I've pushed a new commit to master that should work.
