### ISSUE TITLE
How to correctly import or reference System.Private.CorLib Types and Methods

### ISSUE THREAD

**Issue by FenixDan** [0xd4d/dnlib#287]
Hello, I've read some of the issues already created for the same thing, however I'm unable to make it working .

https://github.com/0xd4d/dnlib/issues/244

The main problem I have is that if the assembly is using .NET Core and I want to import a Type or a Method it doesn't get the right TypeRef.

### This is my example code

This returns a TypeRef from System.Runtime instead of System.Private.CorLib, I know this is not wrong but I would like to reference System.Private.CorLib instead
`var type = module.CorLibTypes.GetTypeRef("System", "Type");` 

`var corLib = module.CorLibTypes;`
`var toString = new MemberRefUser(module, "ToString", methodSig.CreateInstance(corLib.String), type);`

So, the **toString** will contain a MemberRef to **System.Type.ToString** from **System.Runtime** but the assembly that really contains it is **System.Private.CorLib** which is a reference inside **System.Runtime**

![img](https://image.prntscr.com/image/K7xx5RavRDqZQKpgohZNAQ.png)

And this is what's wrong

![img](https://image.prntscr.com/image/PjFfPMCST5KxEWokMwMFUg.png)

**Comment by 0xd4d** [comment]
Resolve the `TypeRef` to get a `TypeDef`. Then use the `Importer` to import it (you'll get a `TypeRef`).

**Comment by FenixDan** [comment]
I think this is not the way, I'm not sure how you mean to resolve the TypeRef

`var x = context.Module.CorLibTypes.GetTypeRef("System", "Type");`
`var typeDef = x.ResolveTypeDef();`
`var type = importer.Import(typeDef);`

What do you recommend to resolve the TypeRef?

**Comment by 0xd4d** [comment]
It's `x.Resolve()`

**Comment by FenixDan** [comment]
It's not working as expected or I'm doing it wrong

![img](https://image.prntscr.com/image/4d-IVfQHRIS3Oyeic979uA.png)

**Comment by 0xd4d** [comment]
You're using .NET Core, so you need to tell the assembly resolver to only resolve .NET Core assemblies and not search the GAC.

**Comment by FenixDan** [comment]
Alright, thank you!
