### ISSUE TITLE
How to change framework version 4.0 to 2.0 & 2.0 to 4.0 with dnlib

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#288]
i'd like to know how
thank you

**Comment by 0xd4d** [comment]
2->4 is not needed since older assemblies can be loaded by .NET Framework 4.x.

4->2 can break the app since v4 has more APIs than 2.

There's no easy answer since assembly references can be stored anywhere including in baml, resources, custom attributes, etc.
