### ISSUE TITLE
Cannot load file or assembly

### ISSUE THREAD

**Issue by Biggie7** [0xd4d/dnlib#289]
The app first want dnlib 3.2.0.0 in file and when version 3.2.0.0 is placed in folder it wants dnlib 3.1.0.0
looking file in dnspy resource dnlib version for app is only 3.2.0.0

// CawkEmulatorV4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Colorful.Console, Version=1.2.9.0, Culture=neutral, PublicKeyToken=null
// de4dot.blocks, Version=3.1.41592.3405, Culture=neutral, PublicKeyToken=d3f3ed1e47f67fc6
// dnlib, Version=3.2.0.0, Culture=neutral, PublicKeyToken=50e96378b6e77999
// Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

GIF>(https://i.imgur.com/fxzP3yM.gifv)

hope to get your help,

**Comment by 0xd4d** [comment]
This isn't a dnlib issue. Looks like you need to add an app.config file that redicts 3.1.0.0 version to 3.2.0.0. Have a look at dnSpy's config file.
