### ISSUE TITLE
How would I insert a byte array?

### ISSUE THREAD

**Issue by binarysnake** [0xd4d/dnlib#291]
How would I insert a byte array into an already existing method, how would I use ArrayWriter?

**Comment by 0xd4d** [comment]
This is an answer your compiler can answer very easily. Just compile the code, have a look at the IL.

**Comment by binarysnake** [comment]
Okay, I've done that. I'm struggling with the ldtoken instruction though. How do I add a valuetype as operand?
![image](https://user-images.githubusercontent.com/49830371/61556984-5b320600-aa63-11e9-98f2-5c92fe96a729.png)

**Comment by 0xd4d** [comment]
`instruction.Operand = the_type;` and it should be the TypeDef if it's in the same module or a TypeRef if it's in some other module. Find the type, then use module.Import() to get a type ref. If you already know the name of it you can just create a TypeRefUser.

**Comment by binarysnake** [comment]
Okay thank you!
