### ISSUE TITLE
[Question] How do I add a string constructor

### ISSUE THREAD

**Issue by Sploash-c** [0xd4d/dnlib#293]
How would I properly add a constructor that compiles to:

`new string(chars)`?

This is the code I've got:

                        var stringCtor = new MethodDefUser(".ctor",
                            MethodSig.CreateInstance(module.CorLibTypes.String, module.ImportAsTypeSig(typeof(char[]))),
                            MethodImplAttributes.IL | MethodImplAttributes.Managed,
                            MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);

                        method.Body.Instructions.Insert(i + 3, OpCodes.Newobj.ToInstruction(stringCtor));

I'm getting an exception though:
`dnlib.DotNet.Writer.ModuleWriterException: 'Method System.String .ctor(System.Char[]) (06000000) is not defined in this module `

**Comment by 0xd4d** [comment]
You should use a MemberRef not a MethodDef. MethodDefs are for methods in the same module, MemberRefs are for fields/methods in another module.

**Comment by 0xd4d** [comment]
Questions like this can usually be answered by letting the compiler compile the code, then open the assembly with dnlib, find the method, get the instructions and check the operand in the locals/watch window. You'd then see that the operand is a MemberRef.

**Comment by Sploash-c** [comment]
Okay, I believe I fixed that, though when running my sample application I'm getting an exception:
`Unhandled Exception: System.MissingMethodException: Method not found: 'System.String System.String..ctor(Char[])'. At CharTest.Program.Main(String[] args)`
Is there a way I can use the default constructor method or do I need to add that in the module?

**Comment by 0xd4d** [comment]
ctor's return values are always Void.
