### ISSUE TITLE
Can't build using vs 2017 (version: 15.9.13)

### ISSUE THREAD

**Issue by kabua** [0xd4d/dnlib#294]
I just downloaded the code and tried to build (from within VS). But got several CS0150 errors, stating "A constant value is expected" (for `null`).

They all have to do with checking if the `byte*` variable is equal to `null`. 

Examples:
```
if (data is null)
if (blobPtr is null)
if (!(ptkResolutionScope is null))
if (!(szName is null) || !(pchName is null)) {
```
VS is stating that each variable is used incorrectly with this message: "Neither 'is' nor 'as' are valid on pointer types" and the compiler is expecting `null` to be defined as a constant value.

what am I doing wrong?

**Comment by 0xd4d** [comment]
Seems like older C# compiler can't compile that, so VS2019 is required now. I've updated the README.

Note that there's a nuget package so you don't need to compile it.
