### ISSUE TITLE
MetadataHeader padding in Mono

### ISSUE THREAD

**Issue by fsvn** [0xd4d/dnlib#295]
It would seem dnlib does not handle some potential extra padding in the metadata header. In mono at least [here](https://github.com/mono/mono/blob/master/mono/metadata/image.c#L485-L487), not sure about the coreclr.

**Comment by 0xd4d** [comment]
Maybe we need a reader option 'CLR' or 'Mono' because it's not always possible to detect it. AFAIK, Microsoft's CLRs never align it.

**Comment by fsvn** [comment]
> Maybe we need a reader option 'CLR' or 'Mono' because it's not always possible to detect it.

It seems like the most viable solution to coop with the quirks of mono's implementation.

There is also another quirk in mono's implementation where it does not check if it exceeds the bounds of the `TablesStream` as defined by its `StreamHeader` (see [here](https://github.com/mono/mono/blob/master/mono/metadata/image.c#L499-L500) and [here](https://github.com/mono/mono/blob/master/mono/metadata/image.c#L568)), however dnlib will do this bound check and throw a `DataReaderException("There's not enough bytes left to read")` if the  `StreamHeader.StreamSize` defining the `TablesStream` is set to something smaller than the actual size (0 will do fine causing the exception). [Here](https://drive.google.com/open?id=1Xp3ZlmWWmziap323dTu9HOK5I4BBxSGt) is a repro, `Repro-tampered.exe` will run fine on mono.

**Comment by 0xd4d** [comment]
I've updated the code and added a way to tell dnlib that it's an assembly read by mono: https://github.com/0xd4d/dnlib/blob/master/src/DotNet/ModuleCreationOptions.cs#L49

**Comment by fsvn** [comment]
Brilliant 🎉
