### ISSUE TITLE
ResolveTypeDef discarded generic type

### ISSUE THREAD

**Issue by DJPop** [0xd4d/dnlib#296]
I want to inject IL code calling some method via a Singleton class.
For example, `Singleton<MyClass>.instance.SomeMethod()`.
```
public class Singleton<T> where T : new() {
    private static T m_Instance;
    public static T instance {
        get {
            if (Singleton<T>.m_Instance == null) {
                Singleton<T>.m_Instance = Activator.CreateInstance<T>();
                Singleton.Init(Singleton<T>.m_Instance);
            }
            return Singleton<T>.m_Instance;
        }
    }
}
```
But I'm stuck at getting `Singleton<MyClass>` part.
```
var singleton = mod.FindNormalThrow(typeof(Singleton<>).FullName);
var myclass = mod.FindNormalThrow(typeof(MyClass).FullName);
var gen_sig = new GenericInstSig((ClassOrValueTypeSig)singleton.ToTypeSig(), myclass.ToTypeSig());
```
Calling `gen_sig.TryGetTypeDef()` returns null.
Calling `gen_sig.ToTypeDefOrRef()` returns TypeSpecUser, but calling `ResolveTypeDef()` afterward returns just ```Singleton`1``` and not ```Singleton`1<MyClass>```

What's the correct way to do this?

**Comment by 0xd4d** [comment]
You can only resolve a TypeDef, so you get the generic typedef. What are you trying to do with this return value?

**Comment by DJPop** [comment]
I'll inject the method body with these instructions.
```
OpCodes.Call.ToInstruction(new MemberRefUser(
    mod,
    "get_instance",
    MethodSig.CreateStatic(new GenericVar(0)),
    gen_sig.ToTypeDefOrRef()
))
OpCodes.Callvirt.ToInstruction(mymethod)
```
Even though those types are in the same module, TypeDefs never work (but TypeRefs do).
Right now calls are references even though those types are in the same module. (When I check with dnSpy, the assembly references itself in the References section).

**Comment by 0xd4d** [comment]
Have you looked at the compiler generated code what it generates? Find the instruction in the body and compare it against your created instruction.
