### ISSUE TITLE
How to invoke?

### ISSUE THREAD

**Issue by ewwink** [0xd4d/dnlib#297]
below are The code, `mtd` is the method that I want to invoke

```c#
var ModuleDef = ModuleDefMD.Load(filename);
MethodInfo stringMethod = (MethodInfo)ModuleDef.Assembly.ManifestModule
                           .ResolveToken((int)mtd.MDToken.Raw);
object obj = stringMethod.Invoke(null, null);
```

the code is successfully compiled but when I running the app I got error from second line

```Unable to cast object of type 'dnlib.DotNet.MethodDefMD' to type 'System.Reflection.MethodInfo'.```

**Comment by 0xd4d** [comment]
You have to load the assembly with eg. `Assembly.LoadFile()` and then resolve the method to get a `MethodInfo`

**Comment by ewwink** [comment]
I know that but the `ModuleDef` is in the middle processing and partially decrypted so I can't re-open the file, but it was solved I use different way.

before closing, do you have plan to add like `MethodDef.invoke()` ?

**Comment by 0xd4d** [comment]
> before closing, do you have plan to add like `MethodDef.invoke()` ?

No because it requires loading runtime assemblies.

**Comment by ewwink** [comment]
OK thank you.
