### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#298]
https://github.com/0xd4d/dnlib/blob/f67f9696bfafc119f89eae19d31f5ec48d140810/src/DotNet/Emit/DynamicMethodBodyReader.cs#L456

System.ArgumentException if contains generic

It works with this, but I'm not sure whether it allways works:
```return importer.Import(SR.FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)obj, default(RuntimeTypeHandle)));```

**Comment by 0xd4d** [comment]
Show some simple repro code.

**Comment by CreateAndInject** [comment]
```
class Program
{
    static void Main(string[] args)
    {
        var fi = typeof(Test<>).GetField("Field"); // or typeof(Test<int>).GetField("Field");
        var handle = fi.FieldHandle;
        var field = FieldInfo.GetFieldFromHandle(handle);
    }
}

class Test<T>
{
    public static T Field;
}
```

**Comment by 0xd4d** [comment]
I see no dnlib refs in that code so it doesn't looke like a simple repro to me.

**Comment by CreateAndInject** [comment]
It happens in DynamicMethodBodyReader, so there's no dnlib refs, it's dynamic.

**Comment by 0xd4d** [comment]
I'm still missing a repro that I can compile.

**Comment by CreateAndInject** [comment]
I found it in a random file, and I can't write a simple repro, the field is : 
`ldfld System.__Canon System.Runtime.CompilerServices.CallSite`1<System.__Canon>::Target`

**Comment by CreateAndInject** [comment]
Now, I can write a repro:
[DynamicTest.zip](https://github.com/0xd4d/dnlib/files/3464178/DynamicTest.zip)
```
    class Program
    {
        public static void Main()
        {
            var module = ModuleDefMD.Load(typeof(Program).Module);
            var dm = DynamicMethodHelper.ConvertFrom(typeof(Program).GetMethod("Test"));
            //Must call Invoke/CreateDelegate..., or else DynamicMethodBodyReader can't work. Why???
            dm.CreateDelegate(typeof(Action));
            var dmr = new DynamicMethodBodyReader(module, dm);
            dmr.Read();
            var instrs = dmr.Instructions;
        }

        public static void Test()
        {
            dynamic obj = 1;
            obj.ToString();
        }
    }
```

I don't know how to create a DynamicMethod from byte[] or MethodInfo, but I found DynamicMethodHelper based on ILReader, is there a simple way?

**Comment by CreateAndInject** [comment]
@0xd4d Do you view my repro?
Today, I find another one protected by Virbox.
So, if protector use dynamic method, such as ILProtector & Virbox, it can repro this issue.

**Comment by 0xd4d** [comment]
No I haven't investigated this yet. Have you debugged it and know where it throws?

**Comment by CreateAndInject** [comment]
Please view [DynamicTest.zip](https://github.com/0xd4d/dnlib/files/3464178/DynamicTest.zip)
It can repro this issue.

**Comment by CreateAndInject** [comment]
Now, I can repro it easily without `C# 4.0 dynamic`
[DynamicTest2.zip](https://github.com/0xd4d/dnlib/files/3731271/DynamicTest2.zip)

```
class Program
{
    public static void Main()
    {
        var module = ModuleDefMD.Load(typeof(Program).Assembly.Location);
        module.Context = ModuleDef.CreateModuleContext();
        var dm = DynamicMethodHelper.ConvertFrom(typeof(My<>).GetMethod("Test"));
        dm.GetType().GetMethod("GetMethodDescriptor", BindingFlags.NonPublic | BindingFlags.Instance).Invoke(dm, null);
        var dmr = new DynamicMethodBodyReader(module, dm);
        dmr.Read();
        var instrs = dmr.Instructions;
        Console.WriteLine("OK");
        Console.Read();
    }
}

class My<T>
{
    public static T a;

    public static void Test()
    {
        a = default(T);
    }
}
```

It's easy to fix in dnlib:
```return importer.Import(SR.FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)obj, default));```
Please check it.

**Comment by CreateAndInject** [comment]
My fix is wrong, the output dosn't work, must pass in real declaringType, and I don't know how to fix dnlib.
It can repro when converting `Anonymous Type` to `DynamicMethod`
```var obj = from c in "abcde" select new { Text = c.ToString(), Char = c };```

**Comment by anywhereyang** [comment]
@CreateAndInject  is any new progress of this issue ?

**Comment by 0xd4d** [comment]
What's the minimal code to repro this, something that doesn't depend on some 3rd party code you use above?

If it's not possible to get the declaring type from System.Reflection, then this isn't fixable.

**Comment by CreateAndInject** [comment]
[DynamicTest2.zip](https://github.com/0xd4d/dnlib/files/3731271/DynamicTest2.zip)
This project doesn't reference any 3rd party code.
I don't know how to convert a MethodInfo to DynamicMethod, so I use DynamicMethodHelper, it's a party of the source project. If you know some other way to generate a DynamicMethod from MethodInfo, you can remove DynamicMethodHelper code.

**Comment by 0xd4d** [comment]
The code now passes in `default` as the 2nd argument which seems to work. You mentioned above that it doesn't always work but if there's no other way to get the declaring type, then this is not fixable since it's System.Reflection.

**Comment by CreateAndInject** [comment]
@0xd4d I'm afraid you should revert the commit, it's worse than before.
Since dnlib doesn't occur any exception, and the developer doesn't realize the error, when the output call relative methods, it will crash.

The old code will occur exeption, so the developer know where's problem, and can use hard code to fix at least.

**Comment by 0xd4d** [comment]
I've added a new option to a new ctor that can be used to enable this feature.
