### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by svick** [0xd4d/dnlib#30]
It seems that dnlib is not available from NuGet, which makes it harder to use. I think you should consider creating a NuGet package for it.

**Comment by 0xd4d** [comment]
It's probably not something I'll ever do. Is it really so difficult to compile it yourself?

**Comment by svick** [comment]
It's not difficult, but it is a hassle. If I want to quickly try the library, it's great if I can get it in just few clicks using NuGet (and after that, that I can easily keep it updated).

In my specific case (which I realize is far from common), I was considering answering [a question on SO](http://stackoverflow.com/q/29961998/41071) (which is the same as #28). But when I saw that the library (which I didn't hear about before) is not on NuGet, I simply didn't bother.

**Comment by swellfr** [comment]
Hi 0xd4d,

I'm joining svick on this request, this lib is amazing and it 's too bad that there is no nuget package of it.

First, to answer your question, no it's not difficult to compile it and add a reference to your project.

But, here is why it would be great if you reconsider your position on a nuget package
- adding dnlib to a project would follow all the current workflow of all other libs
- no need to version it in source control
- when you release a new version we'll be aware of it

Finally this would give the .net community an amazing lib in our toolbox.

In any case thanks for the amazing job on this lib!
