### ISSUE TITLE
RawAddress error in NativeModuleWriter

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#300]
If RawAddress for the first few sections of the original file is 0, RawAddress for the saved file is not 0.

![Snipaste_2019-08-11_13-05-02](https://user-images.githubusercontent.com/27536652/62829996-ad1c1500-bc38-11e9-8d11-48b0add51089.png)
![Snipaste_2019-08-11_12-38-52](https://user-images.githubusercontent.com/27536652/62829968-4eef3200-bc38-11e9-94e6-6ed386cd5d37.png)
![Snipaste_2019-08-11_12-41-49](https://user-images.githubusercontent.com/27536652/62829969-50205f00-bc38-11e9-8af8-9a65cc14e1a1.png)

**Comment by 0xd4d** [comment]
Does it crash at runtime? Does it really have to be 0?

**Comment by wwh1004** [comment]
It won't crash. I just think there may be potential problems.
