### ISSUE TITLE
How to get export symbols

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnlib#301]
Is it possible to get export symbols (name & address) from a PE file? I couldn't find a property for it. If it does not exist, can this be added?

```
var pe = new PEImage(@"C:\Windows\System32\mshtml.dll");
... ?
```

![asd](https://user-images.githubusercontent.com/14368203/63168305-4ecda880-c023-11e9-944f-69f501048c39.jpg)

**Comment by 0xd4d** [comment]
It's not possible since it was designed to only read .NET files. It's not supposed to support every single PE file feature.
