### ISSUE TITLE
Licensing question in regards to packaging and publishing to NuGet

### ISSUE THREAD

**Issue by MeikTranel** [0xd4d/dnlib#303]
Before the first actual release of my package i wanted to make sure we're cool here.

One of the requirements of MIT is the inclusion of the copyright notice... well. I'm deploying DNLib directly inside my NuGet package, so as per requirement the idea of MIT would tell me to put a license notice in the NuPKG file. Problem is, now more than ever (because of the existence of nuget package caches outside of your working directory) package contents are completely unseen by 99,99999% of regular consumers, thus defeating the point of the notice.

With that in mind i'd propose a more visible notice by listing DNLib in my README.md.

Project in question: https://github.com/MeikTranel/NXPorts

Any thoughts? Is this cool for you? (Please don't feel pressured or something. I'm completely fine with whatever you want me to do 😉)

**Comment by 0xd4d** [comment]
You should ask a lawyer.

What's the reason for including dependenices inside your nuget package? Nuget can take care of that.

**Comment by MeikTranel** [comment]
It's a MSBuild task package which makes use of dnlib during build. Task packages can't make use of package dependencies unfortunately.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 0xd4d** [comment]
Including a text file in the nuget with all license info should be enough

**Comment by MeikTranel** [comment]
I'll do that, thanks.
