### ISSUE TITLE
Mismatch in generic arguments in method overrides

### ISSUE THREAD

**Issue by mkaring** [0xd4d/dnlib#304]
Hello,

I am tracking a issue that may be caused by dnlib. The problem is that I encountered an unexpected signature for the override of a method. The problem is the `MethodOverride` of a method that points to a generic interface (in that case ``IEnumerable`1``). The problem is that the signature of the `DeclaringType` contains the proper generic arguments, but the return value of the method signature contains a generic type called `T` instead of the correct one. I am talking about the `MethodDeclaration` part of the override.

I created a minimal example and a unit test to showcase the issue:
[OverwriteSignatureProblem.zip](https://github.com/0xd4d/dnlib/files/3563755/OverwriteSignatureProblem.zip)

Can you confirm that this is a error, or am I doing something wrong? If you need anything else to track the issue, please let me know.

Best regards,
Martin

**Comment by 0xd4d** [comment]
There's a generic param in the signature in the metadata so it has to be in the MethodSig too. Can you show what you modify the methodoverride to before and after.

**Comment by mkaring** [comment]
I am not sure what you mean. I did not modify anything. My example shows the released version of dnlib that has an behaviour that is unexpected by me. There is no "modification".

**Comment by 0xd4d** [comment]
Show the real code you're using then, seems like you're just copying the return type from one sig to another without replacing the generic parameters with the generic arguments.

**Comment by 0xd4d** [comment]
Also attach a small repro if possible or it will take longer to figure out if there's something wrong with your code or dnlib's code.

**Comment by mkaring** [comment]
I'm not sure why the example project I provided when opening the issue isn't helping. Can't you access the file or something?

The actual code that fails is here: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/Analyzers/VTableAnalyzer.cs#L141
It adds the override declarations to the `MethodDef` in case the method is a implicit override instead of an explicit one. That fails, because the method signature of the declaration isn't matching the signature of the target method, because the method declaration in the signature doesn't contain the full generic type, just as showcased in the minimal example provided.

**Comment by 0xd4d** [comment]
The example you provided is just a test, it doesn't generate the runtime error your users reported. I'm trying to figure out if it's a dnlib error or not. A short repro will help.

**Comment by mkaring** [comment]
The cause of the runtime error is that the signature comparison in the line I provided above fails. This causes that an additional override is added. One with the generic type set to `<T>` and one set to the `KeyValuePair<...>`. This causes that the type fails to load.

I have the error reproduced in a unit test with the runtime code here:
https://github.com/mkaring/ConfuserEx/tree/feature/78_sig_mismatch/Tests/78_SignatureMismatch
and the test code here:
https://github.com/mkaring/ConfuserEx/tree/feature/78_sig_mismatch/Tests/78_SignatureMismatch.Test

**Comment by 0xd4d** [comment]
Thanks but that's not a small repro. A small repro has as few dependencies as possible, in this case only dnlib and the runtime. Your repro has the full ConfuserEx source code as a dependency.

If it's the type comparison line you showed earlier, it's probably because you haven't replaced the generic parameters with the generic arguments. ConfuserEx should already have some class that can do that, its renamer must do something like that when comparing sigs, probably this code: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/GenericArgumentResolver.cs

**Comment by mkaring** [comment]
There is a file attached! At the beginning of this issue.
Here: [OverwriteSignatureProblem.zip][1]
This shows my expectation and the actual output. It's as minimal as possible and it only has dnlib as dependency.

[1]: https://github.com/0xd4d/dnlib/files/3563755/OverwriteSignatureProblem.zip

**Comment by 0xd4d** [comment]
It's a test that doesn't repro the runtime error as explained here https://github.com/0xd4d/dnlib/issues/304#issuecomment-527077135

Did you replace generic params with generic args?

**Comment by mkaring** [comment]
I know why the runtime error is happening. Nonsense is written to the assembly, because dnlib is asked to do so. That isn't the problem. The reason why nonsense is written, is because the equals check that is in the failing `Assert.True` in the Unit Test I provided here is `false`, but I expected it to be `true`.

The problem from my point of view is the method declaration. The method declaration does not have matching generic types. The generic type of the declaring type of the method isn't matching the method signature of the method itself.
The declaring type of the override method declaration is resolved to `IEnumerable<KeyValuePair<string, int>>`
The signature of the override method declaration is resolved to `IEnumerator<T> ()`, but I would expect it to resolve to `IEnumerator<KeyValuePair<string, int>> ()`
I do not understand why that is not the case. 

To get back to the runtime error, this mismatch causes that the latter declaration is added to the overrides of the method. So that means that the `GetEnumerator` method has two overrides:

1. `IEnumerator<T> IEnumerable<KeyValuePair<string, int>>::GetEnumerator()`
2. `IEnumerator<KeyValuePair<string, int>> IEnumerable<KeyValuePair<string, int>>::GetEnumerator()`

And that is just wrong and naturally causes .NET to reject this type.
The strange thing is that either of those overrides works. So if only one of both declarations is present, there is no runtime error.

**Comment by 0xd4d** [comment]
It's how it's represented in metadata and same way in dnlib, it's a MemberRef, decl type is a generic instance type, and the method sig has a generic parameter that you replace with the generic arg. No generic parameter is replaced with the generic arg by dnlib, if you want that behavior you must do it yourself. ConfuserEx seems to do it already, I linked to the class in a previous reply.

**Comment by mkaring** [comment]
You are correct. Thank you for the support. :)
