### ISSUE TITLE
Determine declaring filename and line number of external method.

### ISSUE THREAD

**Issue by arakis** [0xd4d/dnlib#309]
For generating DWARF Symbols in an custom compiler ( https://github.com/mosa/MOSA-Project/blob/233a87b0cbf45539367c7f6e5d9376f0053dfbd7/Source/Mosa.Compiler.Extension.Dwarf/DwarfCompilerStage.cs ), i need the source code location of an external method.

Lets declaring the following situation:
Native.cs:
```
...
389
390  [DllImport("x86/Lonos.InterruptReturn.o", EntryPoint = "InterruptReturn")]
391  private static extern void InterruptReturn(uint stackStatePointer, uint dataSegment, uint pageTableAddr);
391
...
```
Now, I have a MethodDef. The body is null (of course), so the way described in #248 does not work. How to resolve MethodDef ("InterruptReturn") to Location Native.cs:391?

**Comment by 0xd4d** [comment]
The compiler only adds sequence points if it has a method body so you won't be able to find any location info about that method in the PDB.

One solution is to find a list of all source code files and check every line if it has an extern method.

If you don't know the source code file names, you can get the list of all source code files with method bodies in them (`module.PdbState?.Documents`)
