### ISSUE TITLE
Cant remove method arguments and move methods to other types

### ISSUE THREAD

**Issue by GazziFX** [0xd4d/dnlib#310]
Code that causes errors
https://pastebin.com/Enux1Gzj

**Comment by 0xd4d** [comment]
Add a small self contained repro, the code you showed is just a snippet of a larger method.

BTW, use `SigComparer` to compare types and members. None of them overrides `Equals()`.

**Comment by 0xd4d** [comment]
Do you have a repro or more info?

**Comment by GazziFX** [comment]
What do you mean?

**Comment by GazziFX** [comment]
https://github.com/GazziFX/test/

**Comment by 0xd4d** [comment]
`foreach (var method in type.Methods)` iterates over the methods and later inside the same loop, you modify the very same list you're iterating. You can change it to `foreach (var method in type.Methods.ToArray())`

**Comment by GazziFX** [comment]
Yes, It works

**Comment by 0xd4d** [comment]
`SigComparer` must be used or you're just comparing by reference which is wrong most of the time.
