### ISSUE TITLE
"Call" instructions dont changes on renaming some methods

### ISSUE THREAD

**Issue by Sl4vP0weR** [0xd4d/dnlib#311]
"call", "callvirt" instructions dont changes if I renaming the method
before:
![image](https://user-images.githubusercontent.com/42337892/66478107-38484880-eacc-11e9-8b72-1d1e2f3d2d9f.png)
after:
![image](https://user-images.githubusercontent.com/42337892/66478193-67f75080-eacc-11e9-8310-c1619d90ce45.png)

**Comment by GazziFX** [comment]
Its absolutely different code, I cant understand what is wrong.
Offtop: LOL im from Russia and coding for Unturned too

**Comment by 0xd4d** [comment]
The pictures don't even seem to show the same methods.

Add some more info, eg. what is wrong with it. Add a small self contained repro.

**Comment by Sl4vP0weR** [comment]
> The pictures don't even seem to show the same methods.
> 
> Add some more info, eg. what is wrong with it. Add a small self contained repro.

@0xd4d 
On the pics u can see - i'm renamed all methods in class.
Methods like "Log", "Shutdown" dont exists, but instructions "call", "callvirt" dont change reference on those methods.

**Comment by Sl4vP0weR** [comment]
@GazziFX Sl4vP0weR#4178

**Comment by GazziFX** [comment]
Maybe method "Log" still named "Log"?
Method "_3F" reference method "_ud" that is actually "DestroyComponent" I think, I don't notice anything strange

**Comment by Sl4vP0weR** [comment]
> Maybe method "Log" still named "Log"?
> Method "_3F" reference method "_ud" that is actually "DestroyComponent" I think, I don't notice anything strange

No, dnSpy can't go to method if i click on the "Log"
And dnSpy shows me: all methods renamed

**Comment by 0xd4d** [comment]
You can use https://github.com/0xd4d/dnlib/blob/master/src/DotNet/MemberFinder.cs to find all refs in code and other places.
