### ISSUE TITLE
#US heap is too big

### ISSUE THREAD

**Issue by 25rtsregre** [0xd4d/dnlib#313]
Hi, 
i am currently receiving 
https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/USHeap.cs#L97

this exception, if i comment the check out it works fine however im unsure if this will break something else in the future

Kind Regards

**Comment by 0xd4d** [comment]
`ldstr` instructions reference the #US heap with a 24-bit offset so it could still work if you add a super long string at offset 0x00FFFFFF.

If you have 16MB or more UTF-16 strings, it's better to store them in the resources or in text files.
