### ISSUE TITLE
Corrupts attribute constructor Type array parameters

### ISSUE THREAD

**Issue by MulleDK19** [0xd4d/dnlib#315]
Been spending the entire day debugging why the CLR complained about being unable to load a .NET Framework type from my own assembly, and finally decided to look closer at the tool we wrote to do some post build modifications using dnlib, and as it turns out dnlib resolves the wrong types in attribute constructors. Or rather, doesn't write it correctly.

We're using two tools. One that adds an unmanaged export, always; and another tool that does some additional work on release builds only.

Eg. for this attribute with a simple `SomeAttribute(Type[] types)` constructor:
```csharp
[SomeAttribute(new Type[] { typeof(bool) })]
public class TestClass
```

The compiler emits the following for the Type[] constructor parameter.
```
01 00 01 00 00 00 5b 53 79 73 74 65 6d 2e 42 6f
6f 6c 65 61 6e 2c 20 6d 73 63 6f 72 6c 69 62 2c
20 56 65 72 73 69 6f 6e 3d 34 2e 30 2e 30 2e 30
2c 20 43 75 6c 74 75 72 65 3d 6e 65 75 74 72 61
6c 2c 20 50 75 62 6c 69 63 4b 65 79 54 6f 6b 65
6e 3d 62 37 37 61 35 63 35 36 31 39 33 34 65 30
38 39 00 00
```

Which contains the full name `[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`

When the compiled assembly then gets passed to the tool that adds the unmanaged export, when dnlib writes the module back, instead of the fully qualified name, it only emits the type name:

```
01 00 01 00 00 00 0e 53 79 73 74 65 6d 2e 42 6f
6f 6c 65 61 6e 00 00
```

`System.Boolean`

When the second tool loads the module, dnlib resolves that `System.Boolean` to be a type named `System.Boolean` in the module itself, and thus when it saves, the parameter becomes

```
01 00 01 00 00 00 54 53 79 73 74 65 6d 2e 42 6f
6f 6c 65 61 6e 2c 20 53 6f 6d 65 41 73 73 65 6d
62 6c 79 31 2c 20 56 65 72 73 69 6f 6e 3d 31 2e
30 2e 30 2e 30 2c 20 43 75 6c 74 75 72 65 3d 6e
65 75 74 72 61 6c 2c 20 50 75 62 6c 69 63 4b 65
79 54 6f 6b 65 6e 3d 6e 75 6c 6c 00 00
```

`System.Boolean, SomeAssembly1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

And now the assembly crashes once the CLR tries to instantiate that attribute.

**Comment by 0xd4d** [comment]
Do you have a repro? I tried to repro it but it worked for me (no crash at runtime).

**Comment by MulleDK19** [comment]
You need to save twice, and then actually instantiate the attribute.
I'll have a repro in a few min.

**Comment by 0xd4d** [comment]
I did that, read, save, read, save, run no crash.

Here's the code that finds the type if there's no assembly:

https://github.com/0xd4d/dnlib/blob/master/src/DotNet/CustomAttributeReader.cs#L24-L44

If it can't resolve the type, it assumes it's in the current assembly. I'd check your assembly resolver (or debug that code above to figure out why it can't find the core library).

**Comment by MulleDK19** [comment]
You need to instantiate the attribute.

[SomeApp.zip](https://github.com/0xd4d/dnlib/files/3746058/SomeApp.zip)

Unzip, open solution, right click solution > Restore NuGet Packages, and run.

**Comment by 0xd4d** [comment]
I did that.

You're missing an asm resolver.

```C#
            var options = new ModuleCreationOptions(ModuleDef.CreateModuleContext());
            var asmResolver = (AssemblyResolver)options.Context.AssemblyResolver;
            using (ModuleDefMD module = dnlib.DotNet.ModuleDefMD.Load(File.ReadAllBytes(orgPath), options))
            {
                asmResolver.AddToCache(module);
                // Swap entry point so modified version runs InstantiateClass instead of Main again.
                module.EntryPoint = module.Find("SomeApp.Program", false).FindMethod("InstantiateClass");

                // dnlib now only writes 'System.Boolean' instead of the fully qualified name.
                module.Write(modifiedPath);
            }
```

**Comment by MulleDK19** [comment]
Hmm.

But it still omits the assembly qualified name and just emits the type name.
If it emitted the assembly qualified name like the C# compiler does, it'd avoid issues like this and the second instance wouldn't need a resolver and end up corrupting an assembly that it simply opens and saves.

And even with the resolver there is some issue going on.

For example, if you the first time you open add a `System.Boolean` class to the `SomeApp` assembly.
```csharp
module.Types.Add(new TypeDefUser("System", "Boolean"));
```
dnlib emits the assembly qualified name to the System.Boolean in mscorlib, and the reference to the type in mscorlib is maintained.

But if you instead add the type in the second modification, when it saves, it'll now emit just the type name again, replacing it with the internal type.

```csharp
options = new ModuleCreationOptions(ModuleDef.CreateModuleContext());
asmResolver = (AssemblyResolver)options.Context.AssemblyResolver;
using (ModuleDefMD module = dnlib.DotNet.ModuleDefMD.Load(File.ReadAllBytes(modifiedPath), options))
{
    ////CorLibTypeSig val = (CorLibTypeSig)((IList<CAArgument>)module.Find("SomeApp.TestClass", false).CustomAttributes[0].ConstructorArguments[0].Value)[0].Value;
    module.Types.Add(new TypeDefUser("System", "Boolean"));
    module.Write(modifiedPath);
}
```

The modified version will now be corrupt again. What's interesting is, if you uncomment that line that reads the attribute constructor argument, dnlib will emit the assembly qualified name and retain the proper reference.

**Comment by 0xd4d** [comment]
You should always add an assembly resolver. You might get away without one if all you do is read the assembly and don't need to know if a type is a value type or not. If you save the file, you definitlely need one. I should make it more clear in the readme if I haven't already.

> But if you instead add the type in the second modification, when it saves, it'll now emit just the type name again, replacing it with the internal type.

It's because the custom attribute hasn't been read yet. By the time it reads it, the CA reader will try to resolve the type in the current assembly and it will find your new type.

**Comment by 0xd4d** [comment]
The missing assembly resolver solves this problem so I'm closing it.

I've added an option to enable/disable this feature, and updated the README to include info on how to create a default assembly resolver

**Comment by catester** [comment]
I am having a similar issue, I have a class like below in SomeAssembly:

```c#
[TypeConverterAttribute(typeof(TypeConverter))]
public sealed class SomeClass
{
}
```

When I compile it to a netstandard2.0 dll and then open and save it via net40 app which uses dnlib 3.2, and then access the dll at runtime from a netcore 2.0 app, I get this error:

```
TypeLoadException: Could not load type 'System.ComponentModel.TypeConverter' from assembly 'SomeAssembly, Version=*.*.*.*, Culture=neutral, PublicKeyToken=***'.
```

Well this type should be in System.ComponentModel.TypeConverter.dll on netcore runtime and the error says it's in my DLL? So it seems ClassSig in the custom attribute is written wrongly? Also when I examine the saved DLL in dnSpy, I can no more click on TypeConverter inside [TypeConverterAttribute(typeof(**TypeConverter**))] which indicates dnSpy cannot resolve it too.

I also followed your suggestion of using the assembly resolver but it didn't make any difference?

```c#
var options = new ModuleCreationOptions(ModuleDef.CreateModuleContext());
var asmResolver = (dnlib.DotNet.AssemblyResolver)options.Context.AssemblyResolver;
asmResolver.PreSearchPaths.Add(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9");

primaryModule = ModuleDefMD.Load(primaryAssemblyFile, options);
asmResolver.AddToCache(primaryModule);
```

I examine caArgument.Value before saving it looks like this:
```
{System.ComponentModel.TypeConverter}
    AssemblyQualifiedName: "System.ComponentModel.TypeConverter, netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
    ContainsGenericParameter: false
    DefinitionAssembly: {netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51}
    ElementType: Class
    FullName: "System.ComponentModel.TypeConverter"
    IsArray: false
    IsByRef: false
    IsClassSig: true
    IsCorLibType: false
    IsFunctionPointer: false
    IsGenericInstanceType: false
    IsGenericMethodParameter: false
    IsGenericParameter: false
    IsGenericTypeParameter: false
    IsModifier: false
    IsModuleSig: false
    IsOptionalModifier: false
    IsPinned: false
    IsPointer: false
    IsPrimitive: false
    IsRequiredModifier: false
    IsSZArray: false
    IsSentinel: false
    IsSingleOrMultiDimensionalArray: false
    IsTypeDef: false
    IsTypeDefOrRef: true
    IsTypeRef: true
    IsTypeSpec: false
    IsValueArray: false
    IsValueType: false
    IsValueTypeSig: false
    MDToken: TypeSpec 0
    Module: {SomeAssembly.dll}
    Namespace: "System.ComponentModel"
    Next: null
    ReflectionFullName: "System.ComponentModel.TypeConverter"
    ReflectionName: "TypeConverter"
    ReflectionNamespace: "System.ComponentModel"
..
```

Do you have any solutions?

**Comment by 0xd4d** [comment]
Open a new issue. Sounds like you're not using the correct reference assemblies. Resolve to the correct tfm ref assemblies, your file is a netstandard assembly so shouldn't resolve .NET Core assemblies.

**Comment by 0xd4d** [comment]
https://www.nuget.org/packages/NETStandard.Library/

**Comment by catester** [comment]
Ok opened a new issue #318 and also posted the solution, dnlib needs a simple patch. @MulleDK19 was right, it's not about resolving assemblies, it's about writing missing type info with custom attributes.
