### ISSUE TITLE
Can't resolve the type of variable

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#316]
![image](https://user-images.githubusercontent.com/2529999/67379968-3eeeb980-f5bc-11e9-917f-a3ebf98535fd.png)

When I unpack a program using DynamicMethodBodyReader, there's no issue with most methods, but 2 methods will occur above issue.

**Comment by CreateAndInject** [comment]
Effect when ignore errer:

![image](https://user-images.githubusercontent.com/2529999/67381154-07810c80-f5be-11e9-8e0f-a97de2be1d94.png)
![image](https://user-images.githubusercontent.com/2529999/67381170-12d43800-f5be-11e9-9abd-cf2e33008a5a.png)
![image](https://user-images.githubusercontent.com/2529999/67381205-22ec1780-f5be-11e9-90e4-a79e04f71701.png)

**Comment by 0xd4d** [comment]
There's no repro so I suggest you debug it and get more info. Figure out why the index is out of range, check the callers.

**Comment by 0xd4d** [comment]
Make sure the data used to create the dynamic method is valid. If you decrypted it, make sure you decrypted everything correctly.

**Comment by CreateAndInject** [comment]
This program can only run with a dongle, so you can't repro.
But I found a fix:

https://github.com/0xd4d/dnlib/blob/5b870f6b5e064943b9db6914c909fd2a7bf67e38/src/DotNet/Emit/DynamicMethodBodyReader.cs#L489-L500

`return ImportType(rid);` => `return ImportType(rid) ?? module.ResolveToken(token) as ITypeDefOrRef;`

I had viewed mscorlib.dll, but I don't find whether .net runtime will resolve token from assembly when the rid is out of range, please check it, thanks!

**Comment by 0xd4d** [comment]
That seems to be the correct fix, except that `ImportType(rid)` shouldn't be called.
