### ISSUE TITLE
CustomAttributeWriter does not write assembly qualified types, causes error in NetCore

### ISSUE THREAD

**Issue by catester** [0xd4d/dnlib#318]
I am having a similar issue as in #315, I have a class like below in SomeAssembly:

```c#
[TypeConverterAttribute(typeof(TypeConverter))]
public sealed class SomeClass
{
}
```

When I compile it to a netstandard2.0 dll and then open and save it via net40 app which uses dnlib 3.2, and then access the dll at runtime from a netcore 2.0 app, I get this error:

```
TypeLoadException: Could not load type 'System.ComponentModel.TypeConverter' from assembly 'SomeAssembly, Version=*.*.*.*, Culture=neutral, PublicKeyToken=***'.
```

Well this type should be in System.ComponentModel.TypeConverter.dll on netcore runtime and the error says it's in my DLL? So it seems ClassSig in the custom attribute is written wrongly? Also when I examine the saved DLL in dnSpy, I can no more click on TypeConverter inside [TypeConverterAttribute(typeof(**TypeConverter**))] which indicates dnSpy cannot resolve it too.

I also followed your suggestion of using the assembly resolver but it didn't make any difference?

```c#
var options = new ModuleCreationOptions(ModuleDef.CreateModuleContext());
var asmResolver = (dnlib.DotNet.AssemblyResolver)options.Context.AssemblyResolver;
asmResolver.PreSearchPaths.Add(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9");

primaryModule = ModuleDefMD.Load(primaryAssemblyFile, options);
asmResolver.AddToCache(primaryModule);
```

If I examine caArgument.Value before saving the DLL looks like this:
```
{System.ComponentModel.TypeConverter}
    AssemblyQualifiedName: "System.ComponentModel.TypeConverter, netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
    ContainsGenericParameter: false
    DefinitionAssembly: {netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51}
    ElementType: Class
    FullName: "System.ComponentModel.TypeConverter"
    IsArray: false
    IsByRef: false
    IsClassSig: true
    IsCorLibType: false
    IsFunctionPointer: false
    IsGenericInstanceType: false
    IsGenericMethodParameter: false
    IsGenericParameter: false
    IsGenericTypeParameter: false
    IsModifier: false
    IsModuleSig: false
    IsOptionalModifier: false
    IsPinned: false
    IsPointer: false
    IsPrimitive: false
    IsRequiredModifier: false
    IsSZArray: false
    IsSentinel: false
    IsSingleOrMultiDimensionalArray: false
    IsTypeDef: false
    IsTypeDefOrRef: true
    IsTypeRef: true
    IsTypeSpec: false
    IsValueArray: false
    IsValueType: false
    IsValueTypeSig: false
    MDToken: TypeSpec 0
    Module: {SomeAssembly.dll}
    Namespace: "System.ComponentModel"
    Next: null
    ReflectionFullName: "System.ComponentModel.TypeConverter"
    ReflectionName: "TypeConverter"
    ReflectionNamespace: "System.ComponentModel"
..
```

This problem does not happen with net40 SomeAssembly.dll, it only happens with netstandard2.0 SomeAssembly.dll (the tool that uses dnlib to modify both SomeAssembly.dll, is a net40 app).

Do you have any solutions?

_Originally posted by @catester in https://github.com/0xd4d/dnlib/issues/315#issuecomment-546803786_

**Comment by catester** [comment]
Ok, I debugged dnlib and the problem is here:
https://github.com/0xd4d/dnlib/blob/a0b58a65c8d21ca14c79a8f6bf06b478e324e19c/src/DotNet/Writer/CustomAttributeWriter.cs#L719

I changed that line so that it always writes assembly qualified names for CustomAttributes "Type" parameters:
```c#
this.WriteUTF8String(type.AssemblyQualifiedName);
```

Because when FullNameFactory.AssemblyQualifiedName() is used, it decides to not add assembly name if this inner method returns false. So maybe you should check this function. I guess it should return true even if it's a CorLib type?

https://github.com/0xd4d/dnlib/blob/c993df8800ff2d3ac279720344461f8dfbae9c26/src/DotNet/FullNameFactory.cs#L45-L59

So the problem is not about using a AssemblyResolver at all. Even if I remove the AssemblyResolver, after this change to dnlib, my netstandard2.0 DLL works on netcore2.0. You don't experience the problem in .NET Framework because it can find the dependencies with simple names (not assembly qualified) as it has GAC. The custom attributes should always include assembly qualified type names.

**Comment by catester** [comment]
Some references for future rabit-hole researchers:
https://www.red-gate.com/simple-talk/blogs/anatomy-of-a-net-assembly-custom-attribute-encoding/

> As you can see, the full assembly specification of a type is only needed if the type isn’t in the current assembly or mscorlib. Note, however, that the C# compiler currently chooses to fully-qualify mscorlib types anyway.

**Comment by catester** [comment]
It seems you already added a new write option called "OptimizeCustomAttributeSerializedTypeNames" in 857b3134253724ad498ea3e9a37ab522154733a5 few days ago, I just discovered it. However I am using dnlib 3.2 from nuget and I can't compile from github because you converted to VS 2019 and C# 8.0. Anyway I will use the patched dll in the meantime.

**Comment by 0xd4d** [comment]
There's a new nuget version so you don't have to use a patched version.

**Comment by catester** [comment]
Thank you very much, v3.3.0 works correctly out of the box.
