### ISSUE TITLE
Class Problem

### ISSUE THREAD

**Issue by ZKSCSharp** [0xd4d/dnlib#319]
I used the InjectHelper of ConduserEx who used dnLib. I have some error and I don't know why.

Screenshot of the error : 
- https://prnt.sc/puyoo4
- https://prnt.sc/puyp1b
- https://prnt.sc/puyp54

I hope you can help me (I try to make a obfuscator but it's hard, I develop since less than one yaer now)

Thank you for read this and answ me (if you want my discord is Zyks#5650)

Sorry for my bad english I'm french

**Comment by ElektroKill** [comment]
ConfuserEx uses an old version of dnlib (2.1.0.0) and since then the PdbAttributes property has been removed and the ImportResolver is now ImportMapper.

**Comment by 0xd4d** [comment]
@mkaring's ConfuserEx fork for uses the latest dnlib so use that one instead.

**Comment by ZKSCSharp** [comment]
> ConfuserEx uses an old version of dnlib (2.1.0.0) and since then the PdbAttributes property has been removed and the ImportResolver is now ImportMapper.

Ok thank's I juste start to use Dnlib so I don't know all methods

**Comment by ZKSCSharp** [comment]
> @mkaring's ConfuserEx [fork](https://github.com/mkaring/ConfuserEx) uses the latest dnlib so use that one instead.

Thank you for your help !
