### ISSUE TITLE
Make Importer class supporting array field with initialization

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnlib#32]
Hey,
I noticed when I import a type and it contains a static array field with a direct assignment of the values like:
> private static int[] TestArr = new int[]{1,2,3,4,5};

or 

>private static byte[] BArr = new byte[]{0x01,0x02,0x03};

their will occur a problem when imported.
The field gets added but the output assembly is not runnable.

> byte[] expr_06 = new byte[8];
>   RuntimeHelpers.InitializeArray(expr_06, ldtoken());
>   StringDecryption.nigga = expr_06;

![](http://i.imgur.com/gaRxUkd.png)

This is how the produced MSIL looks like.
I am aware of the fact that its possible to import an array field by using the FieldDef and adding it manually, but it would be much more comfortable to improve the importing class of dnlib so the initialization of array fields will be handled automatically without causing trouble with ldtoken OpCodes.

**Comment by bprg** [comment]
I think you need the class.
https://github.com/0xd4d/de4dot/blob/e0dfa64e31f212eeea9008712a084e60da636830/de4dot.code/deobfuscators/InitializedDataCreator.cs

**Comment by 0xd4d** [comment]
The module.Import() methods create a reference to the field/method/etc, it's not modifying the original array creation code. What method were you using?

**Comment by XenocodeRCE** [comment]
Nevermind : http://lifeinhex.com/how-to-inject-byte-array-using-dnlib/

All problem are solved now, thanks :)
