### ISSUE TITLE
How to change version and PublicKeyOrToken in References for dll?

### ISSUE THREAD

**Issue by ias1985** [0xd4d/dnlib#320]
Hello! Could you help me? I have a dll, it has links to other dlls. It is necessary to change the version and publicTokenKey in some of these dlls. I change, but after saving (module.write) I look at the changed dll through dotPeek and see duplication in References (with new version and new publictokenkey, old version and old publictokenkey). My code:
using (ModuleDefMD moduleloc = ModuleDefMD.Load(txtPathToAssembly.Text))
					{
						IEnumerable<AssemblyRef> changedRefs = moduleloc.GetAssemblyRefs().Where(x => ListRefToChange.Exists(y => y.nameAssembly == x.Name));
						foreach (AssemblyRef curRef in changedRefs)
						{
							RefModel assemblyForChanges = ListRefToChange.Find(x => x.nameAssembly.Equals(curRef.Name));
							if (assemblyForChanges != null)
							{
								curRef.Version = new Version(assemblyForChanges.versionAssembly);
								curRef.PublicKeyOrToken = PublicKeyBase.CreatePublicKeyToken(assemblyForChanges.GetPublicKeyTokenAssemblyAsBytes());
							}
						}					moduleloc.Write(System.IO.Path.Combine(InputOutputHelper.GetFullPathToChangedFiles(), moduleloc.Name));
					}
Thanks)

**Comment by 0xd4d** [comment]
You need to provide a minimal repro.

Did you add an assembly resolver? Make sure it resolves to the modified modules not any original modules on disk.
