### ISSUE TITLE
Do resolved references get refactored too?

### ISSUE THREAD

**Issue by tr33s** [0xd4d/dnlib#321]
Assuming the initial DLL (1) is referenced by another DLL (2), and DLL 2 is resolved into the context, does refactoring in DLL 1 also refactor the TypeRef/MemberRef, etc (I think?) in DLL 2.

If this is possible then how does one save the primary DLL and all the referenced DLLs?

**Comment by xsilent007** [comment]
All MemberRef's will be resolved at runtime via their names + signature. So if you change a method's body in DLL1, you don't have to do anything in DLL2.

**Comment by tr33s** [comment]
All I am trying to do is take 2 (or possibly more, with various referencing) DLLs, do some "mapping" programmatically, and be able to save both DLLs with the new refactoring.

**Comment by notsquirr3l** [comment]
As long as you update the references in both it will work perfectly fine

**Comment by 0xd4d** [comment]
You can use `MemberFinder`, it searches for refs in method bodies and custom attributes etc. If you rename a MethodDef, then you should also rename any method refs (MemberRef) in this module and in any other module that references this one.
