### ISSUE TITLE
Referenced Methods

### ISSUE THREAD

**Issue by procfxgen** [0xd4d/dnlib#322]
Hi,
 how to know if a method is used or referenced by others methods ?
 I try to remove unused methods from my executable in order to reduce ilcode size.
Thanks.

**Comment by notsquirr3l** [comment]
This isn't a dnlib specific issue however you can loop over every method and check instruction operands to see if they reference your method such as Call, Callvirt, Ldftn etc

**Comment by 0xd4d** [comment]
There's also reflection so even if you don't find a reference to a method, it could still be used at runtime.

Have you tried https://github.com/mono/linker
