### ISSUE TITLE
Remove code from all methods

### ISSUE THREAD

**Issue by orellabac** [0xd4d/dnlib#325]
I am looking for a way to generate something like REferenceAssemblies from existing assembly.
The idea is that I might get an assembly for which I dont have a licx so I just want to generate an "skeleton" so I can compile the code.
But I cannot find an easy way to replace the body of the methods by throw null bodies. 
As well as removing all private methods and private inner classes
Any recomendations?

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnlib/issues/323 has some code.

And you can't remove everything especially in structs. Roslyn needs to know if a struct has been initialized and if it has GC refs etc.

**Comment by orellabac** [comment]
Wow this is great. That is what I was looking. Also thanks for pointing
that out about structs
