### ISSUE TITLE
Why is there a TryGetTypeDef and a TryGetTypeRef, but no TryGetTypeDefOrRef

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#326]
There're `TryGetTypeDef`, `TryGetTypeRef`, `TryGetTypeDefOrRefSig`, but no `TryGetTypeDefOrRef`
`ToTypeDefOrRef` may new a `TypeSpecUser`

**Comment by 0xd4d** [comment]
Maybe because no-one has needed it. Suggest an API or send a PR.
