### ISSUE TITLE
'dnlib.DotNet.CAArgument' cannot be serialized

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnlib#327]
Hello,

```csharp
[attributes(new byte[]{ 0xd4d, 0x01, 0x02 })]
public void test(){
}
```

```csharp
var myObject = MethodCustomAttributes.ConstructorArguments[0].Value; //type of Object
System.Collections.IEnumerable en = (System.Collections.IEnumerable)myObject;
foreach (var bytes in en) {
   var z = Convert.ToByte(bytes); //System.InvalidCastException : cannot convert 'dnlib.DotNet.CAArgument' to type 'System.IConvertible'
   newarray.Add(z);
}
```

to get the array value i have to call `MethodDef.CustomAttributes[1].GetBlob();` and then sanitize it manually after, 

am I forced to load the assembly using reflection and use methodinfo GetCustomAttribute ? Why isn't this enumerable or even serializable ?

**Comment by 0xd4d** [comment]
Have you tried reading the `dnlib.DotNet.CAArgument.Value` property?

The System.Collections.IEnumerable cast can be changed to an `IList<CAArguments>` cast which should make the for loop easier and let the C# compiler know what list you have.
