### ISSUE TITLE
(Actually for dnSpy) Where are the old releases?

### ISSUE THREAD

**Issue by flarn2006** [0xd4d/dnlib#329]
Sorry to post this on the wrong repository, but I didn't see the Issues tab on dnSpy, or anywhere else to contact you.

Anyway, I can't find the old dnSpy releases on Github. I was looking for the Unity debugger files but all I see is a release from 13 hours ago that doesn't have those. Have you been deleting the old releases for some reason?

**Comment by 0xd4d** [comment]
The old release is always deleted when I release a new one.

You can compile those debugger files yourself https://github.com/0xd4d/dnSpy-Unity-mono
