### ISSUE TITLE
Linux import from Microsoft.NETFramework.ReferenceAssemblies nuget

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnlib#332]
Hello

I would like to implement some kind of way for dnlib to auto download missing framework references
from nuget on Linux systems, so before doing anything i just wanted to discuss about what would be 
acceptable way of implementing this.

My initial idea is to implement 2 new properties into resolver class that would be allow nuget downloading and, nuget cache folder that would probably be on temp by default or some folder in same folder as dnlib
and on Resolve method would add some kind of downloaded to get correct dll and place it in cache folder and resolve it

**Comment by 0xd4d** [comment]
I don't think auto downloading files by dnlib is a good idea. This logic belongs in the application. You can however derive from the default `AssemblyResolver` and perhaps override some methods and then download any files you need?

**Comment by TheProxyRE** [comment]
Okay will try something like that. If i manage to make anything interesting will link it here so other people with similar issues can reuse
