### ISSUE TITLE
Dnlib changes the order of implemented interfaces.

### ISSUE THREAD

**Issue by catalin00** [0xd4d/dnlib#333]
I am trying to open, modify and write an assembly that has some types with implemented interfaces. The order of the interfaces is pretty important for my project. I can check that up until the AssemblyDef.Write() call the order of the interfaces is right. However, after the assembly is written to the disk, I can open it with dnSpy and the order is different. I can even edit the type with dnspy and fix this by dragging the interfaces in the list. (check picture). However, I don't see why dnlib writes the interfaces in the wrong order, or how to fix it.

This is the Interfaces list in Visual Studio
![2020-01-04_104840](https://user-images.githubusercontent.com/19526623/71763066-18b09880-2ee0-11ea-8cdf-9cbc0bc492ea.png)

And this is the result as seen in dnSpy:
![2020-01-04_104925](https://user-images.githubusercontent.com/19526623/71763074-3c73de80-2ee0-11ea-90f2-50b2db86c7cb.png)

![2020-01-04_105013](https://user-images.githubusercontent.com/19526623/71763076-439aec80-2ee0-11ea-85c4-ec46e677b2ef.png)

**Comment by 0xd4d** [comment]
Open the assembly with dnlib and check the order of the interfaces.

**Comment by 0xd4d** [comment]
You can try enabling the `MetadataFlags.RoslynSortInterfaceImpl` metadata option. The itnerfaces table must be sorted.

**Comment by catalin00** [comment]
In my first screenshot, you can see the interfaces list as dnlib shows it (the right, expected order). It stays the same after I open and modify the assembly, and even after I write it. The issue seems to be at writing to disk. Regarding your suggestion, could you please send me a code snippet? (I am not very experienced with dnlib)

**Comment by 0xd4d** [comment]
The interface table must be sorted in a certain way according to the ECMA spec. If your code depends on non-sorted order, it's better to fix your code to not depend on the order of iterfaces.

The option I mentioned above can be changed by updating `ModuleWriterOptions.MetadataOptions.MetadataOptions.Flags`.

**Comment by catalin00** [comment]
Ok, thanks! I will try it out as soon as I get home. I did change the code in the meantime, so now it doesn't depend on the interface order. However, this is an obfuscator, and this was a real-life case where the software owner ran into this problem, so it would be great to be able to fix it and avoid this happening again.

**Comment by 0xd4d** [comment]
Closing this since it seems it's working now.
