### ISSUE TITLE
__arglist parameter in methods.

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#334]
Hello, I am running into an issue with a method having the `__arglist` parameter. I want to insert a call to that method using dnlib.

Here is the method that uses `__arglist`  as a parameter (All of the decompilations are from dnSpy)
![image](https://user-images.githubusercontent.com/37494960/71784516-a1b8f400-2ff4-11ea-8ec8-fa3a7cbd6d1d.png)

Here is a method that calls it generated by the compiler
![image](https://user-images.githubusercontent.com/37494960/71784532-c4e3a380-2ff4-11ea-930c-99db64d2cf3e.png)
![image](https://user-images.githubusercontent.com/37494960/71784538-d927a080-2ff4-11ea-8b25-729bcfc01083.png)

I wrote some simple code to generate a call to the method `AhowArgList` here is the code
![image](https://user-images.githubusercontent.com/37494960/71784565-0b390280-2ff5-11ea-9844-8e11b32d9fe7.png)

Here is the method generated by the code
![image](https://user-images.githubusercontent.com/37494960/71784577-21df5980-2ff5-11ea-8cb9-d32b084646e3.png)
![image](https://user-images.githubusercontent.com/37494960/71784581-2a379480-2ff5-11ea-8fec-fc25f20980f0.png)

The code generated does not work properly, I have noticed that the call opcode has a different operand than the on generated by the compiler. Is there a way I could do the same using dnlib to make my code work?

Here are the files shown and used to reproduce this issue.
[Files.zip](https://github.com/0xd4d/dnlib/files/4023803/Files.zip)

**Comment by 0xd4d** [comment]
A quick look at the pics shows that your code calls the method def but the original code calls a memberref (method ref).

Have you checked the original compiler generated code with dnlib? Just get the method, and get the call. Then check the called MemberRef arg and verify that you generate the same one. Take a close look at the MethodSig property and its CallingConvention/Params/ParamsAfterSentinel properties.

**Comment by ElektroKill** [comment]
Hi, I solved the problem, thanks for your help. My solution was to create a new MethodSig using the constructor and setting its CallingConvention to VarArg and putting all the params into ParamsAfterSentinel. Then I just made a MemeberRef from it and put it as the operand for the call instruction.
