### ISSUE TITLE
Error writing/saving patched assembly

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnlib#335]
How to reproduce the issue:
Load the file below with the latest dnlib:
[Crack-Me2.zip](https://github.com/0xd4d/dnlib/files/4075912/Crack-Me2.zip)
save the file with/without modifying it. then OutOfMemoryException will occur after that.
I need help because i don't understand much about dnlib internal functions. The also error occurs when saving the file with dnspy.

**Comment by 0xd4d** [comment]
It's an obfuscated assembly. Clean it up, especially that big garbage method. Then save it.
