### ISSUE TITLE
Add byte[] in Constants for FieldDef

### ISSUE THREAD

**Issue by Mageland29** [0xd4d/dnlib#337]
Hello i contact you because i have an suggestion to ask you, is to add in the ConstantUser for the FieldDef to add the byte array, because actualy you can only add that
![rgergeg](https://user-images.githubusercontent.com/31138970/73185692-cea58600-411e-11ea-9269-a7a78aae6288.PNG)

if we add byte array he write null

**Comment by 0xd4d** [comment]
You can't add a byte array, only those types you show in the pic above are supported according to the ECMA 335 spec, partition II, 22.9. Here's the relevant text:

> Type shall be exactly one of: ELEMENT_TYPE_BOOLEAN, ELEMENT_TYPE_CHAR, ELEMENT_TYPE_I1,
ELEMENT_TYPE_U1, ELEMENT_TYPE_I2, ELEMENT_TYPE_U2, ELEMENT_TYPE_I4, ELEMENT_TYPE_U4,
ELEMENT_TYPE_I8, ELEMENT_TYPE_U8, ELEMENT_TYPE_R4, ELEMENT_TYPE_R8, or
ELEMENT_TYPE_STRING; or ELEMENT_TYPE_CLASS with a Value of zero (§23.1.16) [ERROR]
