### ISSUE TITLE
Problem adding System.Runtime methods into .NET Core applications

### ISSUE THREAD

**Issue by juanal98** [0xd4d/dnlib#338]
Good, first of all, thank you for your great work.

I put you in context, the application I charge with dnlib is `.NET Core 3.1.`

I try to add a simple instruction, which is: `Convert.ToInt32`

Previously I have configured the Resolver to load the correct NETCore libraries, and not use the GAC for resolution, that is, if I am not mistaken the dependencies are being loaded correctly.

So, where is the problem:

`module.CorLibTypes` is assigned the correct library, in the case of this application of `NETCore 3.1`, it is `System.Runtime, Version = 4.2.2.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a`:

![descarga](https://user-images.githubusercontent.com/32484496/73614538-54826f00-4600-11ea-8dcc-c3a65ef445d9.png)

That's fine, since it matches the reference the application uses:

![descarga (1)](https://user-images.githubusercontent.com/32484496/73614606-f609c080-4600-11ea-9cef-6a5b4444b407.png)

Here comes the problem, I try to add a method of the `System.Convert` class, specifically `Convert.ToInt32()`

In this version, this class is not found in `System.Runtime`, if not, it is found in `System.Runtime.Extensions`:

![descarga (2)](https://user-images.githubusercontent.com/32484496/73614698-c4452980-4601-11ea-99ac-4d0292b6c558.png)

So, I am not able to import correctly in any way.

For example, `System.String`, `System.Char` ... are in `System.Runtime`, so I can inject `char.ToString()`; without any problem.

This is the code I use to import:
![descarga (3)](https://user-images.githubusercontent.com/32484496/73614790-8dbbde80-4602-11ea-9b44-14c3c5c7c73a.png)

Logically, it doesn't work, because this CorLibTypes is looking for the Convert class, in `System.Runtime`, and there it isn't.

For example, using the code above but obtaining a class that is found in `System.Runtime`, it works perfectly. For example `int.Parse()`.

So how do you think a class like `Convert` should be imported, which is outside of `System.Runtime`?
With the NET Framework applications this does not happen, because everything is in the same place, but in NET Core it is as separate, what do you think could be the solution to make it work?

Thank you for your time, patience and effort, best regards.

**Comment by 0xd4d** [comment]
Sounds like you're resolving runtime assemblies. You should resolve reference assemblies.

- `C:\Program Files\dotnet\packs`
- https://www.nuget.org/packages/NETStandard.Library/

**Comment by juanal98** [comment]
Hello again, thanks for your reply,

I make the resolution with the libraries you told me, download all the nuget versions to check it further, I explain what I think happens:

Here I have all the net core libraries:

![descarga (4)](https://user-images.githubusercontent.com/32484496/73672001-64578d00-46ac-11ea-9102-a1e493f04b1b.png)

If you inspect the Runtime, the Convert class is not found:

![descarga (5)](https://user-images.githubusercontent.com/32484496/73672293-e8117980-46ac-11ea-97ec-1f1ac9084db2.png)

So, this is found in Extensions,

![descarga (6)](https://user-images.githubusercontent.com/32484496/73672710-aa612080-46ad-11ea-8c2b-30c48ce56d6d.png)

Do you think it's the wrong runtime library and I'm wrong?

I say this because it also seems very strange to me, but if I check System.Runtime in `C:\Program Files\ dotnet\packs`, https://www.nuget.org/packages/Microsoft.NETCore.App/

The exact same thing happens, `Convert` is out (in `Extensions`)

If the library is correct, what do you think to solve it? Because `CorLibTypes` loads `System.Runtime` by default, but what should be done to be able to resolve `Convert` that is in `extensions`?

The problem I see with this is that, for example, if my original application does not use `Convert`, the Extensions library is not a reference (because it does not need it), that is, it could not even be resolved as a reference to the assembly ( because that is not it). Should we inject `System.Runtime.Extensions` as a reference and then resolve `Convert`?

I'm really sorry for bothering you, I am still making a silly mistake, but from what I see it's not like mscorlib (it's all there) here is separate and `System.Runtime` doesn't work to solve all classes, such as `Convert.`

Thank you,

**Comment by 0xd4d** [comment]
You should reference the correct assembly according to the reference assemblies. If that class is in the Extensions assembly, then use it.

**Comment by juanal98** [comment]
But how do I know which is the correct assembly? there many assemblies with the same name, version and token, but their content is different, how can I know which one to resolve and how do I resolve it in that case?

**Comment by 0xd4d** [comment]
You should do what the C# compiler does. It gets a list of assemblies. When you reference a class, it looks up that class from all the assemblies it knows about (i.e., the reference assemblies). If it finds multiple classes with the same name, it reports an error.

**Comment by juanal98** [comment]
Ok, thank you very much for the information, I will implement something to solve it.

Thank you for your time, and congratulations on your amazing work.
