### ISSUE TITLE
how to add/remove win32 native resource ?

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#339]
I recently added a win32 resource using Winapi in .NET. But it didn't support lowercase letters & unicode and I accidentally saw it it can possible add native resource with dnlib in github. Can you explain a little example of how to do this? I only found it Find, Root ... sorry my english

**Comment by 0xd4d** [comment]
It only supports raw blobs of data, so you have to create the data and then add it to the win32 resources.

I think there's even a .NET library that can do this, I don't remember the name of it.

**Comment by Ambraham1544** [comment]
If you remember that, could you answer me here?
I really need it...

**Comment by CreateAndInject** [comment]
@0xd4d Do you mean https://github.com/resourcelib/resourcelib ?

**Comment by 0xd4d** [comment]
Could be, it's written in C#.

**Comment by Ambraham1544** [comment]
I'll be waiting for your reply...
