### ISSUE TITLE
Add Tag property for types/members.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#340]
Now, only ModuleDef has a Tag property, can you add it for all types/members?

**Comment by 0xd4d** [comment]
That will add another 4 or 8 bytes to every member so will use more memory.

**Comment by 0xd4d** [comment]
This is not something I plan on adding. You can use [ConditionalWeakTable<TKey,TValue> Class](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2) or a dictionary if you need to store extra state.
