### ISSUE TITLE
PDB files are not created

### ISSUE THREAD

**Issue by ias1985** [0xd4d/dnlib#341]
Hello! 
I'm trying to create pdf files, but it is not created on disk.
using (ModuleDefMD moduleloc = ModuleDefMD.Load(System.IO.Path.Combine(directoryPathForAssemblies, nameOfSelectedFile)))
{....
IEnumerable<AssemblyRef> changedRefs = moduleloc.GetAssemblyRefs();
foreach (AssemblyRef curRef in changedRefs)
{
curRef.Version = new Version(assemblyForChanges.versionAssembly);
							curRef.PublicKeyOrToken = PublicKeyBase.CreatePublicKeyToken(assemblyForChanges.GetPublicKeyTokenAssemblyAsBytes());
}
// Create writer options
					var opts = new ModuleWriterOptions(moduleloc);

					if (param.IsPDBCreate)
					{
						opts.WritePdb = true;
						opts.PdbFileName = @"C:\out2.pdb";
	
						//opts.PdbFileName = System.IO.Path.Combine(InputOutputHelper.GetFullPathToChangedFiles(),$"{moduleloc.Assembly.Name}.pdb");
					}

					// Open or create the strong name key
					var signatureKey = new StrongNameKey(InputOutputHelper.GetFullPathToKeyFile());

					// This method will initialize the required properties
					opts.InitializeStrongNameSigning(moduleloc, signatureKey);
					moduleloc.Write(System.IO.Path.Combine(InputOutputHelper.GetFullPathToChangedFiles(), moduleloc.Name), opts);
}

Thank you!

**Comment by 0xd4d** [comment]
Does the file already have a PDB file? If it doesn't have a PDB file, you have to create all the stuff that's part of a PDB file before saving it.

**Comment by ias1985** [comment]
It doesn't have a PDB file. Could you give me some examples, please?

**Comment by 0xd4d** [comment]
What are you trying to do? The data in a PDB file are created by compilers. If you don't have the original PDB file you have to somehow figure out what the compiler would add to the PDB and do it yourself.

**Comment by ias1985** [comment]
I have a DLL file with links(references) to foreign libraries. I change the dll versions(curRef.Version = new Version(assemblyForChanges.versionAssembly);) in the links and save (moduleloc.Write (System.IO.Path.Combine (InputOutputHelper.GetFullPathToChangedFiles (), moduleloc.Name), opts);) this dll file. And I want this file to be created with a PDB file. I use the parameters var opts = new ModuleWriterOptions (moduleloc); and flag opts.WritePdb = true; but the PDB file is not created. Could you give an example, how can I do this, please? Or is it impossible to do?

**Comment by 0xd4d** [comment]
I suggest you check the Roslyn source code to get an idea of what you need to do to create PDB files from scratch. dnlib can't automatically create this stuff.
