### ISSUE TITLE
How to edit Byte array ??

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#344]
I'd like to edit byte array to compiled dll & exe
how can i ?
I know replace string like this

Dim enm As IEnumerator(Of Instruction) = Nothing
                    Try
                        enm = mdf.Body.Instructions.GetEnumerator
                        Do While enm.MoveNext
                            Dim current As Instruction = enm.Current
                            If current.OpCode.Code = Code.Ldstr Then
                                Dim strings As String = current.Operand.ToString
                                If strings = "@" Then current.Operand = "Hello"
                           End If
                        Loop
                    Catch ex As Exception
                    End Try
but i don't know how to replace byte array
can you teach me please ??

**Comment by 0xd4d** [comment]
There's a `For Each` loop you can use above. No need to use `GetEnumerator()`.

Compile the code you want then look at the IL code and you'll know what to do.

**Comment by Ambraham1544** [comment]
Oh, thanks for reply.
but i need some example code..
can you provide it please ?

**Comment by 0xd4d** [comment]
I've explained how you can get the IL above. You have to write the code yourself.
