### ISSUE TITLE
Is there any problem with MaxStack?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#347]
https://github.com/dotnet/runtime/blob/f80a5147ef7662c3238275568c9dad7655a9684f/src/coreclr/src/inc/corinfo.h#L1180

I notice maxStack is uint(4 bytes) in .Net, but dnlib is ushort(2 bytes), is there any problem?

**Comment by ElektroKill** [comment]
Hi, I maybe wrong but I am pretty sure that before .net 4.0 in .net 2.0 the maxStack was ushort.

**Comment by 0xd4d** [comment]
It's always been 16 bits. What @CreateAndInject found is the internal method structure, not the serialized (in metadata) header.

https://github.com/dotnet/runtime/blob/master/src/coreclr/src/inc/corhdr.h#L1247
