### ISSUE TITLE
Question on comparing array sigs

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnlib#35]
I'm not sure if thats an issue, but anyway I'd like to raise it here.

I've such a method in some class (as seen in SAE for example):
myMeth1(Double[0...,0...], Double[]&&): Boolean

Now, there is a code in some assembly that calls this method 
and the 1st parameter is declared as follows:

http://prntscr.com/7gj2sd

now, taking into account how dnlib compares the arraysig, the lookup fails....

module: SigComparer.cs
code:

```c#
namespace dnlib.DotNet {
......

public bool Equals(TypeSig a, TypeSig b) {
{
...........
				case ElementType.Array:
					ArraySig ara = a as ArraySig, arb = b as ArraySig;
					result = ara.Rank == arb.Rank &&
							Equals(ara.Sizes, arb.Sizes) &&
Equals(ara.LowerBounds, arb.LowerBounds) &&
						Equals(a.Next, b.Next);
					break;

}
```

here is an example of the comparing code:
bool flag6 = !default(SigComparer).Equals(methodSig.Params[i], babelMethodRef.Parameters[i].Type);

I've looked around, there is interesting arcticle about this case:

Array lower bounds can be only '0'
https://msdn.microsoft.com/en-us/library/ttw7c10x%28v=vs.90%29.aspx

So the question is: does it make sense to relax the LowerBounds comparing way?
maybe it'll make sense to check if one side has 0 lower bounds and another no, then the result still may be "equal"?

Thanks

**Comment by 0xd4d** [comment]
I wrote some code that tests this and peverify complains if caller's method signature doesn't include the 0 lower bounds that matches the called method's 0 lower bounds.

The reason that the code you're investigating might work is that it seems from your info above that it's a Babel.NET obfuscated assembly. The obfuscator resolves the correct method and then creates the correct code.

```text
C:\arytest>peverify theexe.exe

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\arytest\theexe.exe : main.Start::Method][offset 0x00000001] Unable to resolve token.
1 Error(s) Verifying theexe.exe

C:\arytest>theexe.exe

Unhandled Exception: System.MissingMethodException: Method not found: 'Int32 ns.Class1.Method(Double[,])'.
   at main.Start.Method()
```
