### ISSUE TITLE
Expose SymbolSequencePoint in MethodDef

### ISSUE THREAD

**Issue by damageboy** [0xd4d/dnlib#350]
I don't mind doing this myself, I'm just opening this issue for discussion purposes.

Right now, it is quite easy to get the sequence points for an `Instruction` through the expose `SequencePoint` property that dnlib is very thoughtfully providing while going over the body's instructions.

I have not found a decent way, to get to the `SymbolSequencePoint` definition point of the function in any reasonable way as a dnlib user, in what looks like a weird omission at the API level.

Does it make sense to add the `SymbolSequencePoint` as a property to the method def and populate it, but like the individual instruction, sequence points get populated while reading the PDB?

It should be a very simple fix, I just wanted to make sure I'm not missing something obvious as to how the API is meant to be used...

**Comment by 0xd4d** [comment]
`SequencePoint` is `SymbolSequencePoint` without an `Offset` field (it's part of `Instruction`), so there's nothing new to expose.

**Comment by damageboy** [comment]
Sorry, I'm probably not clear enough.
What I meant is that I'd like to get a `SequencePoint` for the method definition itself, rather than for the instructions. To that end, I'd like to add a `SequencePoint` to the `MethodDef`..

Am I making more sense now, or not yet :)?

**Comment by 0xd4d** [comment]
I don't think that info is part of PDB files. The sequence points are for statements only, so the best you can get is the start and end statement in the method body.

**Comment by damageboy** [comment]
Thanks.
I've been debugging dnlib and basically came to that conclusion about an hour ago.
You re-affirmation of this seals the deal.
Thanks!
