### ISSUE TITLE
add "DebugType full" in dnlib.csproj

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#352]
by default, when "Configuration" is "Debug", "DebugType" is "full" in Non-SDK-style. but in SDK-style csproj, "DebugType" is "portable". so when i run a program without debugger, i can't get line number when exception is thrown by dnlib.

adding these may help.

```
<PropertyGroup Condition="'$(Configuration)'=='Debug'">
  <DebugType>full</DebugType>
</PropertyGroup>
```

**Comment by 0xd4d** [comment]
Portable PDBs should be used nowadays. They're smaller too, and cross platform.

If you don't get line numbers or anything, it probably means you're using an old .NET Framework, probably < 4.7.1.

**Comment by 0xd4d** [comment]
`Runtime – Support for Portable PDBs`: https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7-1/

**Comment by 0xd4d** [comment]
You need .NET Framework 4.7.2 or later to get useful stack traces (or .NET Core), see https://github.com/microsoft/dotnet/blob/master/releases/net471/KnownIssues/517815-BCL%20Stack%20traces%20are%20missing%20source%20information%20for%20frames%20with%20debug%20information%20in%20the%20Portable%20PDB%20format.md

**Comment by wwh1004** [comment]
my .net version is v4.7.2 and the target framework is also v4.7.2. but i still can't get line number.
eg. i use dnlib to load a file which not exists.
```
using (ModuleDefMD moduleDef = ModuleDefMD.Load("a.dll")) { }
```
![Snipaste_2020-04-15_22-35-06](https://user-images.githubusercontent.com/27536652/79349954-6e79ef80-7f69-11ea-848d-78b226b99e5c.png)

**Comment by 0xd4d** [comment]
Try upgrading to .NET Framework 4.8. It worked for me when I used the nuget package + downloaded the symbols and placed them next to dnlib.dll.

**Comment by 0xd4d** [comment]
Or try .NET Core 3.1. .NET Framework is a dead end.
