### ISSUE TITLE
Just a stupid question

### ISSUE THREAD

**Issue by peteringemann** [0xd4d/dnlib#353]
hi there,
so just a disclaimer: i'm haven't worked hat much with IL coding in general.
but: i have this method that i want to replace. i've cleared the body and inserted like 50 new instructions. instructions i've got using dnSpy, edited the body and set the language to IL. 
seems to be working okay although it was a hassle figuring out how to make references to both internal fields, external fields, method calls etc. it would be nice to have pinned out all types of references.

anyways. i've come far and it's almost possible for me to save the new dll.
my question is: is it in anyway possible to get what line in my C# (or instruction index) code that actually contains the code that makes the save process throw an exception? i have like 50 instructions and it would be nice if the exception was clear about what instruction index that crash.

**Comment by 0xd4d** [comment]
If you have the PDB, you can get the line number. Many instructions have a SequencePoint that contains the line number and filename.

**Comment by peteringemann** [comment]
> 
> 
> If you have the PDB, you can get the line number. 

I don't have the pdb - this is just a dll I got that I am practicing on. I take that I can't create the PDB before the dll has been written. 
And how do I map a pdb to the exception and line number? Am I right if you're talking about setting the sequencepoint when changing the dll and then look for the specific sequence in the exception? 

Sorry for asking - I'm pretty much a n00b.

**Comment by 0xd4d** [comment]
The filenames and line numbers are stored in the PDB file so if you don't have it, you will never be able to get the line numbers and filenames.

**Comment by peteringemann** [comment]
> 
> 
> The filenames and line numbers are stored in the PDB file so if you don't have it, you will never be able to get the line numbers and filenames.

Oh. I get it now - but the PDB will not help me (if I had it). I pretty much replaced the entire method body and now I get and 'Operand is not a Double' error when I wanna save (using dnlib). I pretty much used dnSpy to rewrite the method using C#, switched to IL and used dnlib to replace the method using the IL code from dnSpy (and then I get the operand is not a double). But fair enough. I've been googling and it seems like almost impossible to debug into this. I think I'll just leave it then.

**Comment by 0xd4d** [comment]
It means that the operand is not a 64-bit floating point number, or a `System.Double`.  Check your `ldc.r8` instructions and make sure you initialize `Operand` to a double, not a float or an integer.

**Comment by 0xd4d** [comment]
Eg. change `instr.Operand = 1` to `instr.Operand = 1.0` or `instr.Operand = (double)1`

**Comment by peteringemann** [comment]
This makes totally sense. And it works. I've spend days on this. I would never have thought about casting the operand - I just thought it was text and the IL compiler would eventually cast it because it's so fundamental coding.

I don't know if you wanna keep helping but a new error:
'Local/arg index doesn't fit in a Byte. Use the longer ldloc/ldarg/stloc/starg instruction'.
I understand what the error says but is because I call a method and parse my args and those args doesn't fit? I am not sure I get what triggers this error (and especially now that I don't get any IL_#### line)

**Comment by 0xd4d** [comment]
There are shorter instructions that only take a byte as an argument. They end in `_S`, so don't use them unless you know the operand fits. You should read the IL docs

https://docs.microsoft.com/dotnet/api/system.reflection.emit.opcodes.ldarg_s

Instead of `Ldarg_S` use `Ldarg` and then call `method.Body.OptimizeBranches()` to optimize them.
