### ISSUE TITLE
Generic class/interface parameter variance

### ISSUE THREAD

**Issue by hailstorm75** [0xd4d/dnlib#355]
Is it possible to get the variance of generic parameters of a given class?

```csharp
public class Gen<out T, in S>
{
  ...
}
```

If so, how?
If not, It'd be an awesome feature to have!

I'm using **dnlib** for reading assembly types and generating documentation.

**Comment by 0xd4d** [comment]
`GenericParam.Flags` is probably what you want. See also `GenericParam.GenericParamConstraints`.

**Comment by hailstorm75** [comment]
Thank you, that did the trick
