### ISSUE TITLE
About Dnlib Writer

### ISSUE THREAD

**Issue by GabTeix** [0xd4d/dnlib#357]
Hello, I saw that there's some tools as Detect it easy (die) and they can get the strings the assembly if they're encrypted, I don't know how exactly they do it but they get.
So I tried to write the file without NativeModuleWriteOptions and the same flags as ModuleWriteOptions (flag that I use -> MetadataFlags.PreserveRids) and the die can't get the strings now.

I don't why this but it happend, I think it's about metadata.

With this writer die get the strings encrypted 
![image](https://user-images.githubusercontent.com/46636236/80883756-79d05900-8c93-11ea-8a9e-db8dec4e0ae5.png)
![image](https://user-images.githubusercontent.com/46636236/80884676-b8661380-8c93-11ea-9fef-3093e28491db.png)

But when I change to this, it gets the strings in plaintext anyways (if I don't use decoder call it gets too)

![image](https://user-images.githubusercontent.com/46636236/80885715-0418bd00-8c94-11ea-8579-aedf5ea8b9a4.png)
![image](https://user-images.githubusercontent.com/46636236/80886322-2e6a7a80-8c94-11ea-8b07-33fc4b3edc0e.png)

To get the strings from die you just need to go here
![image](https://user-images.githubusercontent.com/46636236/80886626-43470e00-8c94-11ea-9407-89c9ee83030c.png)

**Comment by 0xd4d** [comment]
You disabled the option that re-uses the old locations to store the new data (if it fits). So you end up with the original strings + new strings in two different locations.

**Comment by GabTeix** [comment]
what option do you mean?

if it is that, it's not working
![image](https://user-images.githubusercontent.com/46636236/81444384-674f9700-914d-11ea-9cfc-a83c087d1eb8.png)

**Comment by 0xd4d** [comment]
It re-uses the old locations if the data fits.

**Comment by GabTeix** [comment]
if the data doesn't fit will it mantain the old string and a encrypted string will go to another location? because if don't, it's not working and the old strings still are in the hex.

but if it does, I'm with the same question, how to erase this old strings?

**Comment by 0xd4d** [comment]
Why are you even using NativeModuleWriter? It's for mixed mode assemblies and they're very rare.

The metadata has a FileOffset/size, and so do other things. You can use that to overwrite the old stuff with 0s. Just make sure you don't overwrite the new data.

**Comment by GabTeix** [comment]
Ok thanks for the answer, I'll figure out what I'll do
