### ISSUE TITLE
How to add <T>

### ISSUE THREAD

**Issue by peteringemann** [0xd4d/dnlib#359]
Hi there,
The following code is from ILDASM

```
.method public instance !T  TestMethod() cil managed
{
  // Code size       10 (0xa)
  .maxstack  1
  .locals init ([0] !T TestMethod,
           [1] !T myString)
  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  call       instance !0 class ConsoleApp1.TestClass`1<!T>::get_DefaultValue()
  IL_0007:  stloc.1
  IL_0008:  ldloc.0
  IL_0009:  ret
} // end of method TestClass`1::TestMethod
```

I am trying to write this using dnlib - Line IL_0002 is giving me a headache.
I can easily grab the get_DefaultValue() as a method but that doesn't give me the <!T> at the end of the TestClass. Any ideas on how to get the <!T>?

/ p

**Comment by 0xd4d** [comment]
Have you loaded the method in dnlib and had a look at the actual instructions? A debugger's watch window is perfect for this.

**Comment by peteringemann** [comment]
Hi,
Thanks for answering. I have to say that I am 100% sure I am doing this wrong. 

This is the Local window:

![dnlib-code](https://user-images.githubusercontent.com/46843486/82838480-a8c19f80-9ecc-11ea-8eb5-fe164b8a43a4.png)

The selected line is injected by me using this operand code

`Dim OP_Testmethod = myModule.Find("ConsoleApp1.TestClass`1", True).FindMethod("get_DefaultValue")`

The next line is the actual one with the <T> that I need to be able to write.

**Comment by peteringemann** [comment]
It's a rather cryptic answer. 
But I guess you're referring to comparing operand IL0002 to operand IL0007.
So I browsed through the declaring types in the Locals windows and for ConsoleApp1.TestClass'1 the type is dnlib.DotNet.TypeDef

And as for ConsoleApp1.TestClass'1<T> the declaring type is dnlib.DotNet.TypeSpecMD

So obviously they are different. The question is how do I fetch the TestClass as a TypeSpecMD type and attach the method?

I've tried to use myModule.ResolveTypeSpec and used the rid I found looking into IL0002 operand but it just returns <!0> instead of <T>

I have no clue what I am doing, what I am suppose to do and I am considering abandon ship and just leave it :)

**Comment by 0xd4d** [comment]
This is how you can use the locals window to see what you need to do.

Load the method and get the instruction

Operand is a `MemberRefMD` and if you expand it and check its fields, you'll see

- `class` is a `TypeSpecMD` and its `typeSig` field is a `GenericInstSig`
- `name` is `"get_DefaultValue"`
- `signature` is a `MethodSig` with `HasThis` flag set (it's an instance method, not a static method) and `retType` is a `GenericVar` with `number` == `0`.


- `typeSig.genericArgs` has 1 elem and it's a `GenericVar` with `number` set to `0`.
- `typeSig.genericType` is a `ClassSig` since `TestClass` is a class and not a struct (use `ValueSig` if it's a value type)
- `ClassSig`'s `typeDefOrRef` is the `TestClass` type definition

I used that info to create a member ref, see below. It's in C#

```C#
using System;
using System.Linq;
using dnlib.DotNet;
using dnlib.DotNet.Emit;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var module = ModuleDefMD.Load(typeof(Program).Module))
            {
                var type = module.FindReflection("ConsoleApp3.TestClass`1") ?? throw new InvalidOperationException();
                var method = type.FindMethod("M") ?? throw new InvalidOperationException();
                var instrs = method.Body.Instructions;

                var @class = new TypeSpecUser(new GenericInstSig(new ClassSig(type), new GenericVar(0)));
                var msig = MethodSig.CreateInstance(new GenericVar(0));
                var memberRef = new MemberRefUser(module, "get_DefaultValue", msig, @class);

                var instrMethod = (IMemberRef)instrs.First(a => a.OpCode.Code == Code.Call).Operand;
                bool b = new SigComparer().Equals(instrMethod, memberRef);
                if (!b)
                    throw new InvalidOperationException("They should be equal");
            }
        }
    }

    class TestClass<T>
    {
        public T DefaultValue => default(T);

        public void M()
        {
            _ = DefaultValue;
        }
    }
}
```

**Comment by peteringemann** [comment]
Just wanna share my solution: 

The operand code block:

...getting the get_Default
`Method operand_getDefaultValue = myModule.Find("csharpConsoleApp2.TestClass'1", true).FindMethod("get_DefaultValue");`

getting generic T to be used as operand
```
var var1 = myModule.FindReflection("csharpConsoleApp2.TestClass`1");
var genericT = new TypeSpecUser(new GenericVar(0));
method.Body.Variables.Add(new Local(genericT.ToTypeSig(), "AnotherValue"));
```


then putting it all together
```
instructions.Insert(i, new Instruction
{
    OpCode = OpCodes.Call,
    Operand = operand_getDefaultValue
});
instructions.Insert(i, new Instruction
{
    OpCode = OpCodes.Stloc,
    Operand = method.Body.Variables[0]
});
```
