### ISSUE TITLE
How to get MethodDefs of interface method?

### ISSUE THREAD

**Issue by xxCherry** [0xd4d/dnlib#363]
Tried this, but it doesnt seem to be work.
Throwing NullReferenceException.

`foreach (var @interface in oTypeDef.Interfaces)
{
    var type = @interface.Interface.ResolveTypeDef();
    var methods = type.Methods;
}`

**Comment by xxCherry** [comment]
Okay, type is null, then how i can get methods of interface?

**Comment by CreateAndInject** [comment]
var module = ModuleDefMD.Load(file, ModuleDef.CreateModuleContext());

**Comment by xxCherry** [comment]
?

**Comment by xxCherry** [comment]
It can't ResolveTypeDef not like they aren't exist.

**Comment by CreateAndInject** [comment]
I can't understand your english.
not like?
aren't exist? doesn't exist?

**Comment by xxCherry** [comment]
I meant that ResolveTypeDef returns null but it's not mean type doesn't exist because if i try to get name from @interface.Interface it will work.
So I ask how to get type of an interface to get its MethodDefs.

**Comment by CreateAndInject** [comment]
If the file which define this interface exists in the same folder:
var module = ModuleDefMD.Load(file, ModuleDef.CreateModuleContext());

**Comment by xxCherry** [comment]
Okay, what next?

**Comment by CreateAndInject** [comment]
No any next.
If you do it, ResolveTypeDef should not be null

**Comment by xxCherry** [comment]
No, it doesnt.

**Comment by CreateAndInject** [comment]
What's your whole code?

**Comment by xxCherry** [comment]
`var module = ModuleDefMD.Load(filePath, ModuleDef.CreateModuleContext());
      if (oTypeDef.HasInterfaces)
			{
				foreach (var @interface in oTypeDef.Interfaces)
				{
					  Console.WriteLine($"Name: {@interface.Interface.Name} HasInterfaces: {originalTypeDef.HasInterfaces}");
					  var type = @interface.Interface.ResolveTypeDef();
					  Console.WriteLine(type.Name);
					  var methods = type.Methods;
					}
				}
			}`

**Comment by CreateAndInject** [comment]
I don't know what to say....
You don't use `module` at all!
var module = ModuleDefMD.Load(filePath, ModuleDef.CreateModuleContext());
var oTypeDef = module.FindNormal(...);
The module which define `oTypeDef` should load with context

**Comment by xxCherry** [comment]
Still

**Comment by xxCherry** [comment]
Okay, ill try to figure out it myself.
