### ISSUE TITLE
Implementation Type Changing

### ISSUE THREAD

**Issue by xxCherry** [0xd4d/dnlib#365]
Let's say i have this method declaration => 
```System.Int32 System.IComparable`1<Dummy.SomeClass>::CompareTo(Dummy.SomeClass)```
How can i change `Dummy.SomeClass` to for example `Test.SomeClass` by using `typeDef.Overrides`.

**Comment by 0xd4d** [comment]
Sounds like it's the same kind of issue as https://github.com/0xd4d/dnlib/issues/359 . Just let the C# compiler generate the code, have a look at it in the locals window etc (see linked issue).

**Comment by xxCherry** [comment]
Okay, i'll try.

**Comment by xxCherry** [comment]
I figured out.
