### ISSUE TITLE
Support for custom CIL instructions

### ISSUE THREAD

**Issue by alexrp** [0xd4d/dnlib#367]
Hi,

For a project I'm currently working on, I need to be able to insert custom CIL instructions into a method body (ones that are understood by the runtime I'm targeting). Basically, I just want to be able to provide dnlib with custom `OpCode` instances that inform it about how to decode/encode these instructions, calculate stack usage and control flow, etc.

From what I can gather looking at the source, what would need to happen for this to be possible is:

* `OpCode` would need to be made extensible in some form (probably just a public constructor).
* There would need to be some place in the API for registering custom `OpCode` instances.
* `MethodBodyReaderBase` and a few other places need to be made aware about the experimental opcode range (`0xf0`..`0xfb`).

There may of course be other required changes that I'm not aware of, but I think that's the gist of it.

Would a patch for this be welcome? If so, what would be an acceptable design for this?

**Comment by 0xd4d** [comment]
>     * `OpCode` would need to be made extensible in some form (probably just a public constructor).
>     * There would need to be some place in the API for registering custom `OpCode` instances.
>     * `MethodBodyReaderBase` and a few other places need to be made aware about the experimental opcode range (`0xf0`..`0xfb`).

Why do they need to be updated? They should just work assuming you don't create new operand types.

> 
> 
> There may of course be other required changes that I'm not aware of, but I think that's the gist of it.
> 
> Would a patch for this be welcome? If so, what would be an acceptable design for this?

Since this isn't part of the ECMA standard, if the PR changes too much or adds more OpCode tables, then it probably won't be accepted. I think it only needs to make the `OpCode` ctor public, and if that's the only change (or only a few smaller more changes) then it will probably be accepted.

**Comment by alexrp** [comment]
> Why do they need to be updated? They should just work assuming you don't create new operand types.

See e.g. here: https://github.com/0xd4d/dnlib/blob/2f8ce28ab3f8a3f90191ec0537c4aeb75837db14/src/DotNet/Emit/MethodBodyReaderBase.cs#L219-L224

> or adds more OpCode tables

I don't think the custom opcodes should be added to dnlib itself; that definitely seems out of scope. But it does seem that there needs to be a way to register `OpCode` instances with dnlib prior to reading a method body.

**Comment by 0xd4d** [comment]
We could add a method to `OpCodes` to register an experimental table (`0xF0`-`0xFB`), and a method to return it.

`ReadOpCode()` and `ToOpCode()` would need to be updated.

Does that sound good? If so, would you like to send a PR?

**Comment by alexrp** [comment]
> Does that sound good?

Wouldn't it make more sense to somehow register the custom opcodes on something like the `ModuleContext` used to load such modules so there's no need for global synchronization if one intends to load regular modules as well?

> If so, would you like to send a PR?

Sure.

**Comment by 0xd4d** [comment]
> Wouldn't it make more sense to somehow register the custom opcodes on something like the `ModuleContext` used to load such modules so there's no need for global synchronization if one intends to load regular modules as well?

`ToOpCode()` wouldn't work since it's just an extension method. But maybe it's acceptable?

**Comment by alexrp** [comment]
Ah, right... perhaps a new overload taking a `ModuleContext` parameter? So the current method only looks through the standard opcodes, and the new overload would look through custom opcodes on the context (if any).

**Comment by 0xd4d** [comment]
Yes, that would work.

**Comment by alexrp** [comment]
One thing I'm not sure about is how to represent the collection of custom opcodes on the `ModuleContext`. A `Dictionary<Code, OpCode>` seems like the obvious thing, but that leaves the possibility for a user to accidentally pass in a wrong `Code` value as the key.

Any thoughts?

**Comment by 0xd4d** [comment]
I would expect that if you want to define your own custom opcodes, you'd create a table with 256 values in it so an array should be enough. `0xF0-0xFB` can then be overridden to use that array (if it's not null).

**Comment by alexrp** [comment]
One more question: What would be the best way to flow a `ModuleContext` through to a `MethodBodyReaderBase` without breaking public API?

**Comment by 0xd4d** [comment]
Add new overloads

- MethodBodyReader: an extra contex arg, pass it to base
- CreateCilBody: two of these call CreateCilBody() and these two methods need to get a new overload with a contex arg

The `opResolver` is usually a module but we can't assume it.
