### ISSUE TITLE
Inserting a metadata heap before the tables heap

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#369]
Hello,

I am pretty sure that in dnlib versions prior to 3.x it was possible to add custom heaps before the tables heap. Would it be possible to bring back this functionality to the newer versions of dnlib?

Thanks in advance.

**Comment by 0xd4d** [comment]
See `ModuleWriterOptions.MetadataOptions`: `CustomHeaps` and `MetadataHeapsAdded`

**Comment by ElektroKill** [comment]
Hello, I saw CustomHeaps but they are added at the end of all the heaps like the old 'OtherHeapsEnd'. I need something to replace the old 'OtherHeaps' which were inserted before the #~ heap.

**Comment by 0xd4d** [comment]
That's what the `MetadataHeapsAdded` event is for. You can sort the list any way you want.

**Comment by ElektroKill** [comment]
Oh ok, I will try it out soon and will let you know if any problems arise.

**Comment by ElektroKill** [comment]
I figured it out. Thanks!
