### ISSUE TITLE
dnlib.DotNet.Writer.ModuleWriterException: A type was removed that is still referenced by this module.

### ISSUE THREAD

**Issue by MulleDK19** [0xd4d/dnlib#37]
Hi.

I'm trying to use dnlib to remove everything from an existing C++/CLI assembly.
However, when I try to write, I get a ModuleWriterException, saying a type is still referenced.

It seems to me that if I remove all types, there shouldn't be any references?

```
ModuleDefMD module = ModuleDefMD.Load(assemblyPath);
foreach (TypeDef typeDefinition in module.Types.ToArray())
{
    if (typeDefinition.FullName == "<Module>")
    {
        typeDefinition.CustomAttributes.Clear();
        typeDefinition.Methods.Clear();
        typeDefinition.Properties.Clear();
        typeDefinition.Fields.Clear();
        typeDefinition.Events.Clear();
        continue;
    }

    module.Types.Remove(typeDefinition);
}

module.NativeWrite(stubPath);
```

An unhandled exception of type 'dnlib.DotNet.Writer.ModuleWriterException' occurred in dnlib.dll

Additional information: TypeDef MyNamespace.GraphicsEventArgs (02000035) is not defined in this module (TopSecret.dll). A type was removed that is still referenced by this module.

**Comment by 0xd4d** [comment]
C++/.NET assemblies usually have a VTableFixups with references to methods. Executable images also have an EntryPoint.

BTW, the correct way to check for the global type is `type.IsGlobalModuleType` since it doesn't have to be named `<Module>`.

**Comment by MulleDK19** [comment]
I've tried setting the VTableFixups property to null. I've also tried to just clear the VTable property on the existing instance. Same exception.

It works if I use Write() instead of NativeWrite(), but I assume all the native stuff is gone then.

**Comment by 0xd4d** [comment]
Some MD tokens are preserved when saving C++/.NET assemblies. Make sure nothing is preserved by passing in writer options that don't have those options enabled.

**Comment by MulleDK19** [comment]
Okay, that worked.

However, when I try to reference the written assembly in VS (Regardless of whether I use NativeWrite or Write), it displays this error.

---------------------------
Microsoft Visual Studio
---------------------------
A reference to 'C:\Users\Morten\AppData\Local\Temp\oka2tu2gtxw05fhc\stub.dll' could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component.
---------------------------
OK   
---------------------------

The assembly opens fine in ILSpy.

**Comment by 0xd4d** [comment]
Maybe VS can't handle empty assemblies? You removed every single type.

**Comment by MulleDK19** [comment]
I left one. But the example above was just a test.
With the actual assembly, I'm simply converting all methods to stubs.

I was attempting to port my working code from Mono.Cecil to dnlib.

**Comment by 0xd4d** [comment]
Cecil doesn't support mixed mode assemblies last time I checked.

If the assembly is never executed, try saving it as a non-mixed mode assembly. I have no idea why VS can't read it but ILSpy can.

**Comment by MulleDK19** [comment]
I tried specifying ILOnly, setting native entry point to 0 and using Write(), but VS still won't reference it. It has no problem referencing the one created by Mono.Cecil.

**Comment by 0xd4d** [comment]
What does peverify say?

**Comment by MulleDK19** [comment]
```
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

File not found or has bad headers.
1 Error(s) Verifying C:\Users\Morten\AppData\Local\Temp\ezqtfa5kpunsvnbe\stub.dll
```

**Comment by 0xd4d** [comment]
That error message didn't help. Who knows what it complains about. Try this and if it doesn't help, email me the file if that's possible:

```C#
mod.IsILOnly = true;
mod.VTableFixups = null;
mod.IsStrongNameSigned = false;
mod.Assembly.PublicKey = null;
mod.Assembly.HasPublicKey = false;

var opts = new ModuleWriterOptions(mod);
mod.Write("path", opts);
```

**Comment by 0xd4d** [comment]
Closed due to inactivity.
