### ISSUE TITLE
Reason for the project at all?

### ISSUE THREAD

**Issue by WrongBit** [0xd4d/dnlib#371]
Hi! Guys, I can sound strange, but... why dnLib is created at all? In main readme I see no any mention or comparison of dnLib with System.Reflection.Emit.AssemblyBuilder; Why it's better? (or worse?) What it simplifies or does better/faster?
It could be nice to know why this library created.
Thanks!

**Comment by KvanTTT** [comment]
I use dnlib for processing .dll libraries without dependency on the current version of .NET. The standard System.Reflection loads type into the same domain and throws exceptions if assemblies are incompatible, unlike dnlib. It works on any platform and with any .NET assembly.

**Comment by 0xd4d** [comment]
I wrote it because I needed it.
