### ISSUE TITLE
How to load a source code?

### ISSUE THREAD

**Issue by Danila2221** [0xd4d/dnlib#374]
Is it possible to somehow load the source code (class files) into these library without decompiling .exe? Suppose I need to upload my code and rename all methods and fields to random values, and save the already renamed code.

**Comment by CursedSheep** [comment]
Sorry but dnlib doesn't work like that. But dnlib can be used for disassembling a compiled .NET assembly.
Here's a good technique. Compile your class files into a library, load it with dnlib, and use dnlib to rename all definitions you want to rename. Then, use dnspy to export it as source code.

or you can just ctrl + r + r in visual studio and rename them manually.

**Comment by Danila2221** [comment]
> Sorry but dnlib doesn't work like that. But dnlib can be used for disassembling a compiled .NET assembly.
> Here's a good technique. Compile your class files into a library, load it with dnlib, and use dnlib to rename all definitions you want to rename. Then, use dnspy to export it as source code.
> 
> or you can just ctrl + r + r in visual studio and rename them manually.

Ok, thanks
