### ISSUE TITLE
Module to ModuleDefMD

### ISSUE THREAD

**Issue by Danila2221** [0xd4d/dnlib#376]
Hello, now another question. How can I convert a module (System.Reflection.Module) to ModuleDefMD, or Assembly (System.Reflection.Assembly) to AssemblyDefMD?
I'm trying to take it from CompiledAssembly, this is example:
`Module module = results.CompiledAssembly.GetModules()[0];`

**Comment by 0xd4d** [comment]
Did you try something like: `ModuleDefMD.Load(typeof(int).Module)`

**Comment by Danila2221** [comment]
> Did you try something like: `ModuleDefMD.Load(typeof(int).Module)`

Thanks, it works
