### ISSUE TITLE
Supporting WinRT type projection

### ISSUE THREAD

**Issue by yck1509** [0xd4d/dnlib#38]
When working with WinRT assemblies, it would be convenient to have WinRT type projection in resolvers, since some WinRT type and CLR type are treated as the same. For example, `Windows.Foundation.Collections.IMapView` is same as `System.Collections.Generic.IReadOnlyDictionary`.

See https://stackoverflow.com/questions/10679515/winrt-projected-types-documentation for details and https://github.com/dotnet/coreclr/blob/master/src/inc/winrtprojectedtypes.h for the projected type list.

**Comment by 0xd4d** [comment]
Yes, that would be useful. Will have a look at this later.

**Comment by 0xd4d** [comment]
I've pushed something that possibly fixes this issue. Let me know how it works on a real world assembly.

**Comment by yck1509** [comment]
It throws NRE at Resolver.Resolve(MemberRef). It seems ToCLR returns null for normal MemberRefs.

**Comment by 0xd4d** [comment]
Missing ?? oeprator. Try again. :)

**Comment by yck1509** [comment]
It works for my case. :)
