### ISSUE TITLE
Why doesn't ModuleDef.Find(ITypeDefOrRef) check Scope?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#380]

**Comment by 0xd4d** [comment]
Why do you think it should check Scope?

**Comment by CreateAndInject** [comment]
If two assemblies contain two types with same fullname:
AssemblyA ns.Class1
AssemblyB ns.Class1
Then, AssemblyA.Find(AssemblyB::ns.Class1) will return AssemblyA::ns.Class1)?

Why there's no TypeDef.FindMethod(IMethod)?
```C#
class A
{
void M1(){}
}
class B
{
void M1(){}
}
```
type=A, method=B.M1, then
type.FindMethod(method.Name, method.MethodSig)=A.M1

I think if someone call ModuleDef.Find/TypeDef.FindMethod, dnlib should return null if the type/method isn't defined in the ModuleDef/TypeDef

**Comment by 0xd4d** [comment]
It's supposed to ignore Scope. Its job is only to find the first type that matches the namespace + name.
