### ISSUE TITLE
ValueType argType instead of Class

### ISSUE THREAD

**Issue by SpoodyTheOne** [0xd4d/dnlib#381]
I'm quite new to IL so i don't know if the title is correct or complete nonsense, but I am having trouble with getting the correct IL output from dnlib.

If i look at the assembly with dnSpy the c# code is correct, but a thing is wrong with the IL code and i don't know how to fix it, and was wondering if anybody could help me.

The IL code im trying to produce is this:
`callvirt  instance object [mscorlib]System.Type::InvokeMember(string, valuetype [mscorlib]System.Reflection.BindingFlags, class [mscorlib]System.Reflection.Binder, object, object[])`

But the code that is produced is this:
`callvirt  instance object [netstandard]System.Type::InvokeMember(string, class [netstandard]System.Reflection.BindingFlags, class [netstandard]System.Reflection.Binder, object, object[])`

the difference is that System.Reflection.BindingFlags has class instead of valuetype infront, and i dont know how to change that.

My current c# code:
![image](https://user-images.githubusercontent.com/28778347/87873336-0cde7c80-c9c1-11ea-8573-9f4ee1f227c9.png)
![image](https://user-images.githubusercontent.com/28778347/87873344-254e9700-c9c1-11ea-98ab-199671ae26cf.png)
![image](https://user-images.githubusercontent.com/28778347/87873353-3dbeb180-c9c1-11ea-8cd3-0691e3c60cbe.png)

**Comment by 0xd4d** [comment]
Did you add an assembly resolver? See the README.

If it's a value type you should use a `ValueTypeSig` and if it's not a value type, use `ClassSig`.
