### ISSUE TITLE
Rename variables

### ISSUE THREAD

**Issue by graysuit** [0xd4d/dnlib#383]
I am working on obfusticator,
I have done basics,
And now I want to rename all private variables in my app according to my choice,
So how do I ?

For a while, I tried this https://github.com/BinaryScary/NET-Obfuscate
And works great except it don't rename variables.

**Comment by 0xd4d** [comment]
All locals have a Name property. Just write to it and save the PDB file. Or just delete the PDB file.

**Comment by graysuit** [comment]
I have some doubts,
I will be thankful if you please help.


>All locals have a Name property.

What locals ? Where do I find ?

>Just write to it and save the PDB file. Or just delete the PDB file.

Are variables are dependent on pdb files ? 
But I can see variables without pdb files using dnspy, why this possible ?


Could you please provide little example for renaming variables ?
```c#
    ModuleDef md = ModuleDefMD.Load(pathExec);
    //how rename variables here ?
    md.Write(outFile);
```

**Comment by 0xd4d** [comment]
Decompilers will generate names of locals if they can't find a PDB so that's probably what you're seeing. So in other words, there's nothing to rename.

All locals are in a method's body, see the Body property. Also see the dnlib examples and the README on how to use dnlib.

**Comment by graysuit** [comment]
Your contribute are really helpful. Thank you so much sir.
