### ISSUE TITLE
class template of method instructions unchanged

### ISSUE THREAD

**Issue by JimLee168** [0xd4d/dnlib#384]
ClassLibrary1
```
	public class Class1 {
		public string TestProperty { get; set; }
	}
	public class Class2<T1, T2> {
		public string TestProperty { get; set; }
	}
```
Test
```
	var mod = ModuleDefMD.Load(@"Z:\in.dll");
	foreach(var t in mod.Types) {
		foreach (var p in t.FindProperties("TestProperty"))
			p.Name = "TestPropertyNew";
		foreach(var f in t.FindFields("<TestProperty>k__BackingField")) {
			f.Name = "<TestPropertyNew>k__BackingField";
		}
	}		
	mod.Write(@"z:\out.dll");
```
The problem is as shown below.
![image](https://user-images.githubusercontent.com/1819980/89643102-a2499e00-d8e7-11ea-9de7-4a3e08dd54d6.png)

**Comment by CreateAndInject** [comment]
View in dnSpy:
``
.method public hidebysig specialname 
	instance string get_TestProperty () cil managed 
{
	.custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
		01 00 00 00
	)
	// Header Size: 12 bytes
	// Code Size: 11 (0xB) bytes
	// LocalVarSig Token: 0x11000004 RID: 4
	.maxstack 1
	.locals init (
		[0] string
	)

	/* 0x000005B8 02           */ IL_0000: ldarg.0
	/* 0x000005B9 7B3F00000A   */ IL_0001: ldfld     string class Class2`2<!T1, !T2>::'<TestProperty>k__BackingField'
	/* 0x000005BE 0A           */ IL_0006: stloc.0
	/* 0x000005BF 2B00         */ IL_0007: br.s      IL_0009

	/* 0x000005C1 06           */ IL_0009: ldloc.0
	/* 0x000005C2 2A           */ IL_000A: ret
} // end of method Class2`2::get_TestProperty
```

```/* 0x000005B9 7B3F00000A   */ IL_0001: ldfld     string class Class2`2<!T1, !T2>::'<TestProperty>k__BackingField'```

See the bytes code, you can see the token is a `MemberRef` (0xA) rather than a `FieldDef`, so you must modify the name of the ref also.

**Comment by JimLee168** [comment]
How to modify MemberRef?

**Comment by JimLee168** [comment]
Thank you, it has been resolved.
