### ISSUE TITLE
Hit assert with `unknown custom debug info` in portable pdb with new version of roslyn(vs16.7)

### ISSUE THREAD

**Issue by yyjdelete** [0xd4d/dnlib#386]
Seems some new debug info has been added in new version of roslyn, and will hit assert [here](https://github.com/0xd4d/dnlib/blob/b4843c7ce1f43429148fb5e008e5bfe5c80e7564/src/DotNet/Pdb/Portable/PortablePdbCustomDebugInfoReader.cs#L63) in debug builds of dnlib.(not affect release build)

https://github.com/dotnet/roslyn/blob/Visual-Studio-2019-Version-16.7/src/Dependencies/CodeAnalysis.Debugging/PortableCustomDebugInfoKinds.cs#L20-L21

`https://github.com/dotnet/runtime/pull/37605/commits/326b437324db24162565ad3ce70b05ad14667b86`

**Comment by KvanTTT** [comment]
I have the same issue during tests running.

**Comment by 0xd4d** [comment]
Thanks for reporting this. It now supports these 2 new custom debug info guids.
