### ISSUE TITLE
How to determine the exe of a .NET Core application by dnlib?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#388]
The exe of .NET Core application is a native PE rather than manged.
So is there any why to determine whether an exe is a .NET Core applition by dnlib?

**Comment by 0xd4d** [comment]
No. dnSpy's debugger does it however:

https://github.com/0xd4d/dnSpy/blob/839383b7f2f0ef512b16739bc6f903fcc9855d8c/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.CorDebug/Dialogs/DebugProgram/DotNetCoreGenericDebugEngineGuidProvider.cs#L35-L43
