### ISSUE TITLE
Should Add arg.Value if it's TypeSig?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#390]
https://github.com/0xd4d/dnlib/blob/a14ea62859eb0e6c658752cbf9353eb1aeddc8c6/src/DotNet/MemberFinder.cs#L272-L275

**Comment by 0xd4d** [comment]
Yes, but also if it's an `IList<CAArgument>` or a `CAArgument`

**Comment by CreateAndInject** [comment]
It's TypeSig when `[Attr(typeof(...)]`
When happened for `IList<CAArgument>` and `CAArgument`?

**Comment by ElektroKill** [comment]
This issue was fixed by: https://github.com/0xd4d/dnlib/commit/cfcdf54693016a3a6dd1d7bb74563eeb7f9fec8c

**Comment by wtfsck** [comment]
OK, closing it.
