### ISSUE TITLE
Should MethodSpec has ReturnType and Parameters/ParamDefs?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#391]
Should MethodSpec has `ReturnType` and `Parameters`/`ParamDefs` properties? So I can get the actual type?

```C#
class C
{
	public static T Test<T, U>(T arg1, string arg2, U arg3)
	{
		throw new NotImplementedException();
	}

	public void Call()
	{
		Test(this, "abc", 1); //MethodSpec: ReturnType:C, Parameters:C,string,int
	}
}
```

**Comment by 0xd4d** [comment]
No, the underlying method could be a method reference which doesn't have a `Parameters` property.

You can use `MethodSpec.Method` to get its method (ref or def) and get its method sig with parameter types and return type.
