### ISSUE TITLE
TypeSig of generic class hidden this parameter is not instantiated

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#392]
in ParameterList.UpdateThisParameterType, dnlib just create a ClassOrValueTypeSig, but if declaring type is a generic type, dnlib doesn't create a GenericInstSig. is this a mistake or by design?

**Comment by wwh1004** [comment]
if it is a mistake, these code should work
``` cs
			if (methodDeclaringType is null) {
				hiddenThisParameter.Type = null;
				return;
			}
			var typeSig = methodDeclaringType.IsValueType ? (TypeSig)new ValueTypeSig(methodDeclaringType) : new ClassSig(methodDeclaringType);
			if (methodDeclaringType.HasGenericParameters) {
				var genArgs = new List<TypeSig>();
				foreach (var gp in methodDeclaringType.GenericParameters)
					genArgs.Add(new GenericVar(gp.Number, methodDeclaringType));
				typeSig = new GenericInstSig((ClassOrValueTypeSig)typeSig, genArgs);
			}
			if (methodDeclaringType.IsValueType)
				typeSig = new ByRefSig(typeSig);
			hiddenThisParameter.Type = typeSig;
```

**Comment by 0xd4d** [comment]
That code is pretty old so don't remember all the details. Could be a breaking change now.

How did this break your code?

BTW

```C#
foreach (var gp in methodDeclaringType.GenericParameters)
```

That should be a for loop from 0 .. num_gen_params - 1.

**Comment by wwh1004** [comment]
I want to assign local for each parameter, like
``` cs
foreach (var parameter in parameters)
	locals.Add(new Local(parameter.Type));
```
if it is a instance method in generic class, i will get non instantiated this type



are there some errors with "foreach (var gp in methodDeclaringType.GenericParameters)" ?

**Comment by wwh1004** [comment]
how about add another property that returns instantiated this type or add another boolean property to control whether instantiating or not? if this is an acceptable way?
