### ISSUE TITLE
Change NetFramework version of another application

### ISSUE THREAD

**Issue by r3xq1** [0xd4d/dnlib#393]
How can I change the .NetFramework version of another application using dnlib?
````csharp
using var module = ModuleDefMD.Load(Properties.Resources.MyExeFile);
if (module.IsILOnly)
{
   module?.Write(Path.Combine(CurrDir, "Build.exe"));
}
````

**Comment by 0xd4d** [comment]
Short answer: You can't.

Long answer: You can but it's too complicated. Solution: get the source code and recompile it.
