### ISSUE TITLE
how to clone everything or override the exist one from A into B properly?

### ISSUE THREAD

**Issue by liesauer** [0xd4d/dnlib#396]
i am trying to clone every single type(override if exist) into B from A, but when i save the assembly, it said "TypeDef Game (020002FA) is not defined in this module (Assembly-CSharp.dll). A type was removed that is still referenced by this module.". how can i update the ref to the new TypeDef.

```
var assembly = ModuleDefMD.Load(AssemblyName);
var firstPass = ModuleDefMD.Load(FirstPassName);
var newAssembly = ModuleDefMD.Load(ModName);

Dictionary<string, TypeDef> allTypes = new Dictionary<string, TypeDef>();

foreach (var type in newAssembly.Types)
{
    allTypes[type.FullName] = type;
}

foreach (var type in assembly.Types.ToArray())
{
    if (allTypes.ContainsKey(type.FullName))
    {
        assembly.Types.Remove(type);
    }
}

foreach (var type in newAssembly.Types.ToArray())
{
    newAssembly.Types.Remove(type);
    assembly.Types.Add(type);
}

Directory.CreateDirectory("new");

assembly.Write("new/output.dll");
```

i also tried reading the `ModuleImporter` of dnspy, but i got nothing because i am lack of related knowledge. basically, i just want to do the same thing as dnspy "MergeWithAssembly", but i want to override the same type, not rename to `XXX_1` `XXX_2`.

**Comment by 0xd4d** [comment]
The original assembly still has direct refs to the types you removed. Removing those types and adding new types with the same names won't automatically fix all links from the old defs to the new ones. You just have to find all of them and update them. They're in the code and in BaseType, attributes etc.
