### ISSUE TITLE
How to identify members returning and or accepting the dynamic type

### ISSUE THREAD

**Issue by hailstorm75** [0xd4d/dnlib#397]
Hello!
Is there any possibility to figure out whether a return or argument type of a member is `dynamic`? The issue is that is compiles down to `System.Object`.
I've observed that if a member accepting arguments has a `dynamic` type present in its signature, an additional argument `A_0` will be added.

![image](https://user-images.githubusercontent.com/16069996/94898459-e3969e00-0491-11eb-9648-cadf55ee38bb.png)

Are there any more tricks to figure out that a type is `dynamic` using reflection?

**Comment by 0xd4d** [comment]
I think the compiler adds some attributes.
