### ISSUE TITLE
how to edit assembly attributes??

### ISSUE THREAD

**Issue by Ambraham1544** [0xd4d/dnlib#398]
![123](https://user-images.githubusercontent.com/48386042/94943245-5ba4a880-0512-11eb-88ef-b2f53bfe0f7d.PNG)
![cap2](https://user-images.githubusercontent.com/48386042/94943250-5c3d3f00-0512-11eb-9f2b-0c4c13892616.PNG)

I'd like to edit & remove & add attribute class.
But I don't know how to get there about it and I've seen dnspy but it's too esoteric...
I also want to change the framework version.
ModuleDef. If I change it using RuntimeVersion
It seems to have changed in Detect It Easy, etc., but when viewed through dnspy,
It does not appear that it has changed. Also importantly, the version has not actually changed.
English is not my language. Sorry.
i apologize for the lengthy writing and hope you have God's grace.

**Comment by 0xd4d** [comment]
module.Attributes and module.Assembly.Attributes is what you're looking for.
