### ISSUE TITLE
How to rename a type and all references to it?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [0xd4d/dnlib#399]
I know how to find a type. But how can I rename it with all the references to it?

**Comment by 0xd4d** [comment]
You have to find all refs to that type. You can use `MemberFinder` to find all refs and defs and then rename all refs that reference the renamed defs.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks. I'll give it a try.
