### ISSUE TITLE
Renaming Variables

### ISSUE THREAD

**Issue by arsium** [0xd4d/dnlib#404]
foreach (MethodDef method in type.Methods)
{
    //my commands

    if (method.HasBody && method.Body.HasVariables)
    {
        foreach (var vr in method.Body.Variables)
        {
            vr.Name = GenerateName();
        }
    }
} 
I tried to rename my vars with this sample but I got null name and vars are not renamed any idea ?

**Comment by 0xd4d** [comment]
Why are you renaming them, just delete the PDB file or write `null` to `Name`. Variable names are stored in the PDB, not in the .NET metadata that's part of the EXE/DLL file.

**Comment by arsium** [comment]
Thx you I will try that ! I'm beginner about .net so I don't know all for the moment !
