### ISSUE TITLE
Renaming & Writing

### ISSUE THREAD

**Issue by arsium** [0xd4d/dnlib#405]
I tried this code below : 
` 
Dim mdef As ModuleDefMD = ModuleDefMD.Load("OBFTest1.exe")

        Dim xType As Integer = 0
        Dim xMthd As Integer = 0
        Dim xVar As Integer = 0
        Dim xParam As Integer = 0
        Dim xFields As Integer = 0

        If mdef.HasTypes Then

            For Each cls In mdef.Types()
                cls.Name = "Type_" & xType
                cls.Namespace = "NAME_SPACE" & xType
                xType += 1

                For Each field In cls.Fields
                    field.Name = "FIELD_" & xFields
                    xFields += 1
                Next

                'Dim Oaz As Byte() = {3, 1, 2, 3, 4, 45}

                '  Dim O As New UTF8String(Oaz)
                '  cls.Module.Name = O

                If cls.HasMethods Then

                        For Each mthd In cls.Methods()
                            mthd.Name = "mthd_" & xMthd
                            xMthd += 1

                            ' For Each var In mthd.Body.Variables()
                            '  Try
                            '    var.Name = "Var_" & xVar
                            'xVar += 1
                            ' Catch ex As Exception

                            '  End Try

                            '   Next

                            For Each param In mthd.ParamDefs

                                param.Name = "PARAM_" & xParam
                                xParam += 1

                            Next

                            'If mthd.HasBody() And mthd.Body.HasVariables() Then

                            'End If

                        Next
                    End If

                Next

        End If

        mdef.Write("Test.exe")`

and the file written won't open any idea ?

**Comment by 0xd4d** [comment]
> and the file written won't open any idea ?

Define 'open'. Execute it?

**Comment by 0xd4d** [comment]
The likely cause is that you're just renaming virtual methods. Eg. if you have a method that overrides `ToString()` from `System.Object`, you can't just rename it to `Method1()` and expect it to work. Renaming is a little more complicated than that. Try renaming only non-virtual and non-abstract methods (`method.IsVirtual` and `method.IsAbstract`). That's a lot safer. It can still break code that uses reflection to reference them by name.
