### ISSUE TITLE
Writer isn't preserving the custom sections

### ISSUE THREAD

**Issue by GabTeix** [0xd4d/dnlib#407]
I was writing some devirtualizer and when I save the file the custom sections from this vm are gone, the same happens on Dnspy when I use some trick on VMProtect's Anti Tamper.

And yes, I'm using the PreserveAll flag :

![image](https://user-images.githubusercontent.com/46636236/97091277-2f5fe180-1611-11eb-81cb-19374dffd3f2.png)

That's happens :

Before writing :
![image](https://user-images.githubusercontent.com/46636236/97091288-4999bf80-1611-11eb-83f5-344f92124e20.png)

After writing :
![image](https://user-images.githubusercontent.com/46636236/97091314-7e0d7b80-1611-11eb-81b1-30adeb1c37cd.png)

**Comment by GabTeix** [comment]
I already tried to use options.MetadataOptions.PreserveHeapOrder(Module, true), but it still doesn't work.

And in the dnspy case I marked all the presevation options.

Here's the file
[Nasha.zip](https://github.com/0xd4d/dnlib/files/5433623/Nasha.zip)

**Comment by 0xd4d** [comment]
The PE sections are completely rewritten. You can call `NativeWrite()` which will re-use the same executable. If the new data doesn't fit in the old locations, the executable could be much bigger than the original file though. You can also use the normal `Write()` method but add those PE sections yourself. See `Example6.cs` on how to add your own section.
