### ISSUE TITLE
Generic Method MemberRefs are not saved when saving the Module

### ISSUE THREAD

**Issue by fitdev** [0xd4d/dnlib#409]
I am not sure if this is by design or a bug, but when I am saving the Module, having updated its `MemberRef`s' names, only those `MemberRef`s are actually persisted in the output assembly file that _did not have generic parameters_, but those that did have generic parameters are left unchanged (same names as originals).

Since it would not do it automatically, I thought to do it manually, but have not found a way to manually persist a modified `MemberRef` to MemberRefs metadata table.

So, is there no way then to alter existing Method `MemberRef`s with generic signatures (i.e. change their name for instance)?

**Comment by 0xd4d** [comment]
MemberRefs (and a few others) have a reference to some GP context so they're not shared if they're generic.

You can find all of them by using `MemberFinder` and rename them that way.

**Comment by fitdev** [comment]
@0xd4d Thank you for looking into this. It seems to have worked.
Just to confirm, is this the correct approach then:
```cs
var finder = new MemberFinder().FindAll(Module);
var memberRefs = finder.MemberRefs.Keys.Where(mr => /* MemberRefs I am interested in */).ToArray();
foreach (var mr in memberRefs)
	mr.Name = GenerateNewNameLogic();
Module.Write("PathToNewFile.dll"); //Save
```
And would it matter if I access other elements like MemberDefs via non-MemberFinder APIs, or do I have to access all of them through a single MemberFinder instance?

**Comment by 0xd4d** [comment]
The `*Def`s are unique so you can get eg. `TypeDef`s with `module.GetTypes()`

The loop above seems to generate a new name for every `MemberRef` which won't work. There can be 0 or more `MemberRef`s that reference the same method/field in the same assembly or another assembly. All of those `MemberRef`s must have the same name as the `*Def` that they reference. You can use `FieldEqualityComparer`/`MethodEqualityComparer` or `SigComparer` to compare `MemberRef`s.

```C#
var finder = new MemberFinder().FindAll(mod);
// This should actually be all member refs to all defs that you rename. Eg. if you
// rename a def that's referenced by 2 assemblies, it should include all member refs
// from those assemblies instead of just one assembly used by this example.
foreach (var refs in finder.MemberRefs.Keys.GroupBy(a => a, a => a, (a, b) => b, FieldEqualityComparer.CompareDeclaringTypes)) {
	Console.WriteLine("Same refs:");
	foreach (var mr in refs)
		Console.WriteLine($"\t{mr}");
}
```

**Comment by fitdev** [comment]
@0xd4d You are right! Thank you for pointing this out. My bad at providing an overly simplistic example. Of course I do track where each MemberRef is actually used and will be renaming them all together. Thanks again for your help!
