### ISSUE TITLE
MethodSpec.ContainsGenericParameter

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#411]
```C#
		internal static bool ContainsGenericParameter(MethodSpec ms) {
			if (ms is null)
				return false;

			// A normal MethodSpec should always contain generic arguments and thus
			// its MethodDef is always a generic method with generic parameters.
			return true;
		}
```
Why `MethodSpec.ContainsGenericParameter` should allways return true even if its GenericInstMethodSig doesn't contain any GenericMVar?

`call Test<T>(...)` // contains GenericMVar
`call Test<int>(...)` // no GenericMVar

**Comment by wwh1004** [comment]
Fixed in https://github.com/0xd4d/dnlib/pull/440
