### ISSUE TITLE
InternalsVisibleTo Attribute

### ISSUE THREAD

**Issue by Sl4vP0weR** [0xd4d/dnlib#412]
```
var InternalsVisibleToAttributeRef = new TypeRefUser(mod, "System.Runtime.CompilerServices", "InternalsVisibleToAttribute", tps.AssemblyRef);
var InternalsVisibleToAttributeConstructor = new MemberRefUser(mod, ".ctor",
                                            MethodSig.CreateStatic(mod.CorLibTypes.Void, mod.CorLibTypes.String),
                                            InternalsVisibleToAttributeRef);

mod.Assembly.CustomAttributes.Add(new CustomAttribute(InternalsVisibleToAttributeConstructor, new List<CAArgument> { new CAArgument(mod.CorLibTypes.String, "AsemblyName") }));
```
This code add an attribute, but Visual Studio doesn't see this attribute.
If I write attribute in dnSpy, VS will see it correctly.
What should I do ?

**Comment by 0xd4d** [comment]
You need to use the correct args eg. include publickey{,token}, see https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0

The easiest way is to have the compiler do it for you then open it with dnlib and check the attribute's properties in the locals/watch window.

**Comment by Sl4vP0weR** [comment]
Both assemblies hasnt public key. 
The second variant, how can I do this?

**Comment by Sl4vP0weR** [comment]
@0xd4d, Please, help me

**Comment by 0xd4d** [comment]
See my post above, you should add the attribute to a C# file and inspect the created assembly. The compiler will do it correctly.

**Comment by Sl4vP0weR** [comment]
You guessing that I should try to compile my project by csc with /r: attribute?
