### ISSUE TITLE
Infinite loop in SigComparer.GetHashCode

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#427]
```C#
class Program {
		static void Main(string[] args) {
			var module = ModuleDefMD.Load(typeof(Program).Module);
			var method = module.EntryPoint.DeclaringType.FindMethod("Test");
			foreach (var instr in method.Body.Instructions) {
				if (instr.Operand is MethodSpec ms) {
					int code = new SigComparer().GetHashCode(ms); // Infinite loop
					Console.WriteLine(code);
				}
			}
			Console.WriteLine("OK");
			Console.ReadKey();
		}

		static void Test<T>(Dictionary<T, T> dict) => string.Concat(dict);
	}
```

**Comment by wtfsck** [comment]
Where in `SigComparer` does it keep looping?

**Comment by wwh1004** [comment]
generic argument of methodspec still contains generic parameter, dnlib will repeat to replace T with KeyValuePair<TKey,TValue> so there is a loop.
https://github.com/0xd4d/dnlib/blob/master/src/DotNet/SigComparer.cs#L2087

**Comment by CreateAndInject** [comment]
> generic argument of methodspec still contains generic parameter, dnlib will repeat to replace T with KeyValuePair<TKey,TValue> so there is a loop. https://github.com/0xd4d/dnlib/blob/master/src/DotNet/SigComparer.cs#L2087

Seems it's not the key point, since it's no problem if modify `Test` like this:
```
static void Test<T>(List<T> list) => string.Concat(list);
```
