### ISSUE TITLE
Wrong assembly reference

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#436]
```
class Program {
	static void Main(string[] args) {
		var module = ModuleDefMD.Load(typeof(Program).Module);
		var method = module.EntryPoint.DeclaringType.FindMethod("Test");
		foreach (var instr in method.Body.Instructions) {
			if (instr.OpCode == OpCodes.Ldtoken && instr.Operand is TypeRef tr) {
				string typeFullName = tr.AssemblyQualifiedName; // System.AppDomain, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
				var type = TypeNameParser.ParseReflection(module, typeFullName, null);
				instr.Operand = type;
				break;
			}
		}
		module.Write("1.exe");
	}

	static void Test() {
		Console.WriteLine(typeof(AppDomain));
		Console.ReadKey();
	}
}
```

The PublicKeyToken of mscorlib should be `b77a5c561934e089`, but dnlib produces `900e13d46cb0307b`:
 
![image](https://user-images.githubusercontent.com/2529999/146781263-e873e08c-ecfd-43dd-972b-01ff9feb26a5.png)

**Comment by wtfsck** [comment]
Have you debugged this issue?

**Comment by CreateAndInject** [comment]
Yes.
https://github.com/0xd4d/dnlib/blob/4a09c1289cb63ac302785ffe1011c5af9ba9b42e/src/DotNet/AssemblyRef.cs#L373-L383
Should be:??
`attributes = (int)(publicKey is PublicKey && !publicKey.IsNullOrEmpty ? AssemblyAttributes.PublicKey : AssemblyAttributes.None);`

I don't know, but seems `AssemblyRef.Attributes` should not be `AssemblyAttributes.PublicKey`.
