### ISSUE TITLE
why CustomAttribute  `Parent`  column  ` HasCustomAttribute`  is different with ECMA335 ? and what is last two 0?

### ISSUE THREAD

**Issue by WillDawnlll** [0xd4d/dnlib#441]
ecma 22.10 say CustomAttribute  `Parent`  column  ` HasCustomAttribute`:
> •	Parent (an index into any metadata table, except the CustomAttribute table itself; more precisely, a HasCustomAttribute  (§24.2.6) coded index)

why in dnlib is only 24 table ? and last two is 0?
```c#
public static readonly CodedToken HasCustomAttribute = new CodedToken(5, new Table[24] {
	Table.Method, Table.Field, Table.TypeRef, Table.TypeDef,
	Table.Param, Table.InterfaceImpl, Table.MemberRef, Table.Module,
	Table.DeclSecurity, Table.Property, Table.Event, Table.StandAloneSig,
	Table.ModuleRef, Table.TypeSpec, Table.Assembly, Table.AssemblyRef,
	Table.File, Table.ExportedType, Table.ManifestResource, Table.GenericParam,
	Table.GenericParamConstraint, Table.MethodSpec, 0, 0,
});

```

**Comment by wtfsck** [comment]
What it's trying to say is that if everything fits in 16 bits use 16 bits else use 32 bits.

**Comment by WillDawnlll** [comment]
thanks for your help.
yes, but in ecma335 , "fits"  mean 16bits low bit will code table index (log n , n mean relate table total number), remain bytes code max table row number (16-log n) , i guess that is why before  dnlib `return finalRows > 0xFFFF ? 4 : 2;` , there is a loop to find coded index about metadata table max row num . and if all 16 bit code row number , how to get the table  which the coded rid belong to?

**Comment by wtfsck** [comment]
The table is the low bits, eg. if it's a `TypeDefOrRef` coded token, it's the low 2 bits (see the spec for more info on which table value 0 is etc). The upper bits (i.e., starting from bit 2 and up if it's a `TypeDefOrRef` coded token) is the row id.

**Comment by WillDawnlll** [comment]
yes, but in dnlib ,maxRows compare with total 0xffff , is that mean all  16bits coded rid and no bit for table index?
i notice some .net pe  use 2bytes for coded index column , and one of relate coded table row number > remaining byte(for rid) , 
in ECMA335  it should be 4bytes , but in dnlib is 2bytes , and these files seem like dnlib is right .

**Comment by WillDawnlll** [comment]
sorry , dnlib is same with ECMA335, I  set wrong HasCustomAttribute relate tables .so  table bits calculate wrong ...
thanks for help again. 
but ecma 22.10 say CustomAttribute  `Parent`  column  ` HasCustomAttribute`:
> •	Parent (an index into any metadata table, except the CustomAttribute table itself; more precisely, a HasCustomAttribute  (§24.2.6) coded index)

why in dnlib is only 24 table ? and last two is 0?
```c#
public static readonly CodedToken HasCustomAttribute = new CodedToken(5, new Table[24] {
	Table.Method, Table.Field, Table.TypeRef, Table.TypeDef,
	Table.Param, Table.InterfaceImpl, Table.MemberRef, Table.Module,
	Table.DeclSecurity, Table.Property, Table.Event, Table.StandAloneSig,
	Table.ModuleRef, Table.TypeSpec, Table.Assembly, Table.AssemblyRef,
	Table.File, Table.ExportedType, Table.ManifestResource, Table.GenericParam,
	Table.GenericParamConstraint, Table.MethodSpec, 0, 0,
});

```
