### ISSUE TITLE
Why importing generic field should use assembly resolver to resolve original FieldDef

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#445]
https://github.com/0xd4d/dnlib/blob/1386325391fda1e2ca6339bf0e343e812c5fd346/src/DotNet/Importer.cs#L595
``` cs
if (origField.FieldType.ContainsGenericParameters) {
	var origDeclType = origField.DeclaringType;
	var asm = module.Context.AssemblyResolver.Resolve(origDeclType.Module.Assembly.GetName(), module);
	if (asm is null || asm.FullName != origDeclType.Assembly.FullName)
		throw new Exception("Couldn't resolve the correct assembly");
	var mod = asm.FindModule(origDeclType.Module.ScopeName) as ModuleDefMD;
	if (mod is null)
		throw new Exception("Couldn't resolve the correct module");
	var fieldDef = mod.ResolveField((uint)(origField.MetadataToken & 0x00FFFFFF));
	if (fieldDef is null)
		throw new Exception("Couldn't resolve the correct field");

	var fieldSig = new FieldSig(Import(fieldDef.FieldSig.GetFieldType()));
	fieldRef = module.UpdateRowId(new MemberRefUser(module, fieldInfo.Name, fieldSig, parent));
}
```

Sometimes it is difficult to resolve assembly and importer will throw if AssemblyResolver is null.
e.g. Target assembly is memory loaded.

I don't know why generic field should be treated differently. I find it is changed in a old commit https://github.com/0xd4d/dnlib/commit/4ebebc1cd335676158688cc2e786de16b152f173
I've tested many cases of generic field and the old code (same behavior as importing generic method) can return the same result.

Test code:

``` cs
static class G<T1, T2> where T1 : class {
 static volatile T1 Value1;
 static volatile IDictionary<T1, T2> Value2;

 static void MethodToImport<T3>() where T3 : class {
  Value1 = null;
  Value2 = null;
  G<string, string>.Value1 = null;
  G<string, string>.Value2 = null;
  G<string, T3>.Value1 = null;
  G<string, T3>.Value2 = null;
  G<T3, T3>.Value1 = null;
  G<T3, T3>.Value2 = null;
 }
}
```

**Comment by wtfsck** [comment]
I don't remember why. Have you tried opening many other .NET files and checking if the original code produces the same result as code that doesn't try to resolve the assembly?

If you can't find any problems, you can send a PR with a fix!

**Comment by CreateAndInject** [comment]
Seems we must resolve it, or else `fieldInfo.FieldType` may be replaced as a specific type e.g `int` rather than `GenericSig`
