### ISSUE TITLE
MappedFile Handle is created when accessing MethodDef.CustomAttributes

### ISSUE THREAD

**Issue by 0x084E** [0xd4d/dnlib#45]
Hello and first of all, thanks for a really cool library which I'm using every day :)

Among others I'm using it to generate a hash over the IL code of an assembly. While doing this a MappedFile handle is created on the file the module was loaded from. This handle is never released which makes it impossible to save the assembly.  

I was able to track it down to where I start to iterate over the CustomAttributes collection of a MethodDef but I don't know why this handle is created and how I can avoid or close it.

Do you have any ideas?
Best regards

**Comment by 0xd4d** [comment]
Memory mapped IO is used by default unless you pass in a byte[] or an IntPtr to ModuleDefMD.Load().

Calling the module's Dispose() method disposes the module and closes any OS handles it has opened. Don't try to use it after you've called Dispose() though! The module has a destructor which will close the mmap handle but it's of course only called when the GC collects it.

Simple solution, pass in File.ReadAllBytes(filename) to ModuleDefMD.Load() or save it to some other filename.

If you want mmap'd IO, you can disable it later before you try to save the module to the same file:

```C#
ModuleDef m = GetSomeModule();
// ... do something here ...
// If you created the module by calling ModuleDefMD.Load(), it's always a ModuleDefMD
var mod = m as ModuleDefMD;
if (mod != null) {
	// This is only unsafe if other code in other threads are also accessing
	// the module
	mod.MetaData.PEImage.UnsafeDisableMemoryMappedIO();
}
```

**Comment by 0xd4d** [comment]
Note that if you directly or indirectly resolve assemblies, the assembly resolver will cache those assemblies. The default assembly resolver will dispose all those assemblies when you call its Clear() method:

```C#
m.Context.AssemblyResolver.Clear();
```

**Comment by 0x084E** [comment]
I was already loading and saving the module with a byte array because of a similar problem so `UnsafeDisableMemoryMappedIO`didn't help.
But `m.Context.AssemblyResolver.Clear()` before saving did it! So I assume the assembly is loading itself as reference at some point.

Anyways thanks for your fast help, very appreciated!

**Comment by 0xd4d** [comment]
Try this:

```C#
mod.Context.AssemblyResolver.AddToCache(mod);
```

**Comment by 0xd4d** [comment]
Of course, do it right after you've created the module and initialized its Context.

**Comment by 0x084E** [comment]
Works, and the best solution I think, thanks!

**Comment by 0x084E** [comment]
And after seeing it I realized that this is referenced in the readme...
