### ISSUE TITLE
The Writing damage my dll ?

### ISSUE THREAD

**Issue by HPXCoder** [0xd4d/dnlib#457]
hi sir, 
am just read the dll and write it and its been damaged 
there is very big difference between the original dll size and the written dll
as shown in pic 
![err](https://user-images.githubusercontent.com/31288493/158323440-6fd35b84-9aed-4551-9c90-32e5a65e5f10.PNG)

and i have used the metadata flags [preserve all & keep old stack]

`options.MetadataOptions.Flags = MetadataFlags.PreserveAll;` 
`options.MetadataOptions.Flags |= MetadataFlags.KeepOldMaxStack;` 

there is any advice to keep my dll not damaged after write ?

**Comment by yangzhongke** [comment]
It looks like the same problem with mine: [https://github.com/0xd4d/dnlib/issues/455](https://github.com/0xd4d/dnlib/issues/455)

**Comment by HPXCoder** [comment]
> It looks like the same problem with mine: #455
> 
> ```
> if(module.IsILOnly)
>     {
>         module.Write(filename);
>     }
>     else
>     {
>         module.NativeWrite(filename);
>     }
> ```

Oh thanks bro for reply
i will try and give a feedback ;D 
Great Thanks again

**Comment by HPXCoder** [comment]
> It looks like the same problem with mine: #455
> 
> ```
> if(module.IsILOnly)
>     {
>         module.Write(filename);
>     }
>     else
>     {
>         module.NativeWrite(filename);
>     }
> ```

unfortunately
it didnt have any native codes still the same problem

**Comment by yangzhongke** [comment]
Please provide the C# code and the origial dll file.

**Comment by HPXCoder** [comment]
dll
https://mega.nz/file/JCp1DA7Y#qPEBkKcLUUYexaac7jw8eaWGTCjrpyXCOE---D_ZGf4

`using (ModuleDefMD mod = ModuleDefMD.Load(FilePath))
                    {
                        ModuleWriterOptions options = new ModuleWriterOptions(mod) { Logger = DummyLogger.ThrowModuleWriterExceptionOnErrorInstance };

                        options.MetadataOptions.Flags = MetadataFlags.KeepOldMaxStack;
                        mod.Write(DestPath, options);
                    }`

**Comment by HPXCoder** [comment]
> Please provide the C# code and the origial dll file.

dll
https://mega.nz/file/JCp1DA7Y#qPEBkKcLUUYexaac7jw8eaWGTCjrpyXCOE---D_ZGf4

c# code
`using (ModuleDefMD mod = ModuleDefMD.Load(FilePath))`
                   ` {`
                     `   ModuleWriterOptions options = new ModuleWriterOptions(mod) { Logger = DummyLogger.ThrowModuleWriterExceptionOnErrorInstance };`
                        `options.MetadataOptions.Flags = MetadataFlags.KeepOldMaxStack;`
                        `mod.Write(DestPath, options);`
                   ` }`

**Comment by yangzhongke** [comment]
Sorry, I did not use .NET framwork with dnlib. I have no idea.
Maybe because it's obfuscated, and obfuscator embeded extra hidden data in dll file.
Hope others can help you.

**Comment by HPXCoder** [comment]
> Sorry, I did not use .NET framwork with dnlib. I have no idea. Maybe because it's obfuscated, and obfuscator embeded extra hidden data in dll file. Hope others can help you.

i appreciate your help 😊
Thanka for your time

**Comment by wtfsck** [comment]
Try calling `module.NativeWrite()` instead of `Write()`. And if it's obfuscated it could have runtime checks (eg. checksum) and other data. If so you have to fix that manually.

**Comment by HPXCoder** [comment]
> Try calling `module.NativeWrite()` instead of `Write()`. And if it's obfuscated it could have runtime checks (eg. checksum) and other data. If so you have to fix that manually.

First thank you for your help,
Its obfuscated .
With agile
and if i edited it using dnspy i will face the same problem .
Oh i forgot something 
The dll working so good in runtime 
But if added to visual studio and running a code or using a ui control 
Give me an error 
Stack trace err 
And saying that the object is not loaded when i put some controls to my form.

**Comment by wtfsck** [comment]
You need to find a deobfuscator for it.

**Comment by HPXCoder** [comment]
> You need to find a deobfuscator for it.

unfortunately, there is no 

can i deob it manually, is any toturial ? maybe you can help ?
