### ISSUE TITLE
Importer create ClassSig rather than GenericInstSig for generic type

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#462]
I don't know if it's a .NET runtime bug or dnlib bug.
.NET runtime indicate different `IsGenericTypeDefinition` for the same type `Task<>`
dnlib create ClassSig since `IsGenericType` and `IsGenericTypeDefinition` are both `True`;
```
			if (a.IsGenericType && !a.IsGenericTypeDefinition)
				return ElementType.GenericInst;
```

```
using System;
using System.Reflection;
using System.Threading.Tasks;
using dnlib.DotNet;

class Program {
	static void Main() {
		var methodInfo1 = typeof(Task<string>).GetMethod("ContinueWith", new Type[] { typeof(Action<Task<string>>) });
		Show(methodInfo1); // True

		var methodInfo2 = typeof(Demo2<string>).GetMethod("Test");
		Show(methodInfo2); // False

		var moule = ModuleDefMD.Load(typeof(Program).Module);
		var method1 = moule.Import(methodInfo1); // System.Threading.Tasks.Task System.Threading.Tasks.Task`1<System.String>::ContinueWith(System.Action`1<System.Threading.Tasks.Task`1>)
		Show(method1); // Class
		var method2 = moule.Import(methodInfo2); // System.Void Demo2`1<System.String>::Test(System.Action`1<System.Threading.Tasks.Task`1<System.String>>)
		Show(method2); // GenericInst
		Console.ReadKey();
	}

	static void Show(MethodInfo method) {
		var origMethod = method.Module.ResolveMethod(method.MetadataToken);
		var type = origMethod.GetParameters()[0].ParameterType.GenericTypeArguments[0];
		Console.WriteLine(type.IsGenericTypeDefinition);
	}

	static void Show(IMethod method) {
		var typeSig = (method.MethodSig.Params[0] as GenericInstSig).GenericArguments[0];
		Console.WriteLine(typeSig.ElementType);
	}
}

class Demo2<T> {
	public void Test(Action<Task<T>> arg) { }
}
```

**Comment by wtfsck** [comment]
If you have time, find the line in dnlib code, get the git blame and check why the line was changed, maybe it was one of the PRs. https://github.com/0xd4d/dnlib/blame/master/src/DotNet/Importer.cs

**Comment by CreateAndInject** [comment]
This code is from:
https://github.com/0xd4d/dnlib/blob/aa403ba424cc5fe7146e7958897cb35b43dd1ddb/src/DotNet/ReflectionExtensions.cs#L57-L58
Seems the line wasn't changed.
When I modify it to:
```
	if (a.IsGenericType)
		return ElementType.GenericInst;
```
I'll get StackOverflowException somewhere (not above code)

**Comment by wtfsck** [comment]
A generic instance is not a generic type def so both checks are needed. This does not appear to be a dnlib issue.

**Comment by CreateAndInject** [comment]
But `Import(Task.ContinueWith)` should be GenericInstSig.
I found this issue from DynamicMethodBodyReader, when I restore IL, and view it in dnSpy, dnSpy can't navigate a method, that means dnSpy can't resolve the method.
When I investigate it, I find the reason can create this tiny reprouce.
Maybe should set `treatAsGenericInst` to `true` in more cases, I don't know.

**Comment by wtfsck** [comment]
It's a problem that reflection is lying about it. If you can detect it some other way, let me know. There's another method in the same file that's used by some other code that can be used.

**Comment by CreateAndInject** [comment]
I'm sorry, I made a mistake:
```
class Demo2<T> {
	public void Test(Action<Task<T>> arg) { } // Task<T> => Demo2<T>
}
```

So, reflection keep pace with Task<T>.ContinueWith

So, reflection isn't lying?
My reproduce is completely wrong, but `DynamicMethodBodyReader` really build wrong IL like I said

**Comment by ElektroKill** [comment]
Hello!
I managed to find another test case for this problem, this time for fields!

```csharp
namespace TestFile {
	public sealed class Program {
		public static void Main() {
			var resolver = new AssemblyResolver();
			resolver.DefaultModuleContext = new ModuleContext(resolver);
			var mod = ModuleDefMD.Load(typeof(Program).Assembly.Location, resolver.DefaultModuleContext);

			var type = mod.Find("TestFile.Program", true);
			var method = type.FindMethod("TestMethod");

			var operand = (IField)method.Body.Instructions.FirstOrDefault(x => x.OpCode.Code == Code.Ldsfld).Operand;
			Console.WriteLine("Original: {0}", operand);

			var reflectionMember = (FieldInfo)typeof(Program).Assembly.ManifestModule.ResolveMember(operand.MDToken.ToInt32());

			var importer = new Importer(mod, ImporterOptions.TryToUseDefs, GenericParamContext.Create(method));

			Console.WriteLine("Imported: {0}", importer.Import(reflectionMember));
			Console.ReadKey(true);
		}

		private static void TestMethod() {
			Console.WriteLine(GenericClass<NonGenericClass.NestedGenericStruct<Type>>.Field);
		}
	}

	internal sealed class GenericClass<V> {
		private GenericClass() { }

		public static readonly GenericClass<V> Field = new GenericClass<V>();
	}

	internal static class NonGenericClass {
		public struct NestedGenericStruct<K> { }
	}
}
```
Compiling and running this code with dnlib 3.5.0 yields the following result:
```
Original: TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>> TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>>::Field
Imported: TestFile.GenericClass`1 TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>>::Field
```
It is worth mentioning that doing the same using dnlib 3.4.0 yield the expected result:
```
Original: TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>> TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>>::Field
Imported: TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>> TestFile.GenericClass`1<TestFile.NonGenericClass/NestedGenericStruct`1<System.Type>>::Field
```
I think something got broken when this PR https://github.com/0xd4d/dnlib/pull/452 by @wwh1004 was merged which modified how fields are imported.

**Comment by CreateAndInject** [comment]
Seems `NonGenericClass` and `NestedGenericStruct` are not required, can simply reproduce like:
```
private static void TestMethod()
		{
			Console.WriteLine(GenericClass<string>.Field);
		}
```

**Comment by wtfsck** [comment]
PRs welcome. I don't have time.

**Comment by wwh1004** [comment]
In old commit https://github.com/0xd4d/dnlib/commit/4ebebc1cd335676158688cc2e786de16b152f173#diff-3bc1d65c9144274297f0e9a1b2e194898aa3aa9e441d2956ab303ab4522dc554L488 code is
``` cs
var fieldSig = new FieldSig(ImportAsTypeSig(origField.FieldType));
```
So I use "origField" instead of "fieldInfo". But after running more tests I find "fieldInfo" is true.   
Also I find more problems about generic like nested case of "MustTreatTypeAsGenericInstType", wrong result of "FieldComparer.Equals", inconsistent result of GetHashCode(SRM.FieldInfo) and GetHashCode(DNN.IField), generic MemberRef always return true.  
I will fix them these days.
