### ISSUE TITLE
About interface IContainsGenericParameter and IContainsGenericParameter2

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/dnlib#467]
I used to found issue https://github.com/0xd4d/dnlib/issues/411 so I send pr https://github.com/0xd4d/dnlib/pull/440.
But now I find TypeHelper.ContainsGenericParameter just recursively check a dnlib object and its properties whether contains GenericVar/GenericMVar.

e.g. MethodSpec has columns Method and Instantiation, column Method is always generic and contains GenericMVar. So TypeHelper.ContainsGenericParameter(MethodSpec) always returns true if argument not null.

I didn't know the design of dnlib very well before, so made a wrong change. Now I think IContainsGenericParameter2 is used for resolve cache. If a metadata record contains gp (e.g. column Method in table MethodSpec has gp), SimpleLazyList2 shouldn't cache it.
But I still don't know what does IContainsGenericParameter design for. It seems useless for normal user because the behavior doesn't match reflection api and "a MethodSpec has closed instantiation but contains generic parameter" is very counterintuitive.

I think keep IContainsGenericParameter2 behaviors for internal use due to GenericParamContext is good. Should we change IContainsGenericParameter to same as reflection api, or revert pr https://github.com/0xd4d/dnlib/pull/440?

**Comment by wtfsck** [comment]
It was added so we wouldn't cache some things if they had a var/mvar.

> Should we change IContainsGenericParameter to same as reflection api, or revert pr #440?

Changing the behavior is a breaking change. Will reverting that PR fix a bug?

**Comment by wwh1004** [comment]
> It was added so we wouldn't cache some things if they had a var/mvar.

Do you mean currently IContainsGenericParameter is fully same as IContainsGenericParameter2? I thought they should have some differences before.

> Changing the behavior is a breaking change. Will reverting that PR fix a bug?

No bug will be fixed. Only thing is that pr https://github.com/0xd4d/dnlib/pull/440 breaks old behavior. I don't know if we should revert that pr. Because old behavior is that always return true for MethodSpec, but currently it will return false for MethodSpec which has closed instantiations.

**Comment by wtfsck** [comment]
> No bug will be fixed.

In that case nothing needs to be reverted. So far no-one has created any issue about this so there's nothing to fix.
