### ISSUE TITLE
Misleading use of uint

### ISSUE THREAD

**Issue by blattm** [0xd4d/dnlib#472]
As defined in the specification of CIL, branch targets are unsigned values. Dnlib reads branch targets as unsigned values (long version) or converts them to uint (short version). As far as I know, the code still behaves correctly because the 32 or 8 bit values can overflow.

I think it would make the code clearer to explicitly use signed integers in those cases or add comments in the MethodBodyReaderBase and MethodBodyWriterBase. I have actually seen this misleading use of uint "cause" bugs in another project inspired by dnlib. It was written in a language where overflows do not happen.

**Comment by wtfsck** [comment]
Using signed integers would be wrong. Offsets are unsigned. Unless you've found a bug somewhere, I think this issue can be closed.
