### ISSUE TITLE
 Param is already owned by another method. Set DeclaringMethod to null first.

### ISSUE THREAD

**Issue by sunnamed434** [0xd4d/dnlib#482]
```cs
var callingMethodDef = //other method instance...
var dummyMethod = new MethodDefUser("Dummy");
foreach (var paramDef in callingMethodDef.ParamDefs)
{
    dummyMethod.ParamDefs.Add(paramDef);
}
```
![image](https://user-images.githubusercontent.com/65300126/197363950-50ddb04b-2e5d-419f-926e-be09658d7e35.png)
![image](https://user-images.githubusercontent.com/65300126/197363949-eda5f9a1-4d45-49fd-aed8-dbce589fa18b.png)

The question is, how can I change the paramdef.DeclaringMethod when set is internal? Is it intentional?

**Comment by wtfsck** [comment]
Remove it from the owning method.
