### ISSUE TITLE
Writer option to only write modified method bodies

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnlib#49]
I'm currently trying to edit a module where all method bodies except for one are compressed/junk IL. When trying to save the module in dnSpy, it outputs:
```
Instruction operand is null
Instruction is null
Operand is not a local/arg
All files written to disk.
```
Perhaps this could be solved with an additional module writer option (metadata flag) to specify that only modified method bodies should be written/interpreted? Something like `MetaDataFlags.KeepUnmodifiedMethodBodies`.

**Comment by 0xd4d** [comment]
Seems like it would only be useful in very limited cases, i.e., when the file isn't deobfuscated and it's safe to keep the encrypted methods. Most obfuscators who encrypt methods probably have some check to make sure the image hasn't been modified so if you just change one method (even just one bit), it would be detected at runtime. The key used to decrypt the methods should be a function of the generated image, which means decryption wouldn't be possible after saving the file. Unless it's a very weak obfuscator.

**Comment by saneki** [comment]
Good points, closing this.
