### ISSUE TITLE
MetadataFlags.PreserveAll breaks Portable/Embedded PDBs

### ISSUE THREAD

**Issue by jespanag** [0xd4d/dnlib#495]
Info:
- OS: Win 11
- Loading module with dnlib: (.NET 7 Console App with Portable PDB)
- Using dnlib: (.NET 7 app, last dnlib version)

Hello, i'm trying to understand some issue, but i don't know why it's happening.
The summary is that if you use  `MetadataFlags.PreserveAll` when writting a module and previously you modify the module by adding a type/method, the portable/embedded pdb is wrong.

### I'm loading a module (.net 7) with dnlib:

- #### First case (Correct pdb)
 1. I load the module,
 2.  i set `wopts.WritePdb = true;` and 
 3. i `write` it and the writted pdb is correctly.
 
 - #### Second case (Correct pdb)
 1. I load the module,
 2. i set `wopts.WritePdb = true;`
 3. i add a new method to the module (a .cctor example):
 ```csharp
 var modType = module.GlobalType;

            var implFlags = MethodImplAttributes.IL | MethodImplAttributes.Managed;
            var flags = MethodAttributes.Private | MethodAttributes.Static |
                        MethodAttributes.HideBySig | MethodAttributes.ReuseSlot |
                        MethodAttributes.SpecialName | MethodAttributes.RTSpecialName;
            UTF8String StaticConstructorName = ".cctor";
            var cctor = (new MethodDefUser(StaticConstructorName,
                        MethodSig.CreateStatic(module.CorLibTypes.Void), implFlags, flags));
            var body = new CilBody();
            body.InitLocals = true;
            body.MaxStack = 8;
            body.Instructions.Add(OpCodes.Ret.ToInstruction());
            cctor.Body = body;
           
            
            modType.Methods.Add(cctor);
            module.UpdateRowId(cctor); //tryed this but not has effect in the pdb
```
 4.  i `write` it and the writted pdb is correctly.

- #### Third case (INVALID PDB)
1. I do the same that in second case but i add ` wopts.MetadataOptions.Flags |= dnlib.DotNet.Writer.MetadataFlags.PreserveAll;`
2. now the writted pdb is not working.

- #### Tests
1. If a use ` wopts.MetadataOptions.Flags |= dnlib.DotNet.Writer.MetadataFlags.PreserveAll;` but no new method/type is added to the assembly pdb is correctly.
2. If i **don't** put ` wopts.MetadataOptions.Flags |= dnlib.DotNet.Writer.MetadataFlags.PreserveAll;` pdb is all times correctly.
3. If the pdb type is *Windows pdb* works well in any scenario, but portable/embedded fails in the previous ones.

## Steps to reproduce:

```csharp
ModuleContext modCtx = ModuleDef.CreateModuleContext();
ModuleDefMD module = ModuleDefMD.Load(@"ExceptionsApps.dll", modCtx);

//This is the same that call to modType.FindOrCreateStaticConstructor(); 👇
var modType = module.GlobalType;
var implFlags = MethodImplAttributes.IL | MethodImplAttributes.Managed;
var flags = MethodAttributes.Private | MethodAttributes.Static |
                        MethodAttributes.HideBySig | MethodAttributes.ReuseSlot |
                        MethodAttributes.SpecialName | MethodAttributes.RTSpecialName;
UTF8String StaticConstructorName = ".cctor";
var cctor = (new MethodDefUser(StaticConstructorName,
                        MethodSig.CreateStatic(module.CorLibTypes.Void), implFlags, flags));
var body = new CilBody();
body.InitLocals = true;
body.MaxStack = 8;
body.Instructions.Add(OpCodes.Ret.ToInstruction());
cctor.Body = body;
modType.Methods.Add(cctor);
module.UpdateRowId(cctor);

//////
var wopts = new dnlib.DotNet.Writer.ModuleWriterOptions(module);
wopts.MetadataOptions.Flags |= dnlib.DotNet.Writer.MetadataFlags.PreserveAll;
wopts.WritePdb = true;    

module.Write(@"\pdb\ExceptionsApps.dll",wopts);
```

If your `ExceptionsApps` generates a exception, the pdb is not loaded and not shows file/line number.
If you remove `wopts.MetadataOptions.Flags |= dnlib.DotNet.Writer.MetadataFlags.PreserveAll;` from code example, pdb will be correctly generated.

I was reading about Rids -> pdb implications, but i can't understand whats happening here.

Thank you!

**Comment by jespanag** [comment]
@0xd4d or maybe, if it can't be fixed, there is any option to maintain the current `mdtoken` of already existing methods without using `PreserveAll` or similiar ?

- Complementary test: 
All the others `Preserve...` like `PreserveMethodRids` breaks the PDB file,

**Comment by ElektroKill** [comment]
Libraries like System.Reflection.Metadata forbid Portable/Embedded PDB from featuring the `MethodPtr` and other similar tables in the portable metadata which dnlib includes when using the metadata token preserving writer. I'm not entirely sure if this is documented somewhere or no since I cannot find any mentions of it in the portable pdb documentation.

Not really sure how this could be fixed as the Ptr tables are essential for the preserve tokens writer to function!

**Comment by jespanag** [comment]
Thanks for your answer,

And how could an assembly be modified keeping the MdToken and not breaking the pdb? Any ideas? Is there a way to manipulate the pdbs in another way?

**Comment by wtfsck** [comment]
This isn't supported and never will.
