### ISSUE TITLE
System.BadImageFormatException: ".NET data directory RVA is 0"

### ISSUE THREAD

**Issue by TrixiS** [0xd4d/dnlib#497]
```
ModuleDefMD.Load(filePath);
```

Raises System.BadImageFormatException: ".NET data directory RVA is 0"

**Comment by TrixiS** [comment]
Using .net7.0 with .exe assembly. Actually the copy of an assembly of the same program

**Comment by sunnamed434** [comment]
As far as I know, .NET 7.0 compiles into the native code, so, because of that It says that .NET RVA is 0 (because this is not a .NET file), not sure if you can disable native compilation

**Comment by TrixiS** [comment]
It works with .dll. Can I use it for .exes ?

**Comment by sunnamed434** [comment]
Ah, yeah, of course, it stores the code in .DLL, obviously use .DLL then

**Comment by TrixiS** [comment]
kk thx
