### ISSUE TITLE
Example for Windows PDB

### ISSUE THREAD

**Issue by baylf2000** [0xd4d/dnlib#498]
I've been trying to find an example for reading a Windows PDB, but I can't seem to find anything. If there was one available it would be extremely helpful. Thank you!

**Comment by sunnamed434** [comment]
You can try to use [asmresolver](https://github.com/Washi1337/AsmResolver) for that

**Comment by baylf2000** [comment]
> You can try to use [asmresolver](https://github.com/Washi1337/AsmResolver) for that

Thanks for the reply, but I don't believe that library does what I need. This one specifically says it does do what I need, however I'm lost as to how to make it work. Just looking for a basic example to get started.

**Comment by wtfsck** [comment]
See the README: https://github.com/0xd4d/dnlib#windows-pdbs
