### ISSUE TITLE
Saving Mixed Mode Assembly on Linux

### ISSUE THREAD

**Issue by AndriiTomashevskyi** [0xd4d/dnlib#499]
Hello, we are using the following code to load System.Net.Http.dll from the .NET Core runtime directory (`systemNetHttpPath`) and save it to another directory (`newSystemNetHttpPath`). We do not make any changes to the assembly. We pick the System.Net.Http.dll version based on the target framework of the application that will use it.
```
var module = ModuleDefMD.Load(File.ReadAllBytes(systemNetHttpPath));

if (module.IsILOnly)
{
    module.Write(newSystemNetHttpPath);
}
else
{
    module.NativeWrite(newSystemNetHttpPath);
}
```
We are getting the following exception on .NET Core 3.1 when we call `module.NativeWrite`:
dnlib.DotNet.Writer.ModuleWriterException: 'Could not create header'.

On .NET 6.0 we are getting the following exception:
dnlib.DotNet.Writer.ModuleWriterException: 'Invalid section RVA'.

We found a similar [issue](https://github.com/0xd4d/dnlib/issues/305) and according to the conversation we tried to do the following:
 ```
 if (!module.IsILOnly)
{
    module.Cor20HeaderFlags &= ~ComImageFlags.ILLibrary;
}

  module.Write(newSystemNetHttpPath);
```  
In this case, the module is saved successfully but we are getting a runtime exception when we try to run the application that uses saved System.Net.Http.dll:
'System.BadImageFormatException': 'Could not load file or assembly 'System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.'

**Note:** We experiencing this issue only on Linux (tested on Ubuntu 22.04)
On Windows both cases work fine.

**Comment by wtfsck** [comment]
Have you tried to debug this? You should be able to debug this on Windows if you just copy the file over to your Windows machine. I don't have a lot of time to investigate this at the moment.
