### ISSUE TITLE
Extend `DataStream` with additional methods for signed integers and decimal

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#509]
Currently, the way a `DataReader` created from a `DataStream` can be customized allows for changing the behavior by which unsigned integers, float point values, guids, and strings are read. However, the `DataReader` exposes methods like `ReadDecimal`, `ReadInt16`, and other methods for other signed integer types which currently just use casts from unsigned to signed integers to work.

I think it would be beneficial to provide additional `virtual` methods to `DataStream` for reading decimals and signed integer types. This would allow for greater customization of the `DataReader` behavior for scenarios where the logic for reading signed integers might be different from that of reading unsigned integers. The virtual methods could default to the current behavior but would allow an API consumer to implement their own versions when they derive from `DataStream`.

Example:
```csharp
class DataStream {
[...]

public abstract ulong ReadUInt64(uint offset);

public virtual long ReadInt64(uint offset) => (long)ReadUInt64(offset);

[...]
}
```
The `DataReader` struct could then be updated to use these additional methods.

I would happily contribute these changes if they are deemed appropriate!

**Comment by wtfsck** [comment]
Makes sense. In that case we'd have to find all places that cast the unsigned value to a signed value and then call the new signed overload instead.
