### ISSUE TITLE
Expose `WinMDHelpers` for consumers

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#510]
When implementing a custom implementation of `Resolver` I found myself having to copy and paste the `WinMDHelpers` class in order to add support for WinMD redirects. It would be nice to have this class exposed to the users.

**Comment by wtfsck** [comment]
Sure, want to send a PR?

**Comment by wtfsck** [comment]
https://github.com/0xd4d/dnlib/pull/511
