### ISSUE TITLE
Optimize properties on `TypeRef` and `TypeDef`

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#519]
`TypeRef` and `TypeDef` both currently implement `IType` and due to this, they have to provide `string Namespace { get; }` and `string TypeName { get; }` properties. These properties currently call `FullNameFactory.Name` or `FullNameFactory.Namespace`. These calls are expensive as they allocate a `StringBuilder` only to access and append a single similarly named property of type `UTF8String` from the `TypeDef` or `TypeRef`. Modifying these properties to just return the direct value of `UTF8String` properties through the use of its implicit cast operator would help improve the performance of the `IType` implementation in these two types.

If a green light is given, I'd be willing to open a pull request with these changes.

EDIT: After further investigation, this optimization could also be applied to `ExportedType`.

**Comment by wtfsck** [comment]
Type{Def,Ref} and ExportedType: sure, I probably wrote it that way for consistency.

GetAssemblyNameString: sure, but there are other allocations there too. How often is this function called, it's possible that it's barely used so it can be a waste of time to optimize it.

**Comment by ElektroKill** [comment]
> Type{Def,Ref} and ExportedType: sure, I probably wrote it that way for consistency.
> 
> GetAssemblyNameString: sure, but there are other allocations there too. How often is this function called, it's possible that it's barely used so it could be a waste of time to optimize it.

GetAssemblyNameString is used by anything which computes the assembly full name and even discarding potential aggressive use of this by the end user, this is used when building assembly-qualified names which is done by the security declaration writer, marshal blob writer, and custom attribute writer. The amount of times this is called can quickly add up depending on how many of these are present in the module being written.

See: 
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/Writer/MarshalBlobWriter.cs#L74
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/Writer/MarshalBlobWriter.cs#L102
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/Writer/DeclSecurityWriter.cs#L85
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/Writer/CustomAttributeWriter.cs#L719

It's also possible to modify these usages to use a shared  `StringBuilder` per run to prevent having to allocate a fresh `StringBuilder` every time and prevent the additional overhead of growing the internal buffer when long type names come along.
