### ISSUE TITLE
Potential feature: Support for 64 bit offsets and length in dnlib.IO

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#538]
Currently all the code under `dnlib.IO` is restricted to 32-bit offsets and sizes making it hard to use in scenarios when using 64-bit offsets may be necessary. 

Changing the code to support 64bit offsets would be a massive refactoring.

What do you think of this as a potential feature?

**Comment by wtfsck** [comment]
File offsets? 32 bits should be enough. A PE file can't be too big and a .NET PE file also has other size limitations.

**Comment by ElektroKill** [comment]
Solved my issue by implementing `DataStream` differently. I guess I will close this now since it was not really in the scope of dnlib since the issue was in my own implementations!
