### ISSUE TITLE
Sort `ExportedType` table in the same way as the `TypeDef` table

### ISSUE THREAD

**Issue by ElektroKill** [0xd4d/dnlib#558]
Microsoft has modified the specification to state that the table containing `ExportedType` rows should receive the exact same sorting as the `TypeDef` table.

See: https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md#metadata-logical-format

**Comment by wtfsck** [comment]
I think this only requires fixing `AddExportedTypes()` and just updating the code `var exportedTypes = module.ExportedTypes;` to make sure `exportedTypes` is sorted correctly, similar to what `module.GetTypes()` already does, see `NormalMetadata.GetAllTypeDefs()`

**Comment by ElektroKill** [comment]
Yeah, I thought about just modifying the code in `AddExportedTypes` to sort the exported types in the order that is defined in the ECMA augments documents but I haven't though of a nice and optimal algorithm for sorting. We can't do what we do for normal types since `ExportedType` defines its parent type compared to `TypeDef` which defines all of its nested types making creating the necessary ordering easier. If you have any ideas, lmk! Maybe I'm not thinking of something obvious :D

**Comment by wtfsck** [comment]
If it's a nested exported type, `ExportedType.Implementation` is an `ExportedType`. Just like if a type is nested, `TypeDef.DeclaringType` is a `TypeDef`.

It should be possible to build a temporary `TypeDef.NestedTypes` (for exported types) with a dictionary `ExportedType` -> `List<ExportedType>` by just checking if the current exported type (looping over all of them) is a nested type, and if so, just add it to `dict[parent].Add(current exported type)`. Then once we have that dict, we should be able to just use the same algorithm as module.GetTypes(), except that if `ExportedType.Implementation` is a `FileDef` or `AssemblyRef`, just add it to the result (no special ordering required).

```
foreach et in all-exported-types {
  if (et.Implementation is FileDef or AssemblyRef)
    just add it, no ordering required
  else if it's an ExportedType parent
    dict[parent].Add(et)
}
// now use the same algo as module.GetBytes() but use `dict` instead of checking `NestedTypes` property.
```

Haven't tested this but it seems like it could work.
