### ISSUE TITLE
TypeAttributes.NestedPrivate and Public

### ISSUE THREAD

**Issue by wangzq** [0xd4d/dnlib#58]
The enum is defined as flags so I assumed I can use `typeDef.HasFlag(TypeAttributes.Public)` to find public types, but since TypeAttributes.NestedPrivate is 3 and TypeAttributes.Public is 1, a private nested type seems return incorrect result here.

**Comment by 0xd4d** [comment]
The low 3 bits is the visibility. https://github.com/0xd4d/dnlib/blob/master/src/DotNet/TypeAttributes.cs#L11

Use typeDef.[Visibility](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/TypeDef.cs#L780) to get the visibility bits or just use `typeDef.[IsPublic](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/TypeDef.cs#L795).
