### ISSUE TITLE
dnlib adds PE sections when saving assembly with native code

### ISSUE THREAD

**Issue by AndreyThompson** [0xd4d/dnlib#65]
I have my assembly with native code. It has 3 PE sections: text, rsrc and reloc: 
![image](https://cloud.githubusercontent.com/assets/11197315/15708976/c240b94c-280a-11e6-85c5-adebb2923315.png)

I open and save it with dnlib
`var module = ModuleDefMD.Load(exeName);
module.NativeWrite(exeNewName);`

After that I noticed that file's size increased (from 6 kb to ~12 kb). I opened new file with dnlib:
![image](https://cloud.githubusercontent.com/assets/11197315/15709064/42069bf6-280b-11e6-820b-168ba9865a45.png)

New file has 5 PE sections: new text and rsrc section, reloc section and old text and rsrc sections.
If I apply my code to the new file - generated file will have 7 PE sections. And so on.

I tried to use `NativeModuleWriterOptions` to avoid this, but it seems that there is no such option.

It's a bug? Or am I missing something?

**Comment by 0xd4d** [comment]
The old sections are kept because there's no reliable way of finding all native methods, data, etc, so we can't re-create the whole file, we must keep the old one.

dnlib doesn't currently try to re-use old metadata locations to store the new metadata if it fits in the old location.
