### ISSUE TITLE
Moving debug information from one method to another

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#66]
Hi,

I'm looking for a way to move debug info from one method to another (which has the same body than the original).
I tried to change the `Rid` property, without success: the new method does not show any variable in the debugger and evaluating the `this` causes an error (in the debugger).
There is probably a simple way to do this, but I can't find it :sob: 

Thanks.

**Comment by 0xd4d** [comment]
Have you tried just copying the original method's `PdbScope` to the new method and all sequence points to the new method's instructions?

**Comment by picrap** [comment]
Yes I had this idea, however when I took a look at the `PdbScope` I couldn't figure how to use it. So if you give me event a small hint, that would be a great step for me.

**Comment by 0xd4d** [comment]
The scope contains info on which locals and namespaces are accessible in an instruction range (Start/End props). There can be nested scopes. The compiler could create a new scope each time you add `{` and `}` to your code.

If the methods are identical, same instructions in the same order, same locals in the same order, then the cloning can easily be done using a recursive method. You'd need to build dictionaries to map from old instructions to new instructions and old locals to new locals, where `toNew[oldInstrs[i]] == newInstrs[i]` (oldInstrs = oldMethod.Body.Instructions, newInstrs = newMethod.Body.Instructions)

Psuedo code of recursive clone method. Requires the dictionaries to have been initialized.

```C#
scope clone(scope a)
{
  var scope = new scope()
  scope.Start = toNew[a.Start]
  scope.End = a.End==null?null:toNew[a.End]
  scope.Namespaces.AddRange(a.Namespaces)
  foreach l in a.locals
    scope.locals.Add(toNew(l))
  foreach (var nested in a.Scopes)
    scope.Scopes.Add(clone(nested))
}
```

**Comment by picrap** [comment]
Thanks! I didn't notice there was a `Body.Scope` :+1:

**Comment by picrap** [comment]
Hi,

I finally copied the reference from one method to another (because I rewrite the original method body), however the variables are still screwed.
Even trying to evaluate the `this` value results in an error.
Is there any way to diagnose the generated debug info?

Thanks.

**Comment by picrap** [comment]
Latest news: I solved my problem by copying the whole `Body`... So far so good :smile: 
Thanks for help.
