### ISSUE TITLE
ldtoken GenericParam

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#68]
Hi,

I want to emit a `ldtoken`with a given `GenericParam` (to get something equivalent to C# `typeof(T)`), however I can't find a way to do this.
What have I missed?

Thanks.

**Comment by 0xd4d** [comment]
You can easily find out how the compiler does it by compiling the code and checking the instruction operand in the VS debugger.

```C#
class MyClass<T> {
  void Method<U>() {
    var a = typeof(T);
    var b = typeof(U);
  }
}

```

**Comment by picrap** [comment]
I already found out this, and already implemented this using Cecil :wink: 
However I can not find a way to do the same using dnlib, hence my question.

**Comment by 0xd4d** [comment]
That's the reason you should check it in a debugger to see what classes are being used.

**Comment by picrap** [comment]
How can I see what I need to use in dnlib using a debugger?

**Comment by 0xd4d** [comment]
Compile the code above, open it with dnlib, find the method, get the body, figure out which instruction contains the typeof(T) expression and store its operand in a variable. Use VS' watch/locals window to analyze the type (is it a TypeDef,  TypeRef or a TypeSpec, if TypeSpec, what is the TypeSig, etc?).

**Comment by picrap** [comment]
Wish me luck :smile:, but thanks anyway.

**Comment by 0xd4d** [comment]
```C#
class MyClass<T> {
	void Method<U>() {
		var a = typeof(T);
		var b = typeof(U);
	}
}
static class TestProgram {
	public static void Test() {
		var mod = ModuleDefMD.Load(typeof(TestProgram).Module);
		var type = mod.Find("MyClass`1", true);
		var method = type.FindMethod("Method");
		var instrs = method.Body.Instructions;
	}
}
```

Original code, with BP set @ end of method:
![pic1](https://cloud.githubusercontent.com/assets/1060731/16207987/53675848-3730-11e6-90c2-72a397928a83.png)

Inspect the state:
![pic2](https://cloud.githubusercontent.com/assets/1060731/16207988/5367c45e-3730-11e6-9f64-4080bfba6c31.png)

Add new code using VS' EnC (Edit and Continue) feature:
![pic3](https://cloud.githubusercontent.com/assets/1060731/16207989/5368d254-3730-11e6-9536-c9f9ae4dc15c.png)

Here's the GenericSig with the correct generic number:
![pic4](https://cloud.githubusercontent.com/assets/1060731/16207990/5368e8b6-3730-11e6-9b0c-c428b89477f0.png)

So it's possible to conclude that the compiler created a new `TypeSpec`. The argument to the constructor was a `GenericVar` whose `Number` property is set to `0`.
