### ISSUE TITLE
Maybe a mistake in the code

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnlib#77]
https://github.com/0xd4d/dnlib/blob/b8ca15ff341d7fcf9064f422388ecac65005947b/src/DotNet/Emit/DynamicMethodBodyReader.cs#L219

**Comment by 0xd4d** [comment]
What's wrong with the `if` statement?

**Comment by bprg** [comment]
`isStatic` is ``true``, ``else`` will be ignored.

**Comment by 0xd4d** [comment]
It's because instance methods aren't supported. The `isStatic` is declared at the top so it will be easy to turn it into a parameter in the future.
