### ISSUE TITLE
ExtensionAttribute.cs

### ISSUE THREAD

**Issue by tgiphil** [0xd4d/dnlib#78]
Can this method be removed? It's causing conflicts with the newer .NET frameworks which already have this method defined.

**Comment by 0xd4d** [comment]
You can also disable that warning by adding 1685 to your 'Suppress warnings' list.

**Comment by tgiphil** [comment]
Thanks; would you accept a pull request with a change to suppress 1685.

**Comment by 0xd4d** [comment]
It's not something you need to add to dnlib, only to projects that target a framework that already defines the attributes (eg. .NET Framework 4.0) and that uses dnlib. Or you can just remove the classes from dnlib and retarget it to eg. 4.0, could be easier.

**Comment by tgiphil** [comment]
Thanks; I like the first option.
