### ISSUE TITLE
[Question] How do I get a MemberRefUser from a property?

### ISSUE THREAD

**Issue by 0xFireball** [0xd4d/dnlib#79]
I want to be able to do this:

```
var debuggerTypeRef = new TypeRefUser(mod, "System.Diagnostics", "Debugger", factory.Module.CorLibTypes.AssemblyRef);

var isAttachedPropertySig = PropertySig.CreateInstance(mod.CorLibTypes.Boolean);
                
var debuggerAttachedPropertyRef = new MemberRefUser(mod, "IsAttached", isAttachedPropertySig, debuggerTypeRef);
```

However, the PropertySig is not allowed as a parameter to the `MemberRefUser` constructor.

Am I using the wrong approach? If so, can you please tell me what I can do instead?

I could not find any documentation.

**Comment by 0xd4d** [comment]
There are no references to properties, the code actually only uses references to the get and set methods (eg. get_IsAttachedProperty()), so you should be using `MethodSig` instead of `PropertySig`

**Comment by 0xd4d** [comment]
You should also update the name from `"IsAttached"` to `"get_IsAttached"`
