### ISSUE TITLE
How to retrieve source file from a Type?

### ISSUE THREAD

**Issue by tongbong** [0xd4d/dnlib#81]
Hello,
Let's say an assembly was loaded providing the type MyType:
`
var a = new MyType();
string url = GetSourceFileFor(a.GetType());
`
Is there a way to retrieve a source file from a Type using the PdbState of the ModuleDefMD?
Cheers.

**Comment by 0xd4d** [comment]
To get the `TypeDef`, use `module.Find(type.FullName, true)`.

The filename (not the file itself) can be found in the sequence points which are part of the instructions if the PDB file has been loaded. Most types are only present in one file, some are partial and could be present in more files:

```C#
var options = new ModuleCreationOptions {
	TryToLoadPdbFromDisk = true,
	// and any other options needed...
};
var mod = ModuleDefMD.Load(typeof(XXXXXXX).Assembly.Location, options);
var docs = new HashSet<string>(StringComparer.CurrentCultureIgnoreCase);
foreach (var type in mod.GetTypes()) {
	docs.Clear();
	foreach (var method in type.Methods) {
		var body = method.Body;
		if (body == null)
			continue;
		foreach (var instr in body.Instructions) {
			var seq = instr.SequencePoint;
			if (seq == null)
				continue;
			docs.Add(seq.Document.Url);
		}
	}
	Debug.WriteLine($"Type: {type.FullName}, File(s): {string.Join(", ", docs.ToArray())}");
}
```

**Comment by tongbong** [comment]
Simply brilliant and thanks for the quick answer.
