### ISSUE TITLE
Delete Resource - deleted resource name stay in assembly

### ISSUE THREAD

**Issue by Progress1** [0xd4d/dnlib#85]
I am deleting some image resource Resources.RemoveAt(i) which is working ok. After saving new assembly my specific resource is gone (checking also with dnSpy or Reflector) so this is working fine. If i open assembly with some hex editor i can still find string with deleted resource name inside. Maybe some bad defragment or rebuild resource section is needed? What can cause that this string stay inside?

**Comment by 0xd4d** [comment]
If it's a mixed mode assembly, the original file is re-used when writing the new file but the old content isn't overwritten. Perhaps that's what you're seeing.

**Comment by Progress1** [comment]
It's IL only (CLR Header Flags: 0x00020003). Test file has only 38kb (just one Msgbox + some obfuscation core). I send original and new one for comparing to you at de4dot gmail... Ok?

**Comment by 0xd4d** [comment]
Did you enable one of 'preserve heap offsets' options?

**Comment by Progress1** [comment]
I use for saving MetaDataOptions.Flags = PreserveAll | KeepOldMaxStack. PreserveAll contains also PreserveStringsOffsets - from DOC: Preserves all offsets in the #Strings heap (the original #Strings heap will be saved in the new file). Type names, field names, and other non-user strings are stored in the #Strings heap.
This probably caused that resource name stay after deleting inside. If yes, can cause removing flag PreserveStringsOffsets from save action any problems if .NET executable is obfuscated?

**Comment by 0xd4d** [comment]
If the obfuscator uses hard coded offsets to those heaps, then yes there'll probably be some failure at runtime. Most don't though.
