### ISSUE TITLE
Are there any plans to port this to .NET Core?

### ISSUE THREAD

**Issue by NickStrupat** [0xd4d/dnlib#86]
I took a peek already and it looks like a few things will need to change: serialization, memory-mapping...

**Comment by 0xd4d** [comment]
It's something I probably will do some day, but not in the near future.

**Comment by zwcloud** [comment]
Since .NET Standard 2.0 has been released, is it planned now?

**Comment by 0xd4d** [comment]
.NET Core 2.0 added support to load .NET Framework assemblies. Have you tried it yet?

**Comment by zwcloud** [comment]
Yes. Actually it has already been suported in .NET Core 1.0 or even earlier version.
To be exact, they are called [.NET Standard class library](https://docs.microsoft.com/en-us/dotnet/standard/class-libraries). For example, a .NET Standard class library can be used by all the platforms that support .NET Standard.

**Comment by 0xd4d** [comment]
I'm talking about non-modified .NET Framework assemblies. This is new in .NET Core 2.0

**Comment by zwcloud** [comment]
I just tried adding a .NET Framework 4.6.1 Class libarary to my .NET Core 2.0 App. It works.

But I should say, in theory, if the class library is built on .NET Framework 4.5+, it can be used with .NET Core projects. This is not new in .NET Core 2.0.

**Comment by zwcloud** [comment]
BTW, here is an issue you may be interested in: https://github.com/dotnet/coreclr/issues/13563
I'm stuck when trying to use ModPhuserEx( successor of ConfuserEx). I'm sure it is a .NET Core 2.0 specific issue. _dnlib_ works well on .NET Core 1.1/.NET Standard 1.6 assemblies.

> Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

**Comment by zwcloud** [comment]
> dnlib can't do anything about missing files.

No, it is not a missing file. I can't tell what the problem is but it seems .NET Core makes some modification to assembly loading/referancing procedures, which may possibly become a **trap** when you trying to port dnlib to .NET Core/Standard. I just hope this information will help you in further developing.

see also:
https://stackoverflow.com/questions/45021965/could-not-load-file-or-assembly-netstandard-version-2-0-0-0-reference
https://developercommunity.visualstudio.com/content/problem/97436/fakes-with-net-standard-20.html

**Comment by 0xd4d** [comment]
`dir /s/a/b "c:\Program Files (x86)\netstandard.dll"`

**Comment by zwcloud** [comment]
Actually it is there: `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\netstandard.dll` **in** the searching path.

**Comment by 0xd4d** [comment]
@SlowLogicBoy fixed this,  #155 . Latest master has a netstandard 2.0 project file.
