### ISSUE TITLE
UnmanagedExports / DllExport / .export

### ISSUE THREAD

**Issue by jspraul** [0xd4d/dnlib#87]
Can dnlib add [.vtdata / .vtentry / .vtfixup / .export](https://www.codeproject.com/articles/37675/simple-method-of-dll-export-without-c-cli) ?

C++/CLI, ILASM and [IKVM.Reflection](http://weblog.ikvm.net/PermaLink.aspx?guid=aeaa0190-2b32-45e6-a249-3c3cf126372b) can. Not sure about Mono.Cecil these days.

If you ever decide it's in-scope please let everyone currently search-and-replacing between ILDASM / ILASM ([UnmanagedExports](https://www.nuget.org/packages/UnmanagedExports) / [DllExport](https://github.com/3F/DllExport), etc.) know.

**Comment by 0xd4d** [comment]
It's not supported, however it supports saving modified C++/CLI assemblies.

I'll put this on my TO DO list, but it could take a while before I have time to do it.

**Comment by 0xd4d** [comment]
This has now been fixed, it's now possible to export managed methods. I've updated the README, search for `Exporting managed methods (DllExport)`.
