### ISSUE TITLE
How to correctly resolve types when editing .NET Core assembly?

### ISSUE THREAD

**Issue by nictaylr** [0xd4d/dnlib#88]
I'm editing a .NET Core assembly from a program running on .NET 4.6.
However, when I use `typeof(SomeBuiltinType)` and inject that into the .NET Core assembly, and I run the assembly, I get a Type not found issue. Obviously the type's in a different assembly or something because it's not found,, but I don't know how to get it to choose the intended type.

How could I get code referencing a type (let's say `System.Environment`) into a .NET Core assembly without breaking the .NET Core references?

My actual editing program runs on standard .NET Framework 4.6

**Comment by 0xd4d** [comment]
Try referencing the .NET Core reference assemblies instead of the implementation assemblies. You will need to update the assembly resolver so it only searches those assemblies (and doesn't resolve GAC assemblies).
