### ISSUE TITLE
Why can't get ValueTypeSig?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnlib#90]
var tr = mod.CorLibTypes.GetTypeRef("System", "DateTime");
tr.ToTypeSig=>ClassSig
tr.TryGetValueTypeSig=>null

**Comment by 0xd4d** [comment]
Add an assembly resolver so it can find out that it's a value type.

TryGetValueTypeSig() is used to get the value type sig if it's already a TypeSpec, which it isn't.

**Comment by CreateAndInject** [comment]
Thanks!
