### ISSUE TITLE
Call Generic Method

### ISSUE THREAD

**Issue by RexProg** [0xd4d/dnlib#91]
i want to call Generic Method
for example i want to call this :
`public static void meth<a>(a obj1,  a obj2){}`
i want call it like this :
`meth<int>(2, 3);`
how can i set <int>?

**Comment by 0xd4d** [comment]
This is something you can find out by looking at the IL instructions while debugging in Visual Studio. Compile such a method, load it in dnlib, find the method, get the instructions list, expand it in VS locals window, look at the created types.

**Comment by RexProg** [comment]
i know but i can't set int instead of a
for example:
`            var sizeofMethodDef = typeof(Marshal).GetMethods().Where(m => m.IsGenericMethod).Where(m =>
                m.GetParameters()[0].ParameterType ==
                m.GetGenericArguments()[0]).FirstOrDefault(n => n.Name == "SizeOf");
                        var sizeofMethod =
                            sizeofMethodDef.MakeGenericMethod(typeof(int);

                        mmDef.Body.Instructions.Insert(i,
                            new Instruction(OpCodes.Call, moduleDef.Import(sizeofMethod)));`
i can set Generic Method
can i use dnlib for do it?
Is there an equivalent of MakeGenericMethod in dnlib?

**Comment by 0xd4d** [comment]
That's why I wrote you should look at the code in the locals window. You'll see exactly what types you need to create. See eg. MethodSpec.
