### ISSUE TITLE
Loss of debug info in async methods

### ISSUE THREAD

**Issue by picrap** [0xd4d/dnlib#94]
Hi,

there seems to be a problem with debug info in `async` methods: local variables disappear (this is visible in the provided sample) and it seems that the trace (step over from debugger) is also broken (but this is not visible from the sample).

Here is how to reproduce the problem using the attached solution:
- first of all, if you run the debugger on the project `DnlibAsync`, when you trace into the method named `Async()`, you can see that the local variable is visible, and correctly set.
- now, run the `LoadSaveAssembly` project: it will load `DnlibAsync.exe` and `DnlibAsync.pdb` from `obj` directory using `dnlib` and simply write them to `bin`.
- when you start the debugger in the project `DnlibAsync`, now the local variable in `Async()` method has disappeared (the method works, the generated code has not changed, so this must be the debug info which has changed).

I tried used both symbol loaders (`PdbImplType.Managed` an `PdbImplType.MicrosoftCOM`) and get the same result.

Since the example is dumb as hell, I don't see a point I could have missed in my implementation (which of course, doesn't mean I 100% sure I made everything right 😎).
So, do you think this is a bug?

[DnlibAsync.zip](https://github.com/0xd4d/dnlib/files/692362/DnlibAsync.zip)

**Comment by 0xd4d** [comment]
It's because the compiler writes blobs of data to the PDB that isn't documented (until now with Roslyn perhaps since it's open source).

**Comment by Kahbazi** [comment]
So... is it a bug? Will it be fixed?

**Comment by 0xd4d** [comment]
It's a missing feature, `support undocumented PDB blobs`. This is something I plan on adding, but there's not enough time at the moment. I do accept PRs if you want to add this support.

**Comment by picrap** [comment]
I found some interesting doc here: https://github.com/dotnet/roslyn/blob/portable-pdb/docs/specs/PortablePdb-Metadata.md (especially an "Async method table" section), I'll see how dnlib works internally and if I can do something to help.

**Comment by picrap** [comment]
@0xd4d I think that the Async method table has much more to say, but the TableInfo structure you entered does not match the one I found in documentation. Could you give me your documentation sources, so I can compare and understand the difference?

**Comment by 0xd4d** [comment]
Which table are you talking about? The document you're reading is for portable PDBs, not the normal PDBs, although some of the blobs could possibly be identical.

These Roslyn dirs probably have more info:

https://github.com/dotnet/roslyn/tree/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Dependencies/CodeAnalysis.Metadata

https://github.com/dotnet/roslyn/tree/c752659a3626be9f9bd83e990bc1acf064e51dfd/src/Compilers/Core/Portable/PEWriter

**Comment by picrap** [comment]
I finally gave up on this, I had hard times getting in the code and my PDB skills are too low. Sorry about this, I guess you'll have to do it yourself.

**Comment by 0x084E** [comment]
Maybe part of the code for this could be borrowed from Mono.Cecil which has the same problem at the moment but there is now a pull request which fixes it.
https://github.com/jbevain/cecil/pull/353

**Comment by snekbaev** [comment]
Is there an update on this one? A two year old project just landed on my table which uses the latest MrAdvice. It's a bit hard to learn and develop with the current debugger behaviour :)

Thank you!

**Comment by picrap** [comment]
@0xd4d any schedule for this? I am quite stuck with this (and my projects are also impacted).

**Comment by 0xd4d** [comment]
@picrap I'll have a look at it this month, I don't know how long it will take. There's a lot of undocumented things, but source code (i.e., Roslyn, Pdb2Xml) exist.

**Comment by 0xd4d** [comment]
@picrap Try the latest master, I've updated the code, done some simple testing, will test more later.

**Comment by picrap** [comment]
This seems to work, dude! I'll make some more tests and let you know. Thanks for efficiency :)

**Comment by gautelo** [comment]
Sorry to post in a closed issue. I'm having this exact issue when working with portable pdb's, and I'm wondering what this repo is for. Are you fixing things in a private fork of dotnet, or are you trying to get fixes back upstream? If so, what is the status of the fix?

I'm not very github savvy, so having a bit of trouble figuring what's what and what links where etc.

**Comment by gautelo** [comment]
I do indeed. Thanks for clarifying.
