### ISSUE TITLE
DynamicMethodBodyReader issue?

### ISSUE THREAD

**Issue by AlcatrazDev** [0xd4d/dnlib#98]
Hello, i'm facing an issue with Exceptions Handler when reading a dynamic method, i'm not sure where the trouble is.

Also, this happened with one method only.

http://image.prntscr.com/image/6fbdba57c7c24e54b2dee8a8b544da3e.png

The dynamic method code and exceptions are set using DynamicILInfo.SetCode and DynamicILInfo.SetExceptions, that's why i'm not too sure where the problem comes from, it might be just an error setting the method exceptions.

Edit:

Alright, I think I managed to fix it, I've copied the Exception Handler reader from MethodBodyReader and used it in the DynamicMethodBodyReader, I have to perform more tests to check everything is working properly, but it seems so.

http://image.prntscr.com/image/086ed42fb150421babf1574abe7bc93e.png

If you change from the original code (CreateExceptionHandlers)
```c#
 eh.TryEnd = GetInstruction((uint)(reader.ReadSByte() + offs));
```
To
```c#
 eh.TryEnd = GetInstruction((uint)(reader.ReadByte() + offs));
```
Does the same job

I guess there was the bug, reading the Sbyte.

**Comment by 0xd4d** [comment]
Yes, looks like a bug. Do you want to send a PR and change the `ReadSByte` to `ReadByte`?

**Comment by AlcatrazDev** [comment]
I will if you want me to, once I get all right.

Apart from the ReadSbyte, there are some instructions that make me confused.

http://image.prntscr.com/image/2e6cb8f962be43669cef3391406b7a56.png

Which one is right?

**Comment by 0xd4d** [comment]
Yes, should be unsigned, I don't remember why I used signed there, since the real method body reader code uses unsigned integers.

**Comment by AlcatrazDev** [comment]
PR opened
